export const reflexiveVerbs = [
  'se lever',
  'se coucher',
  's’habiller',
  'se laver',
  'se brosser',
  'se réveiller',
  'se reposer',
  'se dépêcher',
  'se souvenir de',
  'se rendre compte de',
  's’intéresser à',
  's’ennuyer',
  'se fâcher',
  'se tromper',
  'se taire',
  's’asseoir',
  's’entendre avec',
  'se disputer (avec)',
  'se marier (avec)',
  'se divorcer',
  'se battre',
  's’en aller',
  'se rendre',
  'se servir de',
  's’apercevoir de',
  'se douter de',
  'se passer de',
  'se trouver',
  'se mettre à',
  'se faire à',
  'se demander',
  'se plaindre de',
  'se voir',
  's’imaginer',
  's’efforcer de',
  's’évanouir',
  's’indigner',
  's’apercevoir que',
  's’épanouir',
  's’en sortir',
  's’attendre à',
  's’interroger sur',
  'se heurter à',
  'se méfier de',
  'se replier sur soi-même',
  'se raviser',
  'se débrouiller',
  'se réconcilier',
  'se précipiter',
  'se figurer',
];
