INSERT INTO "Verb" ("name")
SELECT v.name
FROM (VALUES
  ('absoudre'),
  ('apprendre'),
  ('atteindre'),
  ('avoir'),
  ('boire'),
  ('clore'),
  ('comprendre'),
  ('conduire'),
  ('connaître'),
  ('craindre'),
  ('croire'),
  ('cuire'),
  ('découvrir'),
  ('devoir'),
  ('dire'),
  ('écrire'),
  ('éteindre'),
  ('être'),
  ('faire'),
  ('falloir'),
  ('inclure'),
  ('joindre'),
  ('lire'),
  ('mettre'),
  ('mourir'),
  ('naître'),
  ('offrir'),
  ('ouvrir'),
  ('peindre'),
  ('plaire'),
  ('pleuvoir'),
  ('pouvoir'),
  ('prendre'),
  ('produire'),
  ('recevoir'),
  ('resoudre'),
  ('rire'),
  ('s’apercevoir'),
  ('s’asseoir'),
  ('s’attendre'),
  ('s’efforcer'),
  ('s’en aller'),
  ('s’en sortir'),
  ('s’ennuyer'),
  ('s’entendre'),
  ('s’épanouir'),
  ('s’évanouir'),
  ('s’habiller'),
  ('s’imaginer'),
  ('s’indigner'),
  ('s’intéresser'),
  ('s’interroger'),
  ('savoir'),
  ('se battre'),
  ('se brosser'),
  ('se coucher'),
  ('se débrouiller'),
  ('se demander'),
  ('se dépêcher'),
  ('se disputer'),
  ('se divorcer'),
  ('se douter'),
  ('se fâcher'),
  ('se faire'),
  ('se figurer'),
  ('se heurter'),
  ('se laver'),
  ('se lever'),
  ('se marier'),
  ('se méfier'),
  ('se mettre'),
  ('se passer'),
  ('se plaindre'),
  ('se précipiter'),
  ('se raviser'),
  ('se réconcilier'),
  ('se rendre'),
  ('se rendre compte'),
  ('se replier sur soi-même'),
  ('se reposer'),
  ('se réveiller'),
  ('se servir'),
  ('se souvenir'),
  ('se taire'),
  ('se tromper'),
  ('se trouver'),
  ('se voir'),
  ('souffrir'),
  ('suivre'),
  ('surprendre'),
  ('tenir'),
  ('traduire'),
  ('valoir'),
  ('venir'),
  ('vivre'),
  ('voir'),
  ('vouloir')
) AS v(name)
WHERE NOT EXISTS (
  SELECT 1
  FROM "Verb" existing
  WHERE existing."name" = v.name
);
