INSERT INTO "Verb" ("name")
SELECT v.name
FROM (VALUES
  ('absoudre'),
  ('acheter'),
  ('aller'),
  ('appeler'),
  ('apprendre'),
  ('attendre'),
  ('atteindre'),
  ('avoir'),
  ('boire'),
  ('clore'),
  ('comprendre'),
  ('conduire'),
  ('connaître'),
  ('courir'),
  ('craindre'),
  ('croire'),
  ('cuire'),
  ('descendre'),
  ('découvrir'),
  ('devoir'),
  ('dire'),
  ('dormir'),
  ('écrire'),
  ('éteindre'),
  ('entendre'),
  ('envoyer'),
  ('être'),
  ('faire'),
  ('falloir'),
  ('inclure'),
  ('joindre'),
  ('jeter'),
  ('lire'),
  ('mettre'),
  ('mourir'),
  ('naître'),
  ('offrir'),
  ('ouvrir'),
  ('partir'),
  ('payer'),
  ('peindre'),
  ('perdre'),
  ('plaire'),
  ('pleuvoir'),
  ('pouvoir'),
  ('prendre'),
  ('préférer'),
  ('produire'),
  ('recevoir'),
  ('répondre'),
  ('resoudre'),
  ('rire'),
  ('s’apercevoir'),
  ('s’asseoir'),
  ('s’attendre'),
  ('s’efforcer'),
  ('s’en aller'),
  ('s’en sortir'),
  ('s’ennuyer'),
  ('s’entendre'),
  ('s’épanouir'),
  ('s’évanouir'),
  ('s’habiller'),
  ('s’imaginer'),
  ('s’indigner'),
  ('s’intéresser'),
  ('s’interroger'),
  ('savoir'),
  ('se battre'),
  ('se brosser'),
  ('se coucher'),
  ('se débrouiller'),
  ('se demander'),
  ('se dépêcher'),
  ('se disputer'),
  ('se divorcer'),
  ('se douter'),
  ('se fâcher'),
  ('se faire'),
  ('se figurer'),
  ('se heurter'),
  ('se laver'),
  ('se lever'),
  ('se marier'),
  ('se méfier'),
  ('se mettre'),
  ('se passer'),
  ('se plaindre'),
  ('se précipiter'),
  ('se raviser'),
  ('se réconcilier'),
  ('se rendre'),
  ('se rendre compte'),
  ('se replier sur soi-même'),
  ('se reposer'),
  ('se réveiller'),
  ('se servir'),
  ('se souvenir'),
  ('se taire'),
  ('se tromper'),
  ('se trouver'),
  ('se voir'),
  ('servir'),
  ('sortir'),
  ('souffrir'),
  ('suivre'),
  ('surprendre'),
  ('tenir'),
  ('traduire'),
  ('valoir'),
  ('vendre'),
  ('venir'),
  ('vivre'),
  ('voir'),
  ('manger'),
  ('nager'),
  ('voyager'),
  ('changer'),
  ('ranger'),
  ('partager'),
  ('corriger'),
  ('protéger'),
  ('interroger'),
  ('déménager'),
  ('commencer'),
  ('placer'),
  ('annoncer'),
  ('avancer'),
  ('lancer'),
  ('prononcer'),
  ('renoncer'),
  ('effacer'),
  ('menacer'),
  ('tracer'),
  ('étudier'),
  ('crier'),
  ('prier'),
  ('oublier'),
  ('marier'),
  ('copier'),
  ('publier'),
  ('appuyer'),
  ('ennuyer'),
  ('nettoyer'),
  ('vouloir')
) AS v(name)
WHERE NOT EXISTS (
  SELECT 1
  FROM "Verb" existing
  WHERE existing."name" = v.name
);
