INSERT INTO "Conjugation" ("verb_id", "subject_id", "tense_id", "text")
SELECT v."id", s."id", t."id", c."text"
FROM (
  VALUES
    ('être', 'je', 'Passé Composé', 'j''ai été'),
    ('être', 'tu', 'Passé Composé', 'tu as été'),
    ('être', 'il', 'Passé Composé', 'il a été'),
    ('être', 'elle', 'Passé Composé', 'elle a été'),
    ('être', 'on', 'Passé Composé', 'on a été'),
    ('être', 'nous', 'Passé Composé', 'nous avons été'),
    ('être', 'vous', 'Passé Composé', 'vous avez été'),
    ('être', 'ils', 'Passé Composé', 'ils ont été'),
    ('être', 'elles', 'Passé Composé', 'elles ont été'),
    ('avoir', 'je', 'Passé Composé', 'j''ai eu'),
    ('avoir', 'tu', 'Passé Composé', 'tu as eu'),
    ('avoir', 'il', 'Passé Composé', 'il a eu'),
    ('avoir', 'elle', 'Passé Composé', 'elle a eu'),
    ('avoir', 'on', 'Passé Composé', 'on a eu'),
    ('avoir', 'nous', 'Passé Composé', 'nous avons eu'),
    ('avoir', 'vous', 'Passé Composé', 'vous avez eu'),
    ('avoir', 'ils', 'Passé Composé', 'ils ont eu'),
    ('avoir', 'elles', 'Passé Composé', 'elles ont eu'),
    ('faire', 'je', 'Passé Composé', 'j''ai fait'),
    ('faire', 'tu', 'Passé Composé', 'tu as fait'),
    ('faire', 'il', 'Passé Composé', 'il a fait'),
    ('faire', 'elle', 'Passé Composé', 'elle a fait'),
    ('faire', 'on', 'Passé Composé', 'on a fait'),
    ('faire', 'nous', 'Passé Composé', 'nous avons fait'),
    ('faire', 'vous', 'Passé Composé', 'vous avez fait'),
    ('faire', 'ils', 'Passé Composé', 'ils ont fait'),
    ('faire', 'elles', 'Passé Composé', 'elles ont fait'),
    ('mettre', 'je', 'Passé Composé', 'j''ai mis'),
    ('mettre', 'tu', 'Passé Composé', 'tu as mis'),
    ('mettre', 'il', 'Passé Composé', 'il a mis'),
    ('mettre', 'elle', 'Passé Composé', 'elle a mis'),
    ('mettre', 'on', 'Passé Composé', 'on a mis'),
    ('mettre', 'nous', 'Passé Composé', 'nous avons mis'),
    ('mettre', 'vous', 'Passé Composé', 'vous avez mis'),
    ('mettre', 'ils', 'Passé Composé', 'ils ont mis'),
    ('mettre', 'elles', 'Passé Composé', 'elles ont mis'),
    ('prendre', 'je', 'Passé Composé', 'j''ai pris'),
    ('prendre', 'tu', 'Passé Composé', 'tu as pris'),
    ('prendre', 'il', 'Passé Composé', 'il a pris'),
    ('prendre', 'elle', 'Passé Composé', 'elle a pris'),
    ('prendre', 'on', 'Passé Composé', 'on a pris'),
    ('prendre', 'nous', 'Passé Composé', 'nous avons pris'),
    ('prendre', 'vous', 'Passé Composé', 'vous avez pris'),
    ('prendre', 'ils', 'Passé Composé', 'ils ont pris'),
    ('prendre', 'elles', 'Passé Composé', 'elles ont pris'),
    ('dire', 'je', 'Passé Composé', 'j''ai dit'),
    ('dire', 'tu', 'Passé Composé', 'tu as dit'),
    ('dire', 'il', 'Passé Composé', 'il a dit'),
    ('dire', 'elle', 'Passé Composé', 'elle a dit'),
    ('dire', 'on', 'Passé Composé', 'on a dit'),
    ('dire', 'nous', 'Passé Composé', 'nous avons dit'),
    ('dire', 'vous', 'Passé Composé', 'vous avez dit'),
    ('dire', 'ils', 'Passé Composé', 'ils ont dit'),
    ('dire', 'elles', 'Passé Composé', 'elles ont dit'),
    ('écrire', 'je', 'Passé Composé', 'j''ai écrit'),
    ('écrire', 'tu', 'Passé Composé', 'tu as écrit'),
    ('écrire', 'il', 'Passé Composé', 'il a écrit'),
    ('écrire', 'elle', 'Passé Composé', 'elle a écrit'),
    ('écrire', 'on', 'Passé Composé', 'on a écrit'),
    ('écrire', 'nous', 'Passé Composé', 'nous avons écrit'),
    ('écrire', 'vous', 'Passé Composé', 'vous avez écrit'),
    ('écrire', 'ils', 'Passé Composé', 'ils ont écrit'),
    ('écrire', 'elles', 'Passé Composé', 'elles ont écrit'),
    ('voir', 'je', 'Passé Composé', 'j''ai vu'),
    ('voir', 'tu', 'Passé Composé', 'tu as vu'),
    ('voir', 'il', 'Passé Composé', 'il a vu'),
    ('voir', 'elle', 'Passé Composé', 'elle a vu'),
    ('voir', 'on', 'Passé Composé', 'on a vu'),
    ('voir', 'nous', 'Passé Composé', 'nous avons vu'),
    ('voir', 'vous', 'Passé Composé', 'vous avez vu'),
    ('voir', 'ils', 'Passé Composé', 'ils ont vu'),
    ('voir', 'elles', 'Passé Composé', 'elles ont vu'),
    ('pouvoir', 'je', 'Passé Composé', 'j''ai pu'),
    ('pouvoir', 'tu', 'Passé Composé', 'tu as pu'),
    ('pouvoir', 'il', 'Passé Composé', 'il a pu'),
    ('pouvoir', 'elle', 'Passé Composé', 'elle a pu'),
    ('pouvoir', 'on', 'Passé Composé', 'on a pu'),
    ('pouvoir', 'nous', 'Passé Composé', 'nous avons pu'),
    ('pouvoir', 'vous', 'Passé Composé', 'vous avez pu'),
    ('pouvoir', 'ils', 'Passé Composé', 'ils ont pu'),
    ('pouvoir', 'elles', 'Passé Composé', 'elles ont pu'),
    ('vouloir', 'je', 'Passé Composé', 'j''ai voulu'),
    ('vouloir', 'tu', 'Passé Composé', 'tu as voulu'),
    ('vouloir', 'il', 'Passé Composé', 'il a voulu'),
    ('vouloir', 'elle', 'Passé Composé', 'elle a voulu'),
    ('vouloir', 'on', 'Passé Composé', 'on a voulu'),
    ('vouloir', 'nous', 'Passé Composé', 'nous avons voulu'),
    ('vouloir', 'vous', 'Passé Composé', 'vous avez voulu'),
    ('vouloir', 'ils', 'Passé Composé', 'ils ont voulu'),
    ('vouloir', 'elles', 'Passé Composé', 'elles ont voulu'),
    ('savoir', 'je', 'Passé Composé', 'j''ai su'),
    ('savoir', 'tu', 'Passé Composé', 'tu as su'),
    ('savoir', 'il', 'Passé Composé', 'il a su'),
    ('savoir', 'elle', 'Passé Composé', 'elle a su'),
    ('savoir', 'on', 'Passé Composé', 'on a su'),
    ('savoir', 'nous', 'Passé Composé', 'nous avons su'),
    ('savoir', 'vous', 'Passé Composé', 'vous avez su'),
    ('savoir', 'ils', 'Passé Composé', 'ils ont su'),
    ('savoir', 'elles', 'Passé Composé', 'elles ont su'),
    ('connaître', 'je', 'Passé Composé', 'j''ai connu'),
    ('connaître', 'tu', 'Passé Composé', 'tu as connu'),
    ('connaître', 'il', 'Passé Composé', 'il a connu'),
    ('connaître', 'elle', 'Passé Composé', 'elle a connu'),
    ('connaître', 'on', 'Passé Composé', 'on a connu'),
    ('connaître', 'nous', 'Passé Composé', 'nous avons connu'),
    ('connaître', 'vous', 'Passé Composé', 'vous avez connu'),
    ('connaître', 'ils', 'Passé Composé', 'ils ont connu'),
    ('connaître', 'elles', 'Passé Composé', 'elles ont connu'),
    ('venir', 'je', 'Passé Composé', 'je suis venu'),
    ('venir', 'tu', 'Passé Composé', 'tu es venu'),
    ('venir', 'il', 'Passé Composé', 'il est venu'),
    ('venir', 'elle', 'Passé Composé', 'elle est venue'),
    ('venir', 'on', 'Passé Composé', 'on est venu'),
    ('venir', 'nous', 'Passé Composé', 'nous sommes venus'),
    ('venir', 'vous', 'Passé Composé', 'vous êtes venus'),
    ('venir', 'ils', 'Passé Composé', 'ils sont venus'),
    ('venir', 'elles', 'Passé Composé', 'elles sont venues'),
    ('devoir', 'je', 'Passé Composé', 'j''ai dû'),
    ('devoir', 'tu', 'Passé Composé', 'tu as dû'),
    ('devoir', 'il', 'Passé Composé', 'il a dû'),
    ('devoir', 'elle', 'Passé Composé', 'elle a dû'),
    ('devoir', 'on', 'Passé Composé', 'on a dû'),
    ('devoir', 'nous', 'Passé Composé', 'nous avons dû'),
    ('devoir', 'vous', 'Passé Composé', 'vous avez dû'),
    ('devoir', 'ils', 'Passé Composé', 'ils ont dû'),
    ('devoir', 'elles', 'Passé Composé', 'elles ont dû'),
    ('croire', 'je', 'Passé Composé', 'j''ai cru'),
    ('croire', 'tu', 'Passé Composé', 'tu as cru'),
    ('croire', 'il', 'Passé Composé', 'il a cru'),
    ('croire', 'elle', 'Passé Composé', 'elle a cru'),
    ('croire', 'on', 'Passé Composé', 'on a cru'),
    ('croire', 'nous', 'Passé Composé', 'nous avons cru'),
    ('croire', 'vous', 'Passé Composé', 'vous avez cru'),
    ('croire', 'ils', 'Passé Composé', 'ils ont cru'),
    ('croire', 'elles', 'Passé Composé', 'elles ont cru'),
    ('boire', 'je', 'Passé Composé', 'j''ai bu'),
    ('boire', 'tu', 'Passé Composé', 'tu as bu'),
    ('boire', 'il', 'Passé Composé', 'il a bu'),
    ('boire', 'elle', 'Passé Composé', 'elle a bu'),
    ('boire', 'on', 'Passé Composé', 'on a bu'),
    ('boire', 'nous', 'Passé Composé', 'nous avons bu'),
    ('boire', 'vous', 'Passé Composé', 'vous avez bu'),
    ('boire', 'ils', 'Passé Composé', 'ils ont bu'),
    ('boire', 'elles', 'Passé Composé', 'elles ont bu'),
    ('lire', 'je', 'Passé Composé', 'j''ai lu'),
    ('lire', 'tu', 'Passé Composé', 'tu as lu'),
    ('lire', 'il', 'Passé Composé', 'il a lu'),
    ('lire', 'elle', 'Passé Composé', 'elle a lu'),
    ('lire', 'on', 'Passé Composé', 'on a lu'),
    ('lire', 'nous', 'Passé Composé', 'nous avons lu'),
    ('lire', 'vous', 'Passé Composé', 'vous avez lu'),
    ('lire', 'ils', 'Passé Composé', 'ils ont lu'),
    ('lire', 'elles', 'Passé Composé', 'elles ont lu'),
    ('vivre', 'je', 'Passé Composé', 'j''ai vécu'),
    ('vivre', 'tu', 'Passé Composé', 'tu as vécu'),
    ('vivre', 'il', 'Passé Composé', 'il a vécu'),
    ('vivre', 'elle', 'Passé Composé', 'elle a vécu'),
    ('vivre', 'on', 'Passé Composé', 'on a vécu'),
    ('vivre', 'nous', 'Passé Composé', 'nous avons vécu'),
    ('vivre', 'vous', 'Passé Composé', 'vous avez vécu'),
    ('vivre', 'ils', 'Passé Composé', 'ils ont vécu'),
    ('vivre', 'elles', 'Passé Composé', 'elles ont vécu'),
    ('recevoir', 'je', 'Passé Composé', 'j''ai reçu'),
    ('recevoir', 'tu', 'Passé Composé', 'tu as reçu'),
    ('recevoir', 'il', 'Passé Composé', 'il a reçu'),
    ('recevoir', 'elle', 'Passé Composé', 'elle a reçu'),
    ('recevoir', 'on', 'Passé Composé', 'on a reçu'),
    ('recevoir', 'nous', 'Passé Composé', 'nous avons reçu'),
    ('recevoir', 'vous', 'Passé Composé', 'vous avez reçu'),
    ('recevoir', 'ils', 'Passé Composé', 'ils ont reçu'),
    ('recevoir', 'elles', 'Passé Composé', 'elles ont reçu'),
    ('ouvrir', 'je', 'Passé Composé', 'j''ai ouvert'),
    ('ouvrir', 'tu', 'Passé Composé', 'tu as ouvert'),
    ('ouvrir', 'il', 'Passé Composé', 'il a ouvert'),
    ('ouvrir', 'elle', 'Passé Composé', 'elle a ouvert'),
    ('ouvrir', 'on', 'Passé Composé', 'on a ouvert'),
    ('ouvrir', 'nous', 'Passé Composé', 'nous avons ouvert'),
    ('ouvrir', 'vous', 'Passé Composé', 'vous avez ouvert'),
    ('ouvrir', 'ils', 'Passé Composé', 'ils ont ouvert'),
    ('ouvrir', 'elles', 'Passé Composé', 'elles ont ouvert'),
    ('offrir', 'je', 'Passé Composé', 'j''ai offert'),
    ('offrir', 'tu', 'Passé Composé', 'tu as offert'),
    ('offrir', 'il', 'Passé Composé', 'il a offert'),
    ('offrir', 'elle', 'Passé Composé', 'elle a offert'),
    ('offrir', 'on', 'Passé Composé', 'on a offert'),
    ('offrir', 'nous', 'Passé Composé', 'nous avons offert'),
    ('offrir', 'vous', 'Passé Composé', 'vous avez offert'),
    ('offrir', 'ils', 'Passé Composé', 'ils ont offert'),
    ('offrir', 'elles', 'Passé Composé', 'elles ont offert'),
    ('naître', 'je', 'Passé Composé', 'je suis né'),
    ('naître', 'tu', 'Passé Composé', 'tu es né'),
    ('naître', 'il', 'Passé Composé', 'il est né'),
    ('naître', 'elle', 'Passé Composé', 'elle est née'),
    ('naître', 'on', 'Passé Composé', 'on est né'),
    ('naître', 'nous', 'Passé Composé', 'nous sommes nés'),
    ('naître', 'vous', 'Passé Composé', 'vous êtes nés'),
    ('naître', 'ils', 'Passé Composé', 'ils sont nés'),
    ('naître', 'elles', 'Passé Composé', 'elles sont nées'),
    ('mourir', 'je', 'Passé Composé', 'je suis mort'),
    ('mourir', 'tu', 'Passé Composé', 'tu es mort'),
    ('mourir', 'il', 'Passé Composé', 'il est mort'),
    ('mourir', 'elle', 'Passé Composé', 'elle est morte'),
    ('mourir', 'on', 'Passé Composé', 'on est mort'),
    ('mourir', 'nous', 'Passé Composé', 'nous sommes morts'),
    ('mourir', 'vous', 'Passé Composé', 'vous êtes morts'),
    ('mourir', 'ils', 'Passé Composé', 'ils sont morts'),
    ('mourir', 'elles', 'Passé Composé', 'elles sont mortes'),
    ('tenir', 'je', 'Passé Composé', 'j''ai tenu'),
    ('tenir', 'tu', 'Passé Composé', 'tu as tenu'),
    ('tenir', 'il', 'Passé Composé', 'il a tenu'),
    ('tenir', 'elle', 'Passé Composé', 'elle a tenu'),
    ('tenir', 'on', 'Passé Composé', 'on a tenu'),
    ('tenir', 'nous', 'Passé Composé', 'nous avons tenu'),
    ('tenir', 'vous', 'Passé Composé', 'vous avez tenu'),
    ('tenir', 'ils', 'Passé Composé', 'ils ont tenu'),
    ('tenir', 'elles', 'Passé Composé', 'elles ont tenu'),
    ('suivre', 'je', 'Passé Composé', 'j''ai suivi'),
    ('suivre', 'tu', 'Passé Composé', 'tu as suivi'),
    ('suivre', 'il', 'Passé Composé', 'il a suivi'),
    ('suivre', 'elle', 'Passé Composé', 'elle a suivi'),
    ('suivre', 'on', 'Passé Composé', 'on a suivi'),
    ('suivre', 'nous', 'Passé Composé', 'nous avons suivi'),
    ('suivre', 'vous', 'Passé Composé', 'vous avez suivi'),
    ('suivre', 'ils', 'Passé Composé', 'ils ont suivi'),
    ('suivre', 'elles', 'Passé Composé', 'elles ont suivi'),
    ('rire', 'je', 'Passé Composé', 'j''ai ri'),
    ('rire', 'tu', 'Passé Composé', 'tu as ri'),
    ('rire', 'il', 'Passé Composé', 'il a ri'),
    ('rire', 'elle', 'Passé Composé', 'elle a ri'),
    ('rire', 'on', 'Passé Composé', 'on a ri'),
    ('rire', 'nous', 'Passé Composé', 'nous avons ri'),
    ('rire', 'vous', 'Passé Composé', 'vous avez ri'),
    ('rire', 'ils', 'Passé Composé', 'ils ont ri'),
    ('rire', 'elles', 'Passé Composé', 'elles ont ri'),
    ('plaire', 'je', 'Passé Composé', 'j''ai plu'),
    ('plaire', 'tu', 'Passé Composé', 'tu as plu'),
    ('plaire', 'il', 'Passé Composé', 'il a plu'),
    ('plaire', 'elle', 'Passé Composé', 'elle a plu'),
    ('plaire', 'on', 'Passé Composé', 'on a plu'),
    ('plaire', 'nous', 'Passé Composé', 'nous avons plu'),
    ('plaire', 'vous', 'Passé Composé', 'vous avez plu'),
    ('plaire', 'ils', 'Passé Composé', 'ils ont plu'),
    ('plaire', 'elles', 'Passé Composé', 'elles ont plu'),
    ('falloir', 'je', 'Passé Composé', 'j''ai fallu'),
    ('falloir', 'tu', 'Passé Composé', 'tu as fallu'),
    ('falloir', 'il', 'Passé Composé', 'il a fallu'),
    ('falloir', 'elle', 'Passé Composé', 'elle a fallu'),
    ('falloir', 'on', 'Passé Composé', 'on a fallu'),
    ('falloir', 'nous', 'Passé Composé', 'nous avons fallu'),
    ('falloir', 'vous', 'Passé Composé', 'vous avez fallu'),
    ('falloir', 'ils', 'Passé Composé', 'ils ont fallu'),
    ('falloir', 'elles', 'Passé Composé', 'elles ont fallu'),
    ('valoir', 'je', 'Passé Composé', 'j''ai valu'),
    ('valoir', 'tu', 'Passé Composé', 'tu as valu'),
    ('valoir', 'il', 'Passé Composé', 'il a valu'),
    ('valoir', 'elle', 'Passé Composé', 'elle a valu'),
    ('valoir', 'on', 'Passé Composé', 'on a valu'),
    ('valoir', 'nous', 'Passé Composé', 'nous avons valu'),
    ('valoir', 'vous', 'Passé Composé', 'vous avez valu'),
    ('valoir', 'ils', 'Passé Composé', 'ils ont valu'),
    ('valoir', 'elles', 'Passé Composé', 'elles ont valu'),
    ('pleuvoir', 'je', 'Passé Composé', 'il a plu'),
    ('pleuvoir', 'tu', 'Passé Composé', 'il a plu'),
    ('pleuvoir', 'il', 'Passé Composé', 'il a plu'),
    ('pleuvoir', 'elle', 'Passé Composé', 'il a plu'),
    ('pleuvoir', 'on', 'Passé Composé', 'il a plu'),
    ('pleuvoir', 'nous', 'Passé Composé', 'il a plu'),
    ('pleuvoir', 'vous', 'Passé Composé', 'il a plu'),
    ('pleuvoir', 'ils', 'Passé Composé', 'il a plu'),
    ('pleuvoir', 'elles', 'Passé Composé', 'il a plu'),
    ('apprendre', 'je', 'Passé Composé', 'j''ai appris'),
    ('apprendre', 'tu', 'Passé Composé', 'tu as appris'),
    ('apprendre', 'il', 'Passé Composé', 'il a appris'),
    ('apprendre', 'elle', 'Passé Composé', 'elle a appris'),
    ('apprendre', 'on', 'Passé Composé', 'on a appris'),
    ('apprendre', 'nous', 'Passé Composé', 'nous avons appris'),
    ('apprendre', 'vous', 'Passé Composé', 'vous avez appris'),
    ('apprendre', 'ils', 'Passé Composé', 'ils ont appris'),
    ('apprendre', 'elles', 'Passé Composé', 'elles ont appris'),
    ('comprendre', 'je', 'Passé Composé', 'j''ai compris'),
    ('comprendre', 'tu', 'Passé Composé', 'tu as compris'),
    ('comprendre', 'il', 'Passé Composé', 'il a compris'),
    ('comprendre', 'elle', 'Passé Composé', 'elle a compris'),
    ('comprendre', 'on', 'Passé Composé', 'on a compris'),
    ('comprendre', 'nous', 'Passé Composé', 'nous avons compris'),
    ('comprendre', 'vous', 'Passé Composé', 'vous avez compris'),
    ('comprendre', 'ils', 'Passé Composé', 'ils ont compris'),
    ('comprendre', 'elles', 'Passé Composé', 'elles ont compris'),
    ('surprendre', 'je', 'Passé Composé', 'j''ai surpris'),
    ('surprendre', 'tu', 'Passé Composé', 'tu as surpris'),
    ('surprendre', 'il', 'Passé Composé', 'il a surpris'),
    ('surprendre', 'elle', 'Passé Composé', 'elle a surpris'),
    ('surprendre', 'on', 'Passé Composé', 'on a surpris'),
    ('surprendre', 'nous', 'Passé Composé', 'nous avons surpris'),
    ('surprendre', 'vous', 'Passé Composé', 'vous avez surpris'),
    ('surprendre', 'ils', 'Passé Composé', 'ils ont surpris'),
    ('surprendre', 'elles', 'Passé Composé', 'elles ont surpris'),
    ('découvrir', 'je', 'Passé Composé', 'j''ai découvert'),
    ('découvrir', 'tu', 'Passé Composé', 'tu as découvert'),
    ('découvrir', 'il', 'Passé Composé', 'il a découvert'),
    ('découvrir', 'elle', 'Passé Composé', 'elle a découvert'),
    ('découvrir', 'on', 'Passé Composé', 'on a découvert'),
    ('découvrir', 'nous', 'Passé Composé', 'nous avons découvert'),
    ('découvrir', 'vous', 'Passé Composé', 'vous avez découvert'),
    ('découvrir', 'ils', 'Passé Composé', 'ils ont découvert'),
    ('découvrir', 'elles', 'Passé Composé', 'elles ont découvert'),
    ('souffrir', 'je', 'Passé Composé', 'j''ai souffert'),
    ('souffrir', 'tu', 'Passé Composé', 'tu as souffert'),
    ('souffrir', 'il', 'Passé Composé', 'il a souffert'),
    ('souffrir', 'elle', 'Passé Composé', 'elle a souffert'),
    ('souffrir', 'on', 'Passé Composé', 'on a souffert'),
    ('souffrir', 'nous', 'Passé Composé', 'nous avons souffert'),
    ('souffrir', 'vous', 'Passé Composé', 'vous avez souffert'),
    ('souffrir', 'ils', 'Passé Composé', 'ils ont souffert'),
    ('souffrir', 'elles', 'Passé Composé', 'elles ont souffert'),
    ('conduire', 'je', 'Passé Composé', 'j''ai conduit'),
    ('conduire', 'tu', 'Passé Composé', 'tu as conduit'),
    ('conduire', 'il', 'Passé Composé', 'il a conduit'),
    ('conduire', 'elle', 'Passé Composé', 'elle a conduit'),
    ('conduire', 'on', 'Passé Composé', 'on a conduit'),
    ('conduire', 'nous', 'Passé Composé', 'nous avons conduit'),
    ('conduire', 'vous', 'Passé Composé', 'vous avez conduit'),
    ('conduire', 'ils', 'Passé Composé', 'ils ont conduit'),
    ('conduire', 'elles', 'Passé Composé', 'elles ont conduit'),
    ('produire', 'je', 'Passé Composé', 'j''ai produit'),
    ('produire', 'tu', 'Passé Composé', 'tu as produit'),
    ('produire', 'il', 'Passé Composé', 'il a produit'),
    ('produire', 'elle', 'Passé Composé', 'elle a produit'),
    ('produire', 'on', 'Passé Composé', 'on a produit'),
    ('produire', 'nous', 'Passé Composé', 'nous avons produit'),
    ('produire', 'vous', 'Passé Composé', 'vous avez produit'),
    ('produire', 'ils', 'Passé Composé', 'ils ont produit'),
    ('produire', 'elles', 'Passé Composé', 'elles ont produit'),
    ('traduire', 'je', 'Passé Composé', 'j''ai traduit'),
    ('traduire', 'tu', 'Passé Composé', 'tu as traduit'),
    ('traduire', 'il', 'Passé Composé', 'il a traduit'),
    ('traduire', 'elle', 'Passé Composé', 'elle a traduit'),
    ('traduire', 'on', 'Passé Composé', 'on a traduit'),
    ('traduire', 'nous', 'Passé Composé', 'nous avons traduit'),
    ('traduire', 'vous', 'Passé Composé', 'vous avez traduit'),
    ('traduire', 'ils', 'Passé Composé', 'ils ont traduit'),
    ('traduire', 'elles', 'Passé Composé', 'elles ont traduit'),
    ('atteindre', 'je', 'Passé Composé', 'j''ai atteint'),
    ('atteindre', 'tu', 'Passé Composé', 'tu as atteint'),
    ('atteindre', 'il', 'Passé Composé', 'il a atteint'),
    ('atteindre', 'elle', 'Passé Composé', 'elle a atteint'),
    ('atteindre', 'on', 'Passé Composé', 'on a atteint'),
    ('atteindre', 'nous', 'Passé Composé', 'nous avons atteint'),
    ('atteindre', 'vous', 'Passé Composé', 'vous avez atteint'),
    ('atteindre', 'ils', 'Passé Composé', 'ils ont atteint'),
    ('atteindre', 'elles', 'Passé Composé', 'elles ont atteint'),
    ('craindre', 'je', 'Passé Composé', 'j''ai craint'),
    ('craindre', 'tu', 'Passé Composé', 'tu as craint'),
    ('craindre', 'il', 'Passé Composé', 'il a craint'),
    ('craindre', 'elle', 'Passé Composé', 'elle a craint'),
    ('craindre', 'on', 'Passé Composé', 'on a craint'),
    ('craindre', 'nous', 'Passé Composé', 'nous avons craint'),
    ('craindre', 'vous', 'Passé Composé', 'vous avez craint'),
    ('craindre', 'ils', 'Passé Composé', 'ils ont craint'),
    ('craindre', 'elles', 'Passé Composé', 'elles ont craint'),
    ('éteindre', 'je', 'Passé Composé', 'j''ai éteint'),
    ('éteindre', 'tu', 'Passé Composé', 'tu as éteint'),
    ('éteindre', 'il', 'Passé Composé', 'il a éteint'),
    ('éteindre', 'elle', 'Passé Composé', 'elle a éteint'),
    ('éteindre', 'on', 'Passé Composé', 'on a éteint'),
    ('éteindre', 'nous', 'Passé Composé', 'nous avons éteint'),
    ('éteindre', 'vous', 'Passé Composé', 'vous avez éteint'),
    ('éteindre', 'ils', 'Passé Composé', 'ils ont éteint'),
    ('éteindre', 'elles', 'Passé Composé', 'elles ont éteint'),
    ('joindre', 'je', 'Passé Composé', 'j''ai joint'),
    ('joindre', 'tu', 'Passé Composé', 'tu as joint'),
    ('joindre', 'il', 'Passé Composé', 'il a joint'),
    ('joindre', 'elle', 'Passé Composé', 'elle a joint'),
    ('joindre', 'on', 'Passé Composé', 'on a joint'),
    ('joindre', 'nous', 'Passé Composé', 'nous avons joint'),
    ('joindre', 'vous', 'Passé Composé', 'vous avez joint'),
    ('joindre', 'ils', 'Passé Composé', 'ils ont joint'),
    ('joindre', 'elles', 'Passé Composé', 'elles ont joint'),
    ('peindre', 'je', 'Passé Composé', 'j''ai peint'),
    ('peindre', 'tu', 'Passé Composé', 'tu as peint'),
    ('peindre', 'il', 'Passé Composé', 'il a peint'),
    ('peindre', 'elle', 'Passé Composé', 'elle a peint'),
    ('peindre', 'on', 'Passé Composé', 'on a peint'),
    ('peindre', 'nous', 'Passé Composé', 'nous avons peint'),
    ('peindre', 'vous', 'Passé Composé', 'vous avez peint'),
    ('peindre', 'ils', 'Passé Composé', 'ils ont peint'),
    ('peindre', 'elles', 'Passé Composé', 'elles ont peint'),
    ('clore', 'je', 'Passé Composé', 'j''ai clos'),
    ('clore', 'tu', 'Passé Composé', 'tu as clos'),
    ('clore', 'il', 'Passé Composé', 'il a clos'),
    ('clore', 'elle', 'Passé Composé', 'elle a clos'),
    ('clore', 'on', 'Passé Composé', 'on a clos'),
    ('clore', 'nous', 'Passé Composé', 'nous avons clos'),
    ('clore', 'vous', 'Passé Composé', 'vous avez clos'),
    ('clore', 'ils', 'Passé Composé', 'ils ont clos'),
    ('clore', 'elles', 'Passé Composé', 'elles ont clos'),
    ('inclure', 'je', 'Passé Composé', 'j''ai inclus'),
    ('inclure', 'tu', 'Passé Composé', 'tu as inclus'),
    ('inclure', 'il', 'Passé Composé', 'il a inclus'),
    ('inclure', 'elle', 'Passé Composé', 'elle a inclus'),
    ('inclure', 'on', 'Passé Composé', 'on a inclus'),
    ('inclure', 'nous', 'Passé Composé', 'nous avons inclus'),
    ('inclure', 'vous', 'Passé Composé', 'vous avez inclus'),
    ('inclure', 'ils', 'Passé Composé', 'ils ont inclus'),
    ('inclure', 'elles', 'Passé Composé', 'elles ont inclus'),
    ('cuire', 'je', 'Passé Composé', 'j''ai cuit'),
    ('cuire', 'tu', 'Passé Composé', 'tu as cuit'),
    ('cuire', 'il', 'Passé Composé', 'il a cuit'),
    ('cuire', 'elle', 'Passé Composé', 'elle a cuit'),
    ('cuire', 'on', 'Passé Composé', 'on a cuit'),
    ('cuire', 'nous', 'Passé Composé', 'nous avons cuit'),
    ('cuire', 'vous', 'Passé Composé', 'vous avez cuit'),
    ('cuire', 'ils', 'Passé Composé', 'ils ont cuit'),
    ('cuire', 'elles', 'Passé Composé', 'elles ont cuit'),
    ('resoudre', 'je', 'Passé Composé', 'j''ai résolu'),
    ('resoudre', 'tu', 'Passé Composé', 'tu as résolu'),
    ('resoudre', 'il', 'Passé Composé', 'il a résolu'),
    ('resoudre', 'elle', 'Passé Composé', 'elle a résolu'),
    ('resoudre', 'on', 'Passé Composé', 'on a résolu'),
    ('resoudre', 'nous', 'Passé Composé', 'nous avons résolu'),
    ('resoudre', 'vous', 'Passé Composé', 'vous avez résolu'),
    ('resoudre', 'ils', 'Passé Composé', 'ils ont résolu'),
    ('resoudre', 'elles', 'Passé Composé', 'elles ont résolu'),
    ('absoudre', 'je', 'Passé Composé', 'j''ai absous'),
    ('absoudre', 'tu', 'Passé Composé', 'tu as absous'),
    ('absoudre', 'il', 'Passé Composé', 'il a absous'),
    ('absoudre', 'elle', 'Passé Composé', 'elle a absous'),
    ('absoudre', 'on', 'Passé Composé', 'on a absous'),
    ('absoudre', 'nous', 'Passé Composé', 'nous avons absous'),
    ('absoudre', 'vous', 'Passé Composé', 'vous avez absous'),
    ('absoudre', 'ils', 'Passé Composé', 'ils ont absous'),
    ('absoudre', 'elles', 'Passé Composé', 'elles ont absous'),
    ('se lever', 'je', 'Passé Composé', 'je me suis levé'),
    ('se lever', 'tu', 'Passé Composé', 'tu t’es levé'),
    ('se lever', 'il', 'Passé Composé', 'il s’est levé'),
    ('se lever', 'elle', 'Passé Composé', 'elle s’est levée'),
    ('se lever', 'on', 'Passé Composé', 'on s’est levé'),
    ('se lever', 'nous', 'Passé Composé', 'nous nous sommes levés'),
    ('se lever', 'vous', 'Passé Composé', 'vous vous êtes levés'),
    ('se lever', 'ils', 'Passé Composé', 'ils se sont levés'),
    ('se lever', 'elles', 'Passé Composé', 'elles se sont levées'),
    ('se coucher', 'je', 'Passé Composé', 'je me suis couché'),
    ('se coucher', 'tu', 'Passé Composé', 'tu t’es couché'),
    ('se coucher', 'il', 'Passé Composé', 'il s’est couché'),
    ('se coucher', 'elle', 'Passé Composé', 'elle s’est couchée'),
    ('se coucher', 'on', 'Passé Composé', 'on s’est couché'),
    ('se coucher', 'nous', 'Passé Composé', 'nous nous sommes couchés'),
    ('se coucher', 'vous', 'Passé Composé', 'vous vous êtes couchés'),
    ('se coucher', 'ils', 'Passé Composé', 'ils se sont couchés'),
    ('se coucher', 'elles', 'Passé Composé', 'elles se sont couchées'),
    ('s’habiller', 'je', 'Passé Composé', 'je me suis habillé'),
    ('s’habiller', 'tu', 'Passé Composé', 'tu t’es habillé'),
    ('s’habiller', 'il', 'Passé Composé', 'il s’est habillé'),
    ('s’habiller', 'elle', 'Passé Composé', 'elle s’est habillée'),
    ('s’habiller', 'on', 'Passé Composé', 'on s’est habillé'),
    ('s’habiller', 'nous', 'Passé Composé', 'nous nous sommes habillés'),
    ('s’habiller', 'vous', 'Passé Composé', 'vous vous êtes habillés'),
    ('s’habiller', 'ils', 'Passé Composé', 'ils se sont habillés'),
    ('s’habiller', 'elles', 'Passé Composé', 'elles se sont habillées'),
    ('se laver', 'je', 'Passé Composé', 'je me suis lavé'),
    ('se laver', 'tu', 'Passé Composé', 'tu t’es lavé'),
    ('se laver', 'il', 'Passé Composé', 'il s’est lavé'),
    ('se laver', 'elle', 'Passé Composé', 'elle s’est lavée'),
    ('se laver', 'on', 'Passé Composé', 'on s’est lavé'),
    ('se laver', 'nous', 'Passé Composé', 'nous nous sommes lavés'),
    ('se laver', 'vous', 'Passé Composé', 'vous vous êtes lavés'),
    ('se laver', 'ils', 'Passé Composé', 'ils se sont lavés'),
    ('se laver', 'elles', 'Passé Composé', 'elles se sont lavées'),
    ('se brosser', 'je', 'Passé Composé', 'je me suis brossé'),
    ('se brosser', 'tu', 'Passé Composé', 'tu t’es brossé'),
    ('se brosser', 'il', 'Passé Composé', 'il s’est brossé'),
    ('se brosser', 'elle', 'Passé Composé', 'elle s’est brossée'),
    ('se brosser', 'on', 'Passé Composé', 'on s’est brossé'),
    ('se brosser', 'nous', 'Passé Composé', 'nous nous sommes brossés'),
    ('se brosser', 'vous', 'Passé Composé', 'vous vous êtes brossés'),
    ('se brosser', 'ils', 'Passé Composé', 'ils se sont brossés'),
    ('se brosser', 'elles', 'Passé Composé', 'elles se sont brossées'),
    ('se réveiller', 'je', 'Passé Composé', 'je me suis réveillé'),
    ('se réveiller', 'tu', 'Passé Composé', 'tu t’es réveillé'),
    ('se réveiller', 'il', 'Passé Composé', 'il s’est réveillé'),
    ('se réveiller', 'elle', 'Passé Composé', 'elle s’est réveillée'),
    ('se réveiller', 'on', 'Passé Composé', 'on s’est réveillé'),
    ('se réveiller', 'nous', 'Passé Composé', 'nous nous sommes réveillés'),
    ('se réveiller', 'vous', 'Passé Composé', 'vous vous êtes réveillés'),
    ('se réveiller', 'ils', 'Passé Composé', 'ils se sont réveillés'),
    ('se réveiller', 'elles', 'Passé Composé', 'elles se sont réveillées'),
    ('se reposer', 'je', 'Passé Composé', 'je me suis reposé'),
    ('se reposer', 'tu', 'Passé Composé', 'tu t’es reposé'),
    ('se reposer', 'il', 'Passé Composé', 'il s’est reposé'),
    ('se reposer', 'elle', 'Passé Composé', 'elle s’est reposée'),
    ('se reposer', 'on', 'Passé Composé', 'on s’est reposé'),
    ('se reposer', 'nous', 'Passé Composé', 'nous nous sommes reposés'),
    ('se reposer', 'vous', 'Passé Composé', 'vous vous êtes reposés'),
    ('se reposer', 'ils', 'Passé Composé', 'ils se sont reposés'),
    ('se reposer', 'elles', 'Passé Composé', 'elles se sont reposées'),
    ('se dépêcher', 'je', 'Passé Composé', 'je me suis dépêché'),
    ('se dépêcher', 'tu', 'Passé Composé', 'tu t’es dépêché'),
    ('se dépêcher', 'il', 'Passé Composé', 'il s’est dépêché'),
    ('se dépêcher', 'elle', 'Passé Composé', 'elle s’est dépêchée'),
    ('se dépêcher', 'on', 'Passé Composé', 'on s’est dépêché'),
    ('se dépêcher', 'nous', 'Passé Composé', 'nous nous sommes dépêchés'),
    ('se dépêcher', 'vous', 'Passé Composé', 'vous vous êtes dépêchés'),
    ('se dépêcher', 'ils', 'Passé Composé', 'ils se sont dépêchés'),
    ('se dépêcher', 'elles', 'Passé Composé', 'elles se sont dépêchées'),
    ('se souvenir', 'je', 'Passé Composé', 'je me suis souvenu'),
    ('se souvenir', 'tu', 'Passé Composé', 'tu t’es souvenu'),
    ('se souvenir', 'il', 'Passé Composé', 'il s’est souvenu'),
    ('se souvenir', 'elle', 'Passé Composé', 'elle s’est souvenue'),
    ('se souvenir', 'on', 'Passé Composé', 'on s’est souvenu'),
    ('se souvenir', 'nous', 'Passé Composé', 'nous nous sommes souvenus'),
    ('se souvenir', 'vous', 'Passé Composé', 'vous vous êtes souvenus'),
    ('se souvenir', 'ils', 'Passé Composé', 'ils se sont souvenus'),
    ('se souvenir', 'elles', 'Passé Composé', 'elles se sont souvenues'),
    ('se rendre compte', 'je', 'Passé Composé', 'je me suis rendu compte'),
    ('se rendre compte', 'tu', 'Passé Composé', 'tu t’es rendu compte'),
    ('se rendre compte', 'il', 'Passé Composé', 'il s’est rendu compte'),
    ('se rendre compte', 'elle', 'Passé Composé', 'elle s’est rendue compte'),
    ('se rendre compte', 'on', 'Passé Composé', 'on s’est rendu compte'),
    ('se rendre compte', 'nous', 'Passé Composé', 'nous nous sommes rendus compte'),
    ('se rendre compte', 'vous', 'Passé Composé', 'vous vous êtes rendus compte'),
    ('se rendre compte', 'ils', 'Passé Composé', 'ils se sont rendus compte'),
    ('se rendre compte', 'elles', 'Passé Composé', 'elles se sont rendues compte'),
    ('s’intéresser', 'je', 'Passé Composé', 'je me suis intéressé'),
    ('s’intéresser', 'tu', 'Passé Composé', 'tu t’es intéressé'),
    ('s’intéresser', 'il', 'Passé Composé', 'il s’est intéressé'),
    ('s’intéresser', 'elle', 'Passé Composé', 'elle s’est intéressée'),
    ('s’intéresser', 'on', 'Passé Composé', 'on s’est intéressé'),
    ('s’intéresser', 'nous', 'Passé Composé', 'nous nous sommes intéressés'),
    ('s’intéresser', 'vous', 'Passé Composé', 'vous vous êtes intéressés'),
    ('s’intéresser', 'ils', 'Passé Composé', 'ils se sont intéressés'),
    ('s’intéresser', 'elles', 'Passé Composé', 'elles se sont intéressées'),
    ('s’ennuyer', 'je', 'Passé Composé', 'je me suis ennuyé'),
    ('s’ennuyer', 'tu', 'Passé Composé', 'tu t’es ennuyé'),
    ('s’ennuyer', 'il', 'Passé Composé', 'il s’est ennuyé'),
    ('s’ennuyer', 'elle', 'Passé Composé', 'elle s’est ennuyée'),
    ('s’ennuyer', 'on', 'Passé Composé', 'on s’est ennuyé'),
    ('s’ennuyer', 'nous', 'Passé Composé', 'nous nous sommes ennuyés'),
    ('s’ennuyer', 'vous', 'Passé Composé', 'vous vous êtes ennuyés'),
    ('s’ennuyer', 'ils', 'Passé Composé', 'ils se sont ennuyés'),
    ('s’ennuyer', 'elles', 'Passé Composé', 'elles se sont ennuyées'),
    ('se fâcher', 'je', 'Passé Composé', 'je me suis fâché'),
    ('se fâcher', 'tu', 'Passé Composé', 'tu t’es fâché'),
    ('se fâcher', 'il', 'Passé Composé', 'il s’est fâché'),
    ('se fâcher', 'elle', 'Passé Composé', 'elle s’est fâchée'),
    ('se fâcher', 'on', 'Passé Composé', 'on s’est fâché'),
    ('se fâcher', 'nous', 'Passé Composé', 'nous nous sommes fâchés'),
    ('se fâcher', 'vous', 'Passé Composé', 'vous vous êtes fâchés'),
    ('se fâcher', 'ils', 'Passé Composé', 'ils se sont fâchés'),
    ('se fâcher', 'elles', 'Passé Composé', 'elles se sont fâchées'),
    ('se tromper', 'je', 'Passé Composé', 'je me suis trompé'),
    ('se tromper', 'tu', 'Passé Composé', 'tu t’es trompé'),
    ('se tromper', 'il', 'Passé Composé', 'il s’est trompé'),
    ('se tromper', 'elle', 'Passé Composé', 'elle s’est trompée'),
    ('se tromper', 'on', 'Passé Composé', 'on s’est trompé'),
    ('se tromper', 'nous', 'Passé Composé', 'nous nous sommes trompés'),
    ('se tromper', 'vous', 'Passé Composé', 'vous vous êtes trompés'),
    ('se tromper', 'ils', 'Passé Composé', 'ils se sont trompés'),
    ('se tromper', 'elles', 'Passé Composé', 'elles se sont trompées'),
    ('se taire', 'je', 'Passé Composé', 'je me suis tu'),
    ('se taire', 'tu', 'Passé Composé', 'tu t’es tu'),
    ('se taire', 'il', 'Passé Composé', 'il s’est tu'),
    ('se taire', 'elle', 'Passé Composé', 'elle s’est tue'),
    ('se taire', 'on', 'Passé Composé', 'on s’est tu'),
    ('se taire', 'nous', 'Passé Composé', 'nous nous sommes tus'),
    ('se taire', 'vous', 'Passé Composé', 'vous vous êtes tus'),
    ('se taire', 'ils', 'Passé Composé', 'ils se sont tus'),
    ('se taire', 'elles', 'Passé Composé', 'elles se sont tues'),
    ('s’asseoir', 'je', 'Passé Composé', 'je me suis assis'),
    ('s’asseoir', 'tu', 'Passé Composé', 'tu t’es assis'),
    ('s’asseoir', 'il', 'Passé Composé', 'il s’est assis'),
    ('s’asseoir', 'elle', 'Passé Composé', 'elle s’est assise'),
    ('s’asseoir', 'on', 'Passé Composé', 'on s’est assis'),
    ('s’asseoir', 'nous', 'Passé Composé', 'nous nous sommes assis'),
    ('s’asseoir', 'vous', 'Passé Composé', 'vous vous êtes assis'),
    ('s’asseoir', 'ils', 'Passé Composé', 'ils se sont assis'),
    ('s’asseoir', 'elles', 'Passé Composé', 'elles se sont assises'),
    ('s’entendre', 'je', 'Passé Composé', 'je me suis entendu'),
    ('s’entendre', 'tu', 'Passé Composé', 'tu t’es entendu'),
    ('s’entendre', 'il', 'Passé Composé', 'il s’est entendu'),
    ('s’entendre', 'elle', 'Passé Composé', 'elle s’est entendue'),
    ('s’entendre', 'on', 'Passé Composé', 'on s’est entendu'),
    ('s’entendre', 'nous', 'Passé Composé', 'nous nous sommes entendus'),
    ('s’entendre', 'vous', 'Passé Composé', 'vous vous êtes entendus'),
    ('s’entendre', 'ils', 'Passé Composé', 'ils se sont entendus'),
    ('s’entendre', 'elles', 'Passé Composé', 'elles se sont entendues'),
    ('se disputer', 'je', 'Passé Composé', 'je me suis disputé'),
    ('se disputer', 'tu', 'Passé Composé', 'tu t’es disputé'),
    ('se disputer', 'il', 'Passé Composé', 'il s’est disputé'),
    ('se disputer', 'elle', 'Passé Composé', 'elle s’est disputée'),
    ('se disputer', 'on', 'Passé Composé', 'on s’est disputé'),
    ('se disputer', 'nous', 'Passé Composé', 'nous nous sommes disputés'),
    ('se disputer', 'vous', 'Passé Composé', 'vous vous êtes disputés'),
    ('se disputer', 'ils', 'Passé Composé', 'ils se sont disputés'),
    ('se disputer', 'elles', 'Passé Composé', 'elles se sont disputées'),
    ('se marier', 'je', 'Passé Composé', 'je me suis marié'),
    ('se marier', 'tu', 'Passé Composé', 'tu t’es marié'),
    ('se marier', 'il', 'Passé Composé', 'il s’est marié'),
    ('se marier', 'elle', 'Passé Composé', 'elle s’est mariée'),
    ('se marier', 'on', 'Passé Composé', 'on s’est marié'),
    ('se marier', 'nous', 'Passé Composé', 'nous nous sommes mariés'),
    ('se marier', 'vous', 'Passé Composé', 'vous vous êtes mariés'),
    ('se marier', 'ils', 'Passé Composé', 'ils se sont mariés'),
    ('se marier', 'elles', 'Passé Composé', 'elles se sont mariées'),
    ('se divorcer', 'je', 'Passé Composé', 'je me suis divorcé'),
    ('se divorcer', 'tu', 'Passé Composé', 'tu t’es divorcé'),
    ('se divorcer', 'il', 'Passé Composé', 'il s’est divorcé'),
    ('se divorcer', 'elle', 'Passé Composé', 'elle s’est divorcée'),
    ('se divorcer', 'on', 'Passé Composé', 'on s’est divorcé'),
    ('se divorcer', 'nous', 'Passé Composé', 'nous nous sommes divorcés'),
    ('se divorcer', 'vous', 'Passé Composé', 'vous vous êtes divorcés'),
    ('se divorcer', 'ils', 'Passé Composé', 'ils se sont divorcés'),
    ('se divorcer', 'elles', 'Passé Composé', 'elles se sont divorcées'),
    ('se battre', 'je', 'Passé Composé', 'je me suis battu'),
    ('se battre', 'tu', 'Passé Composé', 'tu t’es battu'),
    ('se battre', 'il', 'Passé Composé', 'il s’est battu'),
    ('se battre', 'elle', 'Passé Composé', 'elle s’est battue'),
    ('se battre', 'on', 'Passé Composé', 'on s’est battu'),
    ('se battre', 'nous', 'Passé Composé', 'nous nous sommes battus'),
    ('se battre', 'vous', 'Passé Composé', 'vous vous êtes battus'),
    ('se battre', 'ils', 'Passé Composé', 'ils se sont battus'),
    ('se battre', 'elles', 'Passé Composé', 'elles se sont battues'),
    ('s’en aller', 'je', 'Passé Composé', 'je me suis en allé'),
    ('s’en aller', 'tu', 'Passé Composé', 'tu t’es en allé'),
    ('s’en aller', 'il', 'Passé Composé', 'il s’est en allé'),
    ('s’en aller', 'elle', 'Passé Composé', 'elle s’est en allée'),
    ('s’en aller', 'on', 'Passé Composé', 'on s’est en allé'),
    ('s’en aller', 'nous', 'Passé Composé', 'nous nous sommes en allés'),
    ('s’en aller', 'vous', 'Passé Composé', 'vous vous êtes en allés'),
    ('s’en aller', 'ils', 'Passé Composé', 'ils se sont en allés'),
    ('s’en aller', 'elles', 'Passé Composé', 'elles se sont en allées'),
    ('se rendre', 'je', 'Passé Composé', 'je me suis rendu'),
    ('se rendre', 'tu', 'Passé Composé', 'tu t’es rendu'),
    ('se rendre', 'il', 'Passé Composé', 'il s’est rendu'),
    ('se rendre', 'elle', 'Passé Composé', 'elle s’est rendue'),
    ('se rendre', 'on', 'Passé Composé', 'on s’est rendu'),
    ('se rendre', 'nous', 'Passé Composé', 'nous nous sommes rendus'),
    ('se rendre', 'vous', 'Passé Composé', 'vous vous êtes rendus'),
    ('se rendre', 'ils', 'Passé Composé', 'ils se sont rendus'),
    ('se rendre', 'elles', 'Passé Composé', 'elles se sont rendues'),
    ('se servir', 'je', 'Passé Composé', 'je me suis servi'),
    ('se servir', 'tu', 'Passé Composé', 'tu t’es servi'),
    ('se servir', 'il', 'Passé Composé', 'il s’est servi'),
    ('se servir', 'elle', 'Passé Composé', 'elle s’est servie'),
    ('se servir', 'on', 'Passé Composé', 'on s’est servi'),
    ('se servir', 'nous', 'Passé Composé', 'nous nous sommes servis'),
    ('se servir', 'vous', 'Passé Composé', 'vous vous êtes servis'),
    ('se servir', 'ils', 'Passé Composé', 'ils se sont servis'),
    ('se servir', 'elles', 'Passé Composé', 'elles se sont servies'),
    ('s’apercevoir', 'je', 'Passé Composé', 'je me suis aperçu'),
    ('s’apercevoir', 'tu', 'Passé Composé', 'tu t’es aperçu'),
    ('s’apercevoir', 'il', 'Passé Composé', 'il s’est aperçu'),
    ('s’apercevoir', 'elle', 'Passé Composé', 'elle s’est aperçue'),
    ('s’apercevoir', 'on', 'Passé Composé', 'on s’est aperçu'),
    ('s’apercevoir', 'nous', 'Passé Composé', 'nous nous sommes aperçus'),
    ('s’apercevoir', 'vous', 'Passé Composé', 'vous vous êtes aperçus'),
    ('s’apercevoir', 'ils', 'Passé Composé', 'ils se sont aperçus'),
    ('s’apercevoir', 'elles', 'Passé Composé', 'elles se sont aperçues'),
    ('se douter', 'je', 'Passé Composé', 'je me suis douté'),
    ('se douter', 'tu', 'Passé Composé', 'tu t’es douté'),
    ('se douter', 'il', 'Passé Composé', 'il s’est douté'),
    ('se douter', 'elle', 'Passé Composé', 'elle s’est doutée'),
    ('se douter', 'on', 'Passé Composé', 'on s’est douté'),
    ('se douter', 'nous', 'Passé Composé', 'nous nous sommes doutés'),
    ('se douter', 'vous', 'Passé Composé', 'vous vous êtes doutés'),
    ('se douter', 'ils', 'Passé Composé', 'ils se sont doutés'),
    ('se douter', 'elles', 'Passé Composé', 'elles se sont doutées'),
    ('se passer', 'je', 'Passé Composé', 'je me suis passé'),
    ('se passer', 'tu', 'Passé Composé', 'tu t’es passé'),
    ('se passer', 'il', 'Passé Composé', 'il s’est passé'),
    ('se passer', 'elle', 'Passé Composé', 'elle s’est passée'),
    ('se passer', 'on', 'Passé Composé', 'on s’est passé'),
    ('se passer', 'nous', 'Passé Composé', 'nous nous sommes passés'),
    ('se passer', 'vous', 'Passé Composé', 'vous vous êtes passés'),
    ('se passer', 'ils', 'Passé Composé', 'ils se sont passés'),
    ('se passer', 'elles', 'Passé Composé', 'elles se sont passées'),
    ('se trouver', 'je', 'Passé Composé', 'je me suis trouvé'),
    ('se trouver', 'tu', 'Passé Composé', 'tu t’es trouvé'),
    ('se trouver', 'il', 'Passé Composé', 'il s’est trouvé'),
    ('se trouver', 'elle', 'Passé Composé', 'elle s’est trouvée'),
    ('se trouver', 'on', 'Passé Composé', 'on s’est trouvé'),
    ('se trouver', 'nous', 'Passé Composé', 'nous nous sommes trouvés'),
    ('se trouver', 'vous', 'Passé Composé', 'vous vous êtes trouvés'),
    ('se trouver', 'ils', 'Passé Composé', 'ils se sont trouvés'),
    ('se trouver', 'elles', 'Passé Composé', 'elles se sont trouvées'),
    ('se mettre', 'je', 'Passé Composé', 'je me suis mis'),
    ('se mettre', 'tu', 'Passé Composé', 'tu t’es mis'),
    ('se mettre', 'il', 'Passé Composé', 'il s’est mis'),
    ('se mettre', 'elle', 'Passé Composé', 'elle s’est mise'),
    ('se mettre', 'on', 'Passé Composé', 'on s’est mis'),
    ('se mettre', 'nous', 'Passé Composé', 'nous nous sommes mis'),
    ('se mettre', 'vous', 'Passé Composé', 'vous vous êtes mis'),
    ('se mettre', 'ils', 'Passé Composé', 'ils se sont mis'),
    ('se mettre', 'elles', 'Passé Composé', 'elles se sont mises'),
    ('se faire', 'je', 'Passé Composé', 'je me suis fait'),
    ('se faire', 'tu', 'Passé Composé', 'tu t’es fait'),
    ('se faire', 'il', 'Passé Composé', 'il s’est fait'),
    ('se faire', 'elle', 'Passé Composé', 'elle s’est faite'),
    ('se faire', 'on', 'Passé Composé', 'on s’est fait'),
    ('se faire', 'nous', 'Passé Composé', 'nous nous sommes faits'),
    ('se faire', 'vous', 'Passé Composé', 'vous vous êtes faits'),
    ('se faire', 'ils', 'Passé Composé', 'ils se sont faits'),
    ('se faire', 'elles', 'Passé Composé', 'elles se sont faites'),
    ('se demander', 'je', 'Passé Composé', 'je me suis demandé'),
    ('se demander', 'tu', 'Passé Composé', 'tu t’es demandé'),
    ('se demander', 'il', 'Passé Composé', 'il s’est demandé'),
    ('se demander', 'elle', 'Passé Composé', 'elle s’est demandée'),
    ('se demander', 'on', 'Passé Composé', 'on s’est demandé'),
    ('se demander', 'nous', 'Passé Composé', 'nous nous sommes demandés'),
    ('se demander', 'vous', 'Passé Composé', 'vous vous êtes demandés'),
    ('se demander', 'ils', 'Passé Composé', 'ils se sont demandés'),
    ('se demander', 'elles', 'Passé Composé', 'elles se sont demandées'),
    ('se plaindre', 'je', 'Passé Composé', 'je me suis plaint'),
    ('se plaindre', 'tu', 'Passé Composé', 'tu t’es plaint'),
    ('se plaindre', 'il', 'Passé Composé', 'il s’est plaint'),
    ('se plaindre', 'elle', 'Passé Composé', 'elle s’est plainte'),
    ('se plaindre', 'on', 'Passé Composé', 'on s’est plaint'),
    ('se plaindre', 'nous', 'Passé Composé', 'nous nous sommes plaints'),
    ('se plaindre', 'vous', 'Passé Composé', 'vous vous êtes plaints'),
    ('se plaindre', 'ils', 'Passé Composé', 'ils se sont plaints'),
    ('se plaindre', 'elles', 'Passé Composé', 'elles se sont plaintes'),
    ('se voir', 'je', 'Passé Composé', 'je me suis vu'),
    ('se voir', 'tu', 'Passé Composé', 'tu t’es vu'),
    ('se voir', 'il', 'Passé Composé', 'il s’est vu'),
    ('se voir', 'elle', 'Passé Composé', 'elle s’est vue'),
    ('se voir', 'on', 'Passé Composé', 'on s’est vu'),
    ('se voir', 'nous', 'Passé Composé', 'nous nous sommes vus'),
    ('se voir', 'vous', 'Passé Composé', 'vous vous êtes vus'),
    ('se voir', 'ils', 'Passé Composé', 'ils se sont vus'),
    ('se voir', 'elles', 'Passé Composé', 'elles se sont vues'),
    ('s’imaginer', 'je', 'Passé Composé', 'je me suis imaginé'),
    ('s’imaginer', 'tu', 'Passé Composé', 'tu t’es imaginé'),
    ('s’imaginer', 'il', 'Passé Composé', 'il s’est imaginé'),
    ('s’imaginer', 'elle', 'Passé Composé', 'elle s’est imaginée'),
    ('s’imaginer', 'on', 'Passé Composé', 'on s’est imaginé'),
    ('s’imaginer', 'nous', 'Passé Composé', 'nous nous sommes imaginés'),
    ('s’imaginer', 'vous', 'Passé Composé', 'vous vous êtes imaginés'),
    ('s’imaginer', 'ils', 'Passé Composé', 'ils se sont imaginés'),
    ('s’imaginer', 'elles', 'Passé Composé', 'elles se sont imaginées'),
    ('s’efforcer', 'je', 'Passé Composé', 'je me suis efforcé'),
    ('s’efforcer', 'tu', 'Passé Composé', 'tu t’es efforcé'),
    ('s’efforcer', 'il', 'Passé Composé', 'il s’est efforcé'),
    ('s’efforcer', 'elle', 'Passé Composé', 'elle s’est efforcée'),
    ('s’efforcer', 'on', 'Passé Composé', 'on s’est efforcé'),
    ('s’efforcer', 'nous', 'Passé Composé', 'nous nous sommes efforcés'),
    ('s’efforcer', 'vous', 'Passé Composé', 'vous vous êtes efforcés'),
    ('s’efforcer', 'ils', 'Passé Composé', 'ils se sont efforcés'),
    ('s’efforcer', 'elles', 'Passé Composé', 'elles se sont efforcées'),
    ('s’évanouir', 'je', 'Passé Composé', 'je me suis évanoui'),
    ('s’évanouir', 'tu', 'Passé Composé', 'tu t’es évanoui'),
    ('s’évanouir', 'il', 'Passé Composé', 'il s’est évanoui'),
    ('s’évanouir', 'elle', 'Passé Composé', 'elle s’est évanouie'),
    ('s’évanouir', 'on', 'Passé Composé', 'on s’est évanoui'),
    ('s’évanouir', 'nous', 'Passé Composé', 'nous nous sommes évanouis'),
    ('s’évanouir', 'vous', 'Passé Composé', 'vous vous êtes évanouis'),
    ('s’évanouir', 'ils', 'Passé Composé', 'ils se sont évanouis'),
    ('s’évanouir', 'elles', 'Passé Composé', 'elles se sont évanouies'),
    ('s’indigner', 'je', 'Passé Composé', 'je me suis indigné'),
    ('s’indigner', 'tu', 'Passé Composé', 'tu t’es indigné'),
    ('s’indigner', 'il', 'Passé Composé', 'il s’est indigné'),
    ('s’indigner', 'elle', 'Passé Composé', 'elle s’est indignée'),
    ('s’indigner', 'on', 'Passé Composé', 'on s’est indigné'),
    ('s’indigner', 'nous', 'Passé Composé', 'nous nous sommes indignés'),
    ('s’indigner', 'vous', 'Passé Composé', 'vous vous êtes indignés'),
    ('s’indigner', 'ils', 'Passé Composé', 'ils se sont indignés'),
    ('s’indigner', 'elles', 'Passé Composé', 'elles se sont indignées'),
    ('s’épanouir', 'je', 'Passé Composé', 'je me suis épanoui'),
    ('s’épanouir', 'tu', 'Passé Composé', 'tu t’es épanoui'),
    ('s’épanouir', 'il', 'Passé Composé', 'il s’est épanoui'),
    ('s’épanouir', 'elle', 'Passé Composé', 'elle s’est épanouie'),
    ('s’épanouir', 'on', 'Passé Composé', 'on s’est épanoui'),
    ('s’épanouir', 'nous', 'Passé Composé', 'nous nous sommes épanouis'),
    ('s’épanouir', 'vous', 'Passé Composé', 'vous vous êtes épanouis'),
    ('s’épanouir', 'ils', 'Passé Composé', 'ils se sont épanouis'),
    ('s’épanouir', 'elles', 'Passé Composé', 'elles se sont épanouies'),
    ('s’en sortir', 'je', 'Passé Composé', 'je m’en suis sorti'),
    ('s’en sortir', 'tu', 'Passé Composé', 'tu t’en es sorti'),
    ('s’en sortir', 'il', 'Passé Composé', 'il s’en est sorti'),
    ('s’en sortir', 'elle', 'Passé Composé', 'elle s’en est sortie'),
    ('s’en sortir', 'on', 'Passé Composé', 'on s’en est sorti'),
    ('s’en sortir', 'nous', 'Passé Composé', 'nous nous en sommes sortis'),
    ('s’en sortir', 'vous', 'Passé Composé', 'vous vous en êtes sortis'),
    ('s’en sortir', 'ils', 'Passé Composé', 'ils s’en sont sortis'),
    ('s’en sortir', 'elles', 'Passé Composé', 'elles s’en sont sorties'),
    ('s’attendre', 'je', 'Passé Composé', 'je me suis attendu'),
    ('s’attendre', 'tu', 'Passé Composé', 'tu t’es attendu'),
    ('s’attendre', 'il', 'Passé Composé', 'il s’est attendu'),
    ('s’attendre', 'elle', 'Passé Composé', 'elle s’est attendue'),
    ('s’attendre', 'on', 'Passé Composé', 'on s’est attendu'),
    ('s’attendre', 'nous', 'Passé Composé', 'nous nous sommes attendus'),
    ('s’attendre', 'vous', 'Passé Composé', 'vous vous êtes attendus'),
    ('s’attendre', 'ils', 'Passé Composé', 'ils se sont attendus'),
    ('s’attendre', 'elles', 'Passé Composé', 'elles se sont attendues'),
    ('s’interroger', 'je', 'Passé Composé', 'je me suis interrogé'),
    ('s’interroger', 'tu', 'Passé Composé', 'tu t’es interrogé'),
    ('s’interroger', 'il', 'Passé Composé', 'il s’est interrogé'),
    ('s’interroger', 'elle', 'Passé Composé', 'elle s’est interrogée'),
    ('s’interroger', 'on', 'Passé Composé', 'on s’est interrogé'),
    ('s’interroger', 'nous', 'Passé Composé', 'nous nous sommes interrogés'),
    ('s’interroger', 'vous', 'Passé Composé', 'vous vous êtes interrogés'),
    ('s’interroger', 'ils', 'Passé Composé', 'ils se sont interrogés'),
    ('s’interroger', 'elles', 'Passé Composé', 'elles se sont interrogées'),
    ('se heurter', 'je', 'Passé Composé', 'je me suis heurté'),
    ('se heurter', 'tu', 'Passé Composé', 'tu t’es heurté'),
    ('se heurter', 'il', 'Passé Composé', 'il s’est heurté'),
    ('se heurter', 'elle', 'Passé Composé', 'elle s’est heurtée'),
    ('se heurter', 'on', 'Passé Composé', 'on s’est heurté'),
    ('se heurter', 'nous', 'Passé Composé', 'nous nous sommes heurtés'),
    ('se heurter', 'vous', 'Passé Composé', 'vous vous êtes heurtés'),
    ('se heurter', 'ils', 'Passé Composé', 'ils se sont heurtés'),
    ('se heurter', 'elles', 'Passé Composé', 'elles se sont heurtées'),
    ('se méfier', 'je', 'Passé Composé', 'je me suis méfié'),
    ('se méfier', 'tu', 'Passé Composé', 'tu t’es méfié'),
    ('se méfier', 'il', 'Passé Composé', 'il s’est méfié'),
    ('se méfier', 'elle', 'Passé Composé', 'elle s’est méfiée'),
    ('se méfier', 'on', 'Passé Composé', 'on s’est méfié'),
    ('se méfier', 'nous', 'Passé Composé', 'nous nous sommes méfiés'),
    ('se méfier', 'vous', 'Passé Composé', 'vous vous êtes méfiés'),
    ('se méfier', 'ils', 'Passé Composé', 'ils se sont méfiés'),
    ('se méfier', 'elles', 'Passé Composé', 'elles se sont méfiées'),
    ('se replier sur soi-même', 'je', 'Passé Composé', 'je me suis replié sur moi-même'),
    ('se replier sur soi-même', 'tu', 'Passé Composé', 'tu t’es replié sur toi-même'),
    ('se replier sur soi-même', 'il', 'Passé Composé', 'il s’est replié sur lui-même'),
    ('se replier sur soi-même', 'elle', 'Passé Composé', 'elle s’est repliée sur elle-même'),
    ('se replier sur soi-même', 'on', 'Passé Composé', 'on s’est replié sur soi-même'),
    ('se replier sur soi-même', 'nous', 'Passé Composé', 'nous nous sommes repliés sur nous-mêmes'),
    ('se replier sur soi-même', 'vous', 'Passé Composé', 'vous vous êtes repliés sur vous-mêmes'),
    ('se replier sur soi-même', 'ils', 'Passé Composé', 'ils se sont repliés sur eux-mêmes'),
    ('se replier sur soi-même', 'elles', 'Passé Composé', 'elles se sont repliées sur elles-mêmes'),
    ('se raviser', 'je', 'Passé Composé', 'je me suis ravisé'),
    ('se raviser', 'tu', 'Passé Composé', 'tu t’es ravisé'),
    ('se raviser', 'il', 'Passé Composé', 'il s’est ravisé'),
    ('se raviser', 'elle', 'Passé Composé', 'elle s’est ravisée'),
    ('se raviser', 'on', 'Passé Composé', 'on s’est ravisé'),
    ('se raviser', 'nous', 'Passé Composé', 'nous nous sommes ravisés'),
    ('se raviser', 'vous', 'Passé Composé', 'vous vous êtes ravisés'),
    ('se raviser', 'ils', 'Passé Composé', 'ils se sont ravisés'),
    ('se raviser', 'elles', 'Passé Composé', 'elles se sont ravisées'),
    ('se débrouiller', 'je', 'Passé Composé', 'je me suis débrouillé'),
    ('se débrouiller', 'tu', 'Passé Composé', 'tu t’es débrouillé'),
    ('se débrouiller', 'il', 'Passé Composé', 'il s’est débrouillé'),
    ('se débrouiller', 'elle', 'Passé Composé', 'elle s’est débrouillée'),
    ('se débrouiller', 'on', 'Passé Composé', 'on s’est débrouillé'),
    ('se débrouiller', 'nous', 'Passé Composé', 'nous nous sommes débrouillés'),
    ('se débrouiller', 'vous', 'Passé Composé', 'vous vous êtes débrouillés'),
    ('se débrouiller', 'ils', 'Passé Composé', 'ils se sont débrouillés'),
    ('se débrouiller', 'elles', 'Passé Composé', 'elles se sont débrouillées'),
    ('se réconcilier', 'je', 'Passé Composé', 'je me suis réconcilié'),
    ('se réconcilier', 'tu', 'Passé Composé', 'tu t’es réconcilié'),
    ('se réconcilier', 'il', 'Passé Composé', 'il s’est réconcilié'),
    ('se réconcilier', 'elle', 'Passé Composé', 'elle s’est réconciliée'),
    ('se réconcilier', 'on', 'Passé Composé', 'on s’est réconcilié'),
    ('se réconcilier', 'nous', 'Passé Composé', 'nous nous sommes réconciliés'),
    ('se réconcilier', 'vous', 'Passé Composé', 'vous vous êtes réconciliés'),
    ('se réconcilier', 'ils', 'Passé Composé', 'ils se sont réconciliés'),
    ('se réconcilier', 'elles', 'Passé Composé', 'elles se sont réconciliées'),
    ('se précipiter', 'je', 'Passé Composé', 'je me suis précipité'),
    ('se précipiter', 'tu', 'Passé Composé', 'tu t’es précipité'),
    ('se précipiter', 'il', 'Passé Composé', 'il s’est précipité'),
    ('se précipiter', 'elle', 'Passé Composé', 'elle s’est précipitée'),
    ('se précipiter', 'on', 'Passé Composé', 'on s’est précipité'),
    ('se précipiter', 'nous', 'Passé Composé', 'nous nous sommes précipités'),
    ('se précipiter', 'vous', 'Passé Composé', 'vous vous êtes précipités'),
    ('se précipiter', 'ils', 'Passé Composé', 'ils se sont précipités'),
    ('se précipiter', 'elles', 'Passé Composé', 'elles se sont précipitées'),
    ('se figurer', 'je', 'Passé Composé', 'je me suis figuré'),
    ('se figurer', 'tu', 'Passé Composé', 'tu t’es figuré'),
    ('se figurer', 'il', 'Passé Composé', 'il s’est figuré'),
    ('se figurer', 'elle', 'Passé Composé', 'elle s’est figurée'),
    ('se figurer', 'on', 'Passé Composé', 'on s’est figuré'),
    ('se figurer', 'nous', 'Passé Composé', 'nous nous sommes figurés'),
    ('se figurer', 'vous', 'Passé Composé', 'vous vous êtes figurés'),
    ('se figurer', 'ils', 'Passé Composé', 'ils se sont figurés'),
    ('se figurer', 'elles', 'Passé Composé', 'elles se sont figurées'),
    ('acheter', 'je', 'Passé Composé', 'j''ai acheté'),
    ('acheter', 'tu', 'Passé Composé', 'tu as acheté'),
    ('acheter', 'il', 'Passé Composé', 'il a acheté'),
    ('acheter', 'elle', 'Passé Composé', 'elle a acheté'),
    ('acheter', 'on', 'Passé Composé', 'on a acheté'),
    ('acheter', 'nous', 'Passé Composé', 'nous avons acheté'),
    ('acheter', 'vous', 'Passé Composé', 'vous avez acheté'),
    ('acheter', 'ils', 'Passé Composé', 'ils ont acheté'),
    ('acheter', 'elles', 'Passé Composé', 'elles ont acheté'),
    ('aller', 'je', 'Passé Composé', 'je suis allé'),
    ('aller', 'tu', 'Passé Composé', 'tu es allé'),
    ('aller', 'il', 'Passé Composé', 'il est allé'),
    ('aller', 'elle', 'Passé Composé', 'elle est allée'),
    ('aller', 'on', 'Passé Composé', 'on est allé'),
    ('aller', 'nous', 'Passé Composé', 'nous sommes allés'),
    ('aller', 'vous', 'Passé Composé', 'vous êtes allés'),
    ('aller', 'ils', 'Passé Composé', 'ils sont allés'),
    ('aller', 'elles', 'Passé Composé', 'elles sont allées'),
    ('appeler', 'je', 'Passé Composé', 'j''ai appelé'),
    ('appeler', 'tu', 'Passé Composé', 'tu as appelé'),
    ('appeler', 'il', 'Passé Composé', 'il a appelé'),
    ('appeler', 'elle', 'Passé Composé', 'elle a appelé'),
    ('appeler', 'on', 'Passé Composé', 'on a appelé'),
    ('appeler', 'nous', 'Passé Composé', 'nous avons appelé'),
    ('appeler', 'vous', 'Passé Composé', 'vous avez appelé'),
    ('appeler', 'ils', 'Passé Composé', 'ils ont appelé'),
    ('appeler', 'elles', 'Passé Composé', 'elles ont appelé'),
    ('attendre', 'je', 'Passé Composé', 'j''ai attendu'),
    ('attendre', 'tu', 'Passé Composé', 'tu as attendu'),
    ('attendre', 'il', 'Passé Composé', 'il a attendu'),
    ('attendre', 'elle', 'Passé Composé', 'elle a attendu'),
    ('attendre', 'on', 'Passé Composé', 'on a attendu'),
    ('attendre', 'nous', 'Passé Composé', 'nous avons attendu'),
    ('attendre', 'vous', 'Passé Composé', 'vous avez attendu'),
    ('attendre', 'ils', 'Passé Composé', 'ils ont attendu'),
    ('attendre', 'elles', 'Passé Composé', 'elles ont attendu'),
    ('courir', 'je', 'Passé Composé', 'j''ai couru'),
    ('courir', 'tu', 'Passé Composé', 'tu as couru'),
    ('courir', 'il', 'Passé Composé', 'il a couru'),
    ('courir', 'elle', 'Passé Composé', 'elle a couru'),
    ('courir', 'on', 'Passé Composé', 'on a couru'),
    ('courir', 'nous', 'Passé Composé', 'nous avons couru'),
    ('courir', 'vous', 'Passé Composé', 'vous avez couru'),
    ('courir', 'ils', 'Passé Composé', 'ils ont couru'),
    ('courir', 'elles', 'Passé Composé', 'elles ont couru'),
    ('descendre', 'je', 'Passé Composé', 'je suis descendu'),
    ('descendre', 'tu', 'Passé Composé', 'tu es descendu'),
    ('descendre', 'il', 'Passé Composé', 'il est descendu'),
    ('descendre', 'elle', 'Passé Composé', 'elle est descendue'),
    ('descendre', 'on', 'Passé Composé', 'on est descendu'),
    ('descendre', 'nous', 'Passé Composé', 'nous sommes descendus'),
    ('descendre', 'vous', 'Passé Composé', 'vous êtes descendus'),
    ('descendre', 'ils', 'Passé Composé', 'ils sont descendus'),
    ('descendre', 'elles', 'Passé Composé', 'elles sont descendues'),
    ('dormir', 'je', 'Passé Composé', 'j''ai dormi'),
    ('dormir', 'tu', 'Passé Composé', 'tu as dormi'),
    ('dormir', 'il', 'Passé Composé', 'il a dormi'),
    ('dormir', 'elle', 'Passé Composé', 'elle a dormi'),
    ('dormir', 'on', 'Passé Composé', 'on a dormi'),
    ('dormir', 'nous', 'Passé Composé', 'nous avons dormi'),
    ('dormir', 'vous', 'Passé Composé', 'vous avez dormi'),
    ('dormir', 'ils', 'Passé Composé', 'ils ont dormi'),
    ('dormir', 'elles', 'Passé Composé', 'elles ont dormi'),
    ('entendre', 'je', 'Passé Composé', 'j''ai entendu'),
    ('entendre', 'tu', 'Passé Composé', 'tu as entendu'),
    ('entendre', 'il', 'Passé Composé', 'il a entendu'),
    ('entendre', 'elle', 'Passé Composé', 'elle a entendu'),
    ('entendre', 'on', 'Passé Composé', 'on a entendu'),
    ('entendre', 'nous', 'Passé Composé', 'nous avons entendu'),
    ('entendre', 'vous', 'Passé Composé', 'vous avez entendu'),
    ('entendre', 'ils', 'Passé Composé', 'ils ont entendu'),
    ('entendre', 'elles', 'Passé Composé', 'elles ont entendu'),
    ('envoyer', 'je', 'Passé Composé', 'j''ai envoyé'),
    ('envoyer', 'tu', 'Passé Composé', 'tu as envoyé'),
    ('envoyer', 'il', 'Passé Composé', 'il a envoyé'),
    ('envoyer', 'elle', 'Passé Composé', 'elle a envoyé'),
    ('envoyer', 'on', 'Passé Composé', 'on a envoyé'),
    ('envoyer', 'nous', 'Passé Composé', 'nous avons envoyé'),
    ('envoyer', 'vous', 'Passé Composé', 'vous avez envoyé'),
    ('envoyer', 'ils', 'Passé Composé', 'ils ont envoyé'),
    ('envoyer', 'elles', 'Passé Composé', 'elles ont envoyé'),
    ('jeter', 'je', 'Passé Composé', 'j''ai jeté'),
    ('jeter', 'tu', 'Passé Composé', 'tu as jeté'),
    ('jeter', 'il', 'Passé Composé', 'il a jeté'),
    ('jeter', 'elle', 'Passé Composé', 'elle a jeté'),
    ('jeter', 'on', 'Passé Composé', 'on a jeté'),
    ('jeter', 'nous', 'Passé Composé', 'nous avons jeté'),
    ('jeter', 'vous', 'Passé Composé', 'vous avez jeté'),
    ('jeter', 'ils', 'Passé Composé', 'ils ont jeté'),
    ('jeter', 'elles', 'Passé Composé', 'elles ont jeté'),
    ('partir', 'je', 'Passé Composé', 'je suis parti'),
    ('partir', 'tu', 'Passé Composé', 'tu es parti'),
    ('partir', 'il', 'Passé Composé', 'il est parti'),
    ('partir', 'elle', 'Passé Composé', 'elle est partie'),
    ('partir', 'on', 'Passé Composé', 'on est parti'),
    ('partir', 'nous', 'Passé Composé', 'nous sommes partis'),
    ('partir', 'vous', 'Passé Composé', 'vous êtes partis'),
    ('partir', 'ils', 'Passé Composé', 'ils sont partis'),
    ('partir', 'elles', 'Passé Composé', 'elles sont parties'),
    ('payer', 'je', 'Passé Composé', 'j''ai payé'),
    ('payer', 'tu', 'Passé Composé', 'tu as payé'),
    ('payer', 'il', 'Passé Composé', 'il a payé'),
    ('payer', 'elle', 'Passé Composé', 'elle a payé'),
    ('payer', 'on', 'Passé Composé', 'on a payé'),
    ('payer', 'nous', 'Passé Composé', 'nous avons payé'),
    ('payer', 'vous', 'Passé Composé', 'vous avez payé'),
    ('payer', 'ils', 'Passé Composé', 'ils ont payé'),
    ('payer', 'elles', 'Passé Composé', 'elles ont payé'),
    ('perdre', 'je', 'Passé Composé', 'j''ai perdu'),
    ('perdre', 'tu', 'Passé Composé', 'tu as perdu'),
    ('perdre', 'il', 'Passé Composé', 'il a perdu'),
    ('perdre', 'elle', 'Passé Composé', 'elle a perdu'),
    ('perdre', 'on', 'Passé Composé', 'on a perdu'),
    ('perdre', 'nous', 'Passé Composé', 'nous avons perdu'),
    ('perdre', 'vous', 'Passé Composé', 'vous avez perdu'),
    ('perdre', 'ils', 'Passé Composé', 'ils ont perdu'),
    ('perdre', 'elles', 'Passé Composé', 'elles ont perdu'),
    ('préférer', 'je', 'Passé Composé', 'j''ai préféré'),
    ('préférer', 'tu', 'Passé Composé', 'tu as préféré'),
    ('préférer', 'il', 'Passé Composé', 'il a préféré'),
    ('préférer', 'elle', 'Passé Composé', 'elle a préféré'),
    ('préférer', 'on', 'Passé Composé', 'on a préféré'),
    ('préférer', 'nous', 'Passé Composé', 'nous avons préféré'),
    ('préférer', 'vous', 'Passé Composé', 'vous avez préféré'),
    ('préférer', 'ils', 'Passé Composé', 'ils ont préféré'),
    ('préférer', 'elles', 'Passé Composé', 'elles ont préféré'),
    ('répondre', 'je', 'Passé Composé', 'j''ai répondu'),
    ('répondre', 'tu', 'Passé Composé', 'tu as répondu'),
    ('répondre', 'il', 'Passé Composé', 'il a répondu'),
    ('répondre', 'elle', 'Passé Composé', 'elle a répondu'),
    ('répondre', 'on', 'Passé Composé', 'on a répondu'),
    ('répondre', 'nous', 'Passé Composé', 'nous avons répondu'),
    ('répondre', 'vous', 'Passé Composé', 'vous avez répondu'),
    ('répondre', 'ils', 'Passé Composé', 'ils ont répondu'),
    ('répondre', 'elles', 'Passé Composé', 'elles ont répondu'),
    ('servir', 'je', 'Passé Composé', 'j''ai servi'),
    ('servir', 'tu', 'Passé Composé', 'tu as servi'),
    ('servir', 'il', 'Passé Composé', 'il a servi'),
    ('servir', 'elle', 'Passé Composé', 'elle a servi'),
    ('servir', 'on', 'Passé Composé', 'on a servi'),
    ('servir', 'nous', 'Passé Composé', 'nous avons servi'),
    ('servir', 'vous', 'Passé Composé', 'vous avez servi'),
    ('servir', 'ils', 'Passé Composé', 'ils ont servi'),
    ('servir', 'elles', 'Passé Composé', 'elles ont servi'),
    ('sortir', 'je', 'Passé Composé', 'je suis sorti'),
    ('sortir', 'tu', 'Passé Composé', 'tu es sorti'),
    ('sortir', 'il', 'Passé Composé', 'il est sorti'),
    ('sortir', 'elle', 'Passé Composé', 'elle est sortie'),
    ('sortir', 'on', 'Passé Composé', 'on est sorti'),
    ('sortir', 'nous', 'Passé Composé', 'nous sommes sortis'),
    ('sortir', 'vous', 'Passé Composé', 'vous êtes sortis'),
    ('sortir', 'ils', 'Passé Composé', 'ils sont sortis'),
    ('sortir', 'elles', 'Passé Composé', 'elles sont sorties'),
    ('vendre', 'je', 'Passé Composé', 'j''ai vendu'),
    ('vendre', 'tu', 'Passé Composé', 'tu as vendu'),
    ('vendre', 'il', 'Passé Composé', 'il a vendu'),
    ('vendre', 'elle', 'Passé Composé', 'elle a vendu'),
    ('vendre', 'on', 'Passé Composé', 'on a vendu'),
    ('vendre', 'nous', 'Passé Composé', 'nous avons vendu'),
    ('vendre', 'vous', 'Passé Composé', 'vous avez vendu'),
    ('vendre', 'ils', 'Passé Composé', 'ils ont vendu'),
    ('vendre', 'elles', 'Passé Composé', 'elles ont vendu')
) AS c("verb_name", "subject_name", "tense_name", "text")
JOIN "Verb" v ON v."name" = c."verb_name"
JOIN "Subject" s ON s."name" = c."subject_name"
JOIN "Tense" t ON t."name" = c."tense_name"
ON CONFLICT ("verb_id", "subject_id", "tense_id")
DO UPDATE SET "text" = EXCLUDED."text";
