INSERT INTO "Conjugation" ("verb_id", "subject_id", "tense_id", "text")
SELECT v."id", s."id", t."id", c."text"
FROM (
  VALUES
    ('être', 'je', 'Présent', 'je suis'),
    ('être', 'tu', 'Présent', 'tu es'),
    ('être', 'il', 'Présent', 'il est'),
    ('être', 'elle', 'Présent', 'elle est'),
    ('être', 'on', 'Présent', 'on est'),
    ('être', 'nous', 'Présent', 'nous sommes'),
    ('être', 'vous', 'Présent', 'vous êtes'),
    ('être', 'ils', 'Présent', 'ils sont'),
    ('être', 'elles', 'Présent', 'elles sont'),
    ('avoir', 'je', 'Présent', 'j''ai'),
    ('avoir', 'tu', 'Présent', 'tu as'),
    ('avoir', 'il', 'Présent', 'il a'),
    ('avoir', 'elle', 'Présent', 'elle a'),
    ('avoir', 'on', 'Présent', 'on a'),
    ('avoir', 'nous', 'Présent', 'nous avons'),
    ('avoir', 'vous', 'Présent', 'vous avez'),
    ('avoir', 'ils', 'Présent', 'ils ont'),
    ('avoir', 'elles', 'Présent', 'elles ont'),
    ('faire', 'je', 'Présent', 'je fais'),
    ('faire', 'tu', 'Présent', 'tu fais'),
    ('faire', 'il', 'Présent', 'il fait'),
    ('faire', 'elle', 'Présent', 'elle fait'),
    ('faire', 'on', 'Présent', 'on fait'),
    ('faire', 'nous', 'Présent', 'nous faisons'),
    ('faire', 'vous', 'Présent', 'vous faites'),
    ('faire', 'ils', 'Présent', 'ils font'),
    ('faire', 'elles', 'Présent', 'elles font'),
    ('mettre', 'je', 'Présent', 'je mets'),
    ('mettre', 'tu', 'Présent', 'tu mets'),
    ('mettre', 'il', 'Présent', 'il met'),
    ('mettre', 'elle', 'Présent', 'elle met'),
    ('mettre', 'on', 'Présent', 'on met'),
    ('mettre', 'nous', 'Présent', 'nous mettons'),
    ('mettre', 'vous', 'Présent', 'vous mettez'),
    ('mettre', 'ils', 'Présent', 'ils mettent'),
    ('mettre', 'elles', 'Présent', 'elles mettent'),
    ('prendre', 'je', 'Présent', 'je prends'),
    ('prendre', 'tu', 'Présent', 'tu prends'),
    ('prendre', 'il', 'Présent', 'il prend'),
    ('prendre', 'elle', 'Présent', 'elle prend'),
    ('prendre', 'on', 'Présent', 'on prend'),
    ('prendre', 'nous', 'Présent', 'nous prenons'),
    ('prendre', 'vous', 'Présent', 'vous prenez'),
    ('prendre', 'ils', 'Présent', 'ils prennent'),
    ('prendre', 'elles', 'Présent', 'elles prennent'),
    ('dire', 'je', 'Présent', 'je dis'),
    ('dire', 'tu', 'Présent', 'tu dis'),
    ('dire', 'il', 'Présent', 'il dit'),
    ('dire', 'elle', 'Présent', 'elle dit'),
    ('dire', 'on', 'Présent', 'on dit'),
    ('dire', 'nous', 'Présent', 'nous disons'),
    ('dire', 'vous', 'Présent', 'vous dites'),
    ('dire', 'ils', 'Présent', 'ils disent'),
    ('dire', 'elles', 'Présent', 'elles disent'),
    ('écrire', 'je', 'Présent', 'j''écris'),
    ('écrire', 'tu', 'Présent', 'tu écris'),
    ('écrire', 'il', 'Présent', 'il écrit'),
    ('écrire', 'elle', 'Présent', 'elle écrit'),
    ('écrire', 'on', 'Présent', 'on écrit'),
    ('écrire', 'nous', 'Présent', 'nous écrivons'),
    ('écrire', 'vous', 'Présent', 'vous écrivez'),
    ('écrire', 'ils', 'Présent', 'ils écrivent'),
    ('écrire', 'elles', 'Présent', 'elles écrivent'),
    ('voir', 'je', 'Présent', 'je vois'),
    ('voir', 'tu', 'Présent', 'tu vois'),
    ('voir', 'il', 'Présent', 'il voit'),
    ('voir', 'elle', 'Présent', 'elle voit'),
    ('voir', 'on', 'Présent', 'on voit'),
    ('voir', 'nous', 'Présent', 'nous voyons'),
    ('voir', 'vous', 'Présent', 'vous voyez'),
    ('voir', 'ils', 'Présent', 'ils voient'),
    ('voir', 'elles', 'Présent', 'elles voient'),
    ('pouvoir', 'je', 'Présent', 'je puis'),
    ('pouvoir', 'tu', 'Présent', 'tu peux'),
    ('pouvoir', 'il', 'Présent', 'il peut'),
    ('pouvoir', 'elle', 'Présent', 'elle peut'),
    ('pouvoir', 'on', 'Présent', 'on peut'),
    ('pouvoir', 'nous', 'Présent', 'nous pouvons'),
    ('pouvoir', 'vous', 'Présent', 'vous pouvez'),
    ('pouvoir', 'ils', 'Présent', 'ils peuvent'),
    ('pouvoir', 'elles', 'Présent', 'elles peuvent'),
    ('vouloir', 'je', 'Présent', 'je veux'),
    ('vouloir', 'tu', 'Présent', 'tu veux'),
    ('vouloir', 'il', 'Présent', 'il veut'),
    ('vouloir', 'elle', 'Présent', 'elle veut'),
    ('vouloir', 'on', 'Présent', 'on veut'),
    ('vouloir', 'nous', 'Présent', 'nous voulons'),
    ('vouloir', 'vous', 'Présent', 'vous voulez'),
    ('vouloir', 'ils', 'Présent', 'ils veulent'),
    ('vouloir', 'elles', 'Présent', 'elles veulent'),
    ('savoir', 'je', 'Présent', 'je sais'),
    ('savoir', 'tu', 'Présent', 'tu sais'),
    ('savoir', 'il', 'Présent', 'il sait'),
    ('savoir', 'elle', 'Présent', 'elle sait'),
    ('savoir', 'on', 'Présent', 'on sait'),
    ('savoir', 'nous', 'Présent', 'nous savons'),
    ('savoir', 'vous', 'Présent', 'vous savez'),
    ('savoir', 'ils', 'Présent', 'ils savent'),
    ('savoir', 'elles', 'Présent', 'elles savent'),
    ('connaître', 'je', 'Présent', 'je connais'),
    ('connaître', 'tu', 'Présent', 'tu connais'),
    ('connaître', 'il', 'Présent', 'il connaît'),
    ('connaître', 'elle', 'Présent', 'elle connaît'),
    ('connaître', 'on', 'Présent', 'on connaît'),
    ('connaître', 'nous', 'Présent', 'nous connaissons'),
    ('connaître', 'vous', 'Présent', 'vous connaissez'),
    ('connaître', 'ils', 'Présent', 'ils connaissent'),
    ('connaître', 'elles', 'Présent', 'elles connaissent'),
    ('venir', 'je', 'Présent', 'je viens'),
    ('venir', 'tu', 'Présent', 'tu viens'),
    ('venir', 'il', 'Présent', 'il vient'),
    ('venir', 'elle', 'Présent', 'elle vient'),
    ('venir', 'on', 'Présent', 'on vient'),
    ('venir', 'nous', 'Présent', 'nous venons'),
    ('venir', 'vous', 'Présent', 'vous venez'),
    ('venir', 'ils', 'Présent', 'ils viennent'),
    ('venir', 'elles', 'Présent', 'elles viennent'),
    ('devoir', 'je', 'Présent', 'je dois'),
    ('devoir', 'tu', 'Présent', 'tu dois'),
    ('devoir', 'il', 'Présent', 'il doit'),
    ('devoir', 'elle', 'Présent', 'elle doit'),
    ('devoir', 'on', 'Présent', 'on doit'),
    ('devoir', 'nous', 'Présent', 'nous devons'),
    ('devoir', 'vous', 'Présent', 'vous devez'),
    ('devoir', 'ils', 'Présent', 'ils doivent'),
    ('devoir', 'elles', 'Présent', 'elles doivent'),
    ('croire', 'je', 'Présent', 'je crois'),
    ('croire', 'tu', 'Présent', 'tu crois'),
    ('croire', 'il', 'Présent', 'il croit'),
    ('croire', 'elle', 'Présent', 'elle croit'),
    ('croire', 'on', 'Présent', 'on croit'),
    ('croire', 'nous', 'Présent', 'nous croyons'),
    ('croire', 'vous', 'Présent', 'vous croyez'),
    ('croire', 'ils', 'Présent', 'ils croient'),
    ('croire', 'elles', 'Présent', 'elles croient'),
    ('boire', 'je', 'Présent', 'je bois'),
    ('boire', 'tu', 'Présent', 'tu bois'),
    ('boire', 'il', 'Présent', 'il boit'),
    ('boire', 'elle', 'Présent', 'elle boit'),
    ('boire', 'on', 'Présent', 'on boit'),
    ('boire', 'nous', 'Présent', 'nous buvons'),
    ('boire', 'vous', 'Présent', 'vous buvez'),
    ('boire', 'ils', 'Présent', 'ils boivent'),
    ('boire', 'elles', 'Présent', 'elles boivent'),
    ('lire', 'je', 'Présent', 'je lis'),
    ('lire', 'tu', 'Présent', 'tu lis'),
    ('lire', 'il', 'Présent', 'il lit'),
    ('lire', 'elle', 'Présent', 'elle lit'),
    ('lire', 'on', 'Présent', 'on lit'),
    ('lire', 'nous', 'Présent', 'nous lisons'),
    ('lire', 'vous', 'Présent', 'vous lisez'),
    ('lire', 'ils', 'Présent', 'ils lisent'),
    ('lire', 'elles', 'Présent', 'elles lisent'),
    ('vivre', 'je', 'Présent', 'je vis'),
    ('vivre', 'tu', 'Présent', 'tu vis'),
    ('vivre', 'il', 'Présent', 'il vit'),
    ('vivre', 'elle', 'Présent', 'elle vit'),
    ('vivre', 'on', 'Présent', 'on vit'),
    ('vivre', 'nous', 'Présent', 'nous vivons'),
    ('vivre', 'vous', 'Présent', 'vous vivez'),
    ('vivre', 'ils', 'Présent', 'ils vivent'),
    ('vivre', 'elles', 'Présent', 'elles vivent'),
    ('recevoir', 'je', 'Présent', 'je reçois'),
    ('recevoir', 'tu', 'Présent', 'tu reçois'),
    ('recevoir', 'il', 'Présent', 'il reçoit'),
    ('recevoir', 'elle', 'Présent', 'elle reçoit'),
    ('recevoir', 'on', 'Présent', 'on reçoit'),
    ('recevoir', 'nous', 'Présent', 'nous recevons'),
    ('recevoir', 'vous', 'Présent', 'vous recevez'),
    ('recevoir', 'ils', 'Présent', 'ils reçoivent'),
    ('recevoir', 'elles', 'Présent', 'elles reçoivent'),
    ('ouvrir', 'je', 'Présent', 'j''ouvre'),
    ('ouvrir', 'tu', 'Présent', 'tu ouvres'),
    ('ouvrir', 'il', 'Présent', 'il ouvre'),
    ('ouvrir', 'elle', 'Présent', 'elle ouvre'),
    ('ouvrir', 'on', 'Présent', 'on ouvre'),
    ('ouvrir', 'nous', 'Présent', 'nous ouvrons'),
    ('ouvrir', 'vous', 'Présent', 'vous ouvrez'),
    ('ouvrir', 'ils', 'Présent', 'ils ouvrent'),
    ('ouvrir', 'elles', 'Présent', 'elles ouvrent'),
    ('offrir', 'je', 'Présent', 'j''offre'),
    ('offrir', 'tu', 'Présent', 'tu offres'),
    ('offrir', 'il', 'Présent', 'il offre'),
    ('offrir', 'elle', 'Présent', 'elle offre'),
    ('offrir', 'on', 'Présent', 'on offre'),
    ('offrir', 'nous', 'Présent', 'nous offrons'),
    ('offrir', 'vous', 'Présent', 'vous offrez'),
    ('offrir', 'ils', 'Présent', 'ils offrent'),
    ('offrir', 'elles', 'Présent', 'elles offrent'),
    ('naître', 'je', 'Présent', 'je nais'),
    ('naître', 'tu', 'Présent', 'tu nais'),
    ('naître', 'il', 'Présent', 'il naît'),
    ('naître', 'elle', 'Présent', 'elle naît'),
    ('naître', 'on', 'Présent', 'on naît'),
    ('naître', 'nous', 'Présent', 'nous naissons'),
    ('naître', 'vous', 'Présent', 'vous naissez'),
    ('naître', 'ils', 'Présent', 'ils naissent'),
    ('naître', 'elles', 'Présent', 'elles naissent'),
    ('mourir', 'je', 'Présent', 'je meurs'),
    ('mourir', 'tu', 'Présent', 'tu meurs'),
    ('mourir', 'il', 'Présent', 'il meurt'),
    ('mourir', 'elle', 'Présent', 'elle meurt'),
    ('mourir', 'on', 'Présent', 'on meurt'),
    ('mourir', 'nous', 'Présent', 'nous mourons'),
    ('mourir', 'vous', 'Présent', 'vous mourez'),
    ('mourir', 'ils', 'Présent', 'ils meurent'),
    ('mourir', 'elles', 'Présent', 'elles meurent'),
    ('tenir', 'je', 'Présent', 'je tiens'),
    ('tenir', 'tu', 'Présent', 'tu tiens'),
    ('tenir', 'il', 'Présent', 'il tient'),
    ('tenir', 'elle', 'Présent', 'elle tient'),
    ('tenir', 'on', 'Présent', 'on tient'),
    ('tenir', 'nous', 'Présent', 'nous tenons'),
    ('tenir', 'vous', 'Présent', 'vous tenez'),
    ('tenir', 'ils', 'Présent', 'ils tiennent'),
    ('tenir', 'elles', 'Présent', 'elles tiennent'),
    ('suivre', 'je', 'Présent', 'je suis'),
    ('suivre', 'tu', 'Présent', 'tu suis'),
    ('suivre', 'il', 'Présent', 'il suit'),
    ('suivre', 'elle', 'Présent', 'elle suit'),
    ('suivre', 'on', 'Présent', 'on suit'),
    ('suivre', 'nous', 'Présent', 'nous suivons'),
    ('suivre', 'vous', 'Présent', 'vous suivez'),
    ('suivre', 'ils', 'Présent', 'ils suivent'),
    ('suivre', 'elles', 'Présent', 'elles suivent'),
    ('rire', 'je', 'Présent', 'je ris'),
    ('rire', 'tu', 'Présent', 'tu ris'),
    ('rire', 'il', 'Présent', 'il rit'),
    ('rire', 'elle', 'Présent', 'elle rit'),
    ('rire', 'on', 'Présent', 'on rit'),
    ('rire', 'nous', 'Présent', 'nous rions'),
    ('rire', 'vous', 'Présent', 'vous riez'),
    ('rire', 'ils', 'Présent', 'ils rient'),
    ('rire', 'elles', 'Présent', 'elles rient'),
    ('plaire', 'je', 'Présent', 'je plais'),
    ('plaire', 'tu', 'Présent', 'tu plais'),
    ('plaire', 'il', 'Présent', 'il plaît'),
    ('plaire', 'elle', 'Présent', 'elle plaît'),
    ('plaire', 'on', 'Présent', 'on plaît'),
    ('plaire', 'nous', 'Présent', 'nous plaisons'),
    ('plaire', 'vous', 'Présent', 'vous plaisez'),
    ('plaire', 'ils', 'Présent', 'ils plaisent'),
    ('plaire', 'elles', 'Présent', 'elles plaisent'),
    ('falloir', 'je', 'Présent', 'il faut'),
    ('falloir', 'tu', 'Présent', 'il faut'),
    ('falloir', 'il', 'Présent', 'il faut'),
    ('falloir', 'elle', 'Présent', 'il faut'),
    ('falloir', 'on', 'Présent', 'il faut'),
    ('falloir', 'nous', 'Présent', 'il faut'),
    ('falloir', 'vous', 'Présent', 'il faut'),
    ('falloir', 'ils', 'Présent', 'il faut'),
    ('falloir', 'elles', 'Présent', 'il faut'),
    ('valoir', 'je', 'Présent', 'je vaux'),
    ('valoir', 'tu', 'Présent', 'tu vaux'),
    ('valoir', 'il', 'Présent', 'il vaut'),
    ('valoir', 'elle', 'Présent', 'elle vaut'),
    ('valoir', 'on', 'Présent', 'on vaut'),
    ('valoir', 'nous', 'Présent', 'nous valons'),
    ('valoir', 'vous', 'Présent', 'vous valez'),
    ('valoir', 'ils', 'Présent', 'ils valent'),
    ('valoir', 'elles', 'Présent', 'elles valent'),
    ('pleuvoir', 'je', 'Présent', 'il pleut'),
    ('pleuvoir', 'tu', 'Présent', 'il pleut'),
    ('pleuvoir', 'il', 'Présent', 'il pleut'),
    ('pleuvoir', 'elle', 'Présent', 'il pleut'),
    ('pleuvoir', 'on', 'Présent', 'il pleut'),
    ('pleuvoir', 'nous', 'Présent', 'il pleut'),
    ('pleuvoir', 'vous', 'Présent', 'il pleut'),
    ('pleuvoir', 'ils', 'Présent', 'il pleut'),
    ('pleuvoir', 'elles', 'Présent', 'il pleut'),
    ('apprendre', 'je', 'Présent', 'j''apprends'),
    ('apprendre', 'tu', 'Présent', 'tu apprends'),
    ('apprendre', 'il', 'Présent', 'il apprend'),
    ('apprendre', 'elle', 'Présent', 'elle apprend'),
    ('apprendre', 'on', 'Présent', 'on apprend'),
    ('apprendre', 'nous', 'Présent', 'nous apprenons'),
    ('apprendre', 'vous', 'Présent', 'vous apprenez'),
    ('apprendre', 'ils', 'Présent', 'ils apprennent'),
    ('apprendre', 'elles', 'Présent', 'elles apprennent'),
    ('comprendre', 'je', 'Présent', 'je comprends'),
    ('comprendre', 'tu', 'Présent', 'tu comprends'),
    ('comprendre', 'il', 'Présent', 'il comprend'),
    ('comprendre', 'elle', 'Présent', 'elle comprend'),
    ('comprendre', 'on', 'Présent', 'on comprend'),
    ('comprendre', 'nous', 'Présent', 'nous comprenons'),
    ('comprendre', 'vous', 'Présent', 'vous comprenez'),
    ('comprendre', 'ils', 'Présent', 'ils comprennent'),
    ('comprendre', 'elles', 'Présent', 'elles comprennent'),
    ('surprendre', 'je', 'Présent', 'je surprends'),
    ('surprendre', 'tu', 'Présent', 'tu surprends'),
    ('surprendre', 'il', 'Présent', 'il surprend'),
    ('surprendre', 'elle', 'Présent', 'elle surprend'),
    ('surprendre', 'on', 'Présent', 'on surprend'),
    ('surprendre', 'nous', 'Présent', 'nous surprenons'),
    ('surprendre', 'vous', 'Présent', 'vous surprenez'),
    ('surprendre', 'ils', 'Présent', 'ils surprennent'),
    ('surprendre', 'elles', 'Présent', 'elles surprennent'),
    ('découvrir', 'je', 'Présent', 'je découvre'),
    ('découvrir', 'tu', 'Présent', 'tu découvres'),
    ('découvrir', 'il', 'Présent', 'il découvre'),
    ('découvrir', 'elle', 'Présent', 'elle découvre'),
    ('découvrir', 'on', 'Présent', 'on découvre'),
    ('découvrir', 'nous', 'Présent', 'nous découvrons'),
    ('découvrir', 'vous', 'Présent', 'vous découvrez'),
    ('découvrir', 'ils', 'Présent', 'ils découvrent'),
    ('découvrir', 'elles', 'Présent', 'elles découvrent'),
    ('souffrir', 'je', 'Présent', 'je souffre'),
    ('souffrir', 'tu', 'Présent', 'tu souffres'),
    ('souffrir', 'il', 'Présent', 'il souffre'),
    ('souffrir', 'elle', 'Présent', 'elle souffre'),
    ('souffrir', 'on', 'Présent', 'on souffre'),
    ('souffrir', 'nous', 'Présent', 'nous souffrons'),
    ('souffrir', 'vous', 'Présent', 'vous souffrez'),
    ('souffrir', 'ils', 'Présent', 'ils souffrent'),
    ('souffrir', 'elles', 'Présent', 'elles souffrent'),
    ('conduire', 'je', 'Présent', 'je conduis'),
    ('conduire', 'tu', 'Présent', 'tu conduis'),
    ('conduire', 'il', 'Présent', 'il conduit'),
    ('conduire', 'elle', 'Présent', 'elle conduit'),
    ('conduire', 'on', 'Présent', 'on conduit'),
    ('conduire', 'nous', 'Présent', 'nous conduisons'),
    ('conduire', 'vous', 'Présent', 'vous conduisez'),
    ('conduire', 'ils', 'Présent', 'ils conduisent'),
    ('conduire', 'elles', 'Présent', 'elles conduisent'),
    ('produire', 'je', 'Présent', 'je produis'),
    ('produire', 'tu', 'Présent', 'tu produis'),
    ('produire', 'il', 'Présent', 'il produit'),
    ('produire', 'elle', 'Présent', 'elle produit'),
    ('produire', 'on', 'Présent', 'on produit'),
    ('produire', 'nous', 'Présent', 'nous produisons'),
    ('produire', 'vous', 'Présent', 'vous produisez'),
    ('produire', 'ils', 'Présent', 'ils produisent'),
    ('produire', 'elles', 'Présent', 'elles produisent'),
    ('traduire', 'je', 'Présent', 'je traduis'),
    ('traduire', 'tu', 'Présent', 'tu traduis'),
    ('traduire', 'il', 'Présent', 'il traduit'),
    ('traduire', 'elle', 'Présent', 'elle traduit'),
    ('traduire', 'on', 'Présent', 'on traduit'),
    ('traduire', 'nous', 'Présent', 'nous traduisons'),
    ('traduire', 'vous', 'Présent', 'vous traduisez'),
    ('traduire', 'ils', 'Présent', 'ils traduisent'),
    ('traduire', 'elles', 'Présent', 'elles traduisent'),
    ('atteindre', 'je', 'Présent', 'j''atteins'),
    ('atteindre', 'tu', 'Présent', 'tu atteins'),
    ('atteindre', 'il', 'Présent', 'il atteint'),
    ('atteindre', 'elle', 'Présent', 'elle atteint'),
    ('atteindre', 'on', 'Présent', 'on atteint'),
    ('atteindre', 'nous', 'Présent', 'nous atteignons'),
    ('atteindre', 'vous', 'Présent', 'vous atteignez'),
    ('atteindre', 'ils', 'Présent', 'ils atteignent'),
    ('atteindre', 'elles', 'Présent', 'elles atteignent'),
    ('craindre', 'je', 'Présent', 'je crains'),
    ('craindre', 'tu', 'Présent', 'tu crains'),
    ('craindre', 'il', 'Présent', 'il craint'),
    ('craindre', 'elle', 'Présent', 'elle craint'),
    ('craindre', 'on', 'Présent', 'on craint'),
    ('craindre', 'nous', 'Présent', 'nous craignons'),
    ('craindre', 'vous', 'Présent', 'vous craignez'),
    ('craindre', 'ils', 'Présent', 'ils craignent'),
    ('craindre', 'elles', 'Présent', 'elles craignent'),
    ('éteindre', 'je', 'Présent', 'j''éteins'),
    ('éteindre', 'tu', 'Présent', 'tu éteins'),
    ('éteindre', 'il', 'Présent', 'il éteint'),
    ('éteindre', 'elle', 'Présent', 'elle éteint'),
    ('éteindre', 'on', 'Présent', 'on éteint'),
    ('éteindre', 'nous', 'Présent', 'nous éteignons'),
    ('éteindre', 'vous', 'Présent', 'vous éteignez'),
    ('éteindre', 'ils', 'Présent', 'ils éteignent'),
    ('éteindre', 'elles', 'Présent', 'elles éteignent'),
    ('joindre', 'je', 'Présent', 'je joins'),
    ('joindre', 'tu', 'Présent', 'tu joins'),
    ('joindre', 'il', 'Présent', 'il joint'),
    ('joindre', 'elle', 'Présent', 'elle joint'),
    ('joindre', 'on', 'Présent', 'on joint'),
    ('joindre', 'nous', 'Présent', 'nous joignons'),
    ('joindre', 'vous', 'Présent', 'vous joignez'),
    ('joindre', 'ils', 'Présent', 'ils joignent'),
    ('joindre', 'elles', 'Présent', 'elles joignent'),
    ('peindre', 'je', 'Présent', 'je peins'),
    ('peindre', 'tu', 'Présent', 'tu peins'),
    ('peindre', 'il', 'Présent', 'il peint'),
    ('peindre', 'elle', 'Présent', 'elle peint'),
    ('peindre', 'on', 'Présent', 'on peint'),
    ('peindre', 'nous', 'Présent', 'nous peignons'),
    ('peindre', 'vous', 'Présent', 'vous peignez'),
    ('peindre', 'ils', 'Présent', 'ils peignent'),
    ('peindre', 'elles', 'Présent', 'elles peignent'),
    ('clore', 'je', 'Présent', 'je clos'),
    ('clore', 'tu', 'Présent', 'tu clos'),
    ('clore', 'il', 'Présent', 'il clôt'),
    ('clore', 'elle', 'Présent', 'elle clôt'),
    ('clore', 'on', 'Présent', 'on clôt'),
    ('clore', 'nous', 'Présent', 'nous closons'),
    ('clore', 'vous', 'Présent', 'vous closez'),
    ('clore', 'ils', 'Présent', 'ils closent'),
    ('clore', 'elles', 'Présent', 'elles closent'),
    ('inclure', 'je', 'Présent', 'j''inclus'),
    ('inclure', 'tu', 'Présent', 'tu inclus'),
    ('inclure', 'il', 'Présent', 'il inclut'),
    ('inclure', 'elle', 'Présent', 'elle inclut'),
    ('inclure', 'on', 'Présent', 'on inclut'),
    ('inclure', 'nous', 'Présent', 'nous incluons'),
    ('inclure', 'vous', 'Présent', 'vous incluez'),
    ('inclure', 'ils', 'Présent', 'ils incluent'),
    ('inclure', 'elles', 'Présent', 'elles incluent'),
    ('cuire', 'je', 'Présent', 'je cuis'),
    ('cuire', 'tu', 'Présent', 'tu cuis'),
    ('cuire', 'il', 'Présent', 'il cuit'),
    ('cuire', 'elle', 'Présent', 'elle cuit'),
    ('cuire', 'on', 'Présent', 'on cuit'),
    ('cuire', 'nous', 'Présent', 'nous cuisons'),
    ('cuire', 'vous', 'Présent', 'vous cuisez'),
    ('cuire', 'ils', 'Présent', 'ils cuisent'),
    ('cuire', 'elles', 'Présent', 'elles cuisent'),
    ('resoudre', 'je', 'Présent', 'je résous'),
    ('resoudre', 'tu', 'Présent', 'tu résous'),
    ('resoudre', 'il', 'Présent', 'il résout'),
    ('resoudre', 'elle', 'Présent', 'elle résout'),
    ('resoudre', 'on', 'Présent', 'on résout'),
    ('resoudre', 'nous', 'Présent', 'nous résolvons'),
    ('resoudre', 'vous', 'Présent', 'vous résolvez'),
    ('resoudre', 'ils', 'Présent', 'ils résolvent'),
    ('resoudre', 'elles', 'Présent', 'elles résolvent'),
    ('absoudre', 'je', 'Présent', 'j''absous'),
    ('absoudre', 'tu', 'Présent', 'tu absous'),
    ('absoudre', 'il', 'Présent', 'il absout'),
    ('absoudre', 'elle', 'Présent', 'elle absout'),
    ('absoudre', 'on', 'Présent', 'on absout'),
    ('absoudre', 'nous', 'Présent', 'nous absolvons'),
    ('absoudre', 'vous', 'Présent', 'vous absolvez'),
    ('absoudre', 'ils', 'Présent', 'ils absolvent'),
    ('absoudre', 'elles', 'Présent', 'elles absolvent'),
    ('se lever', 'je', 'Présent', 'je me lève'),
    ('se lever', 'tu', 'Présent', 'tu te lèves'),
    ('se lever', 'il', 'Présent', 'il se lève'),
    ('se lever', 'elle', 'Présent', 'elle se lève'),
    ('se lever', 'on', 'Présent', 'on se lève'),
    ('se lever', 'nous', 'Présent', 'nous nous levons'),
    ('se lever', 'vous', 'Présent', 'vous vous levez'),
    ('se lever', 'ils', 'Présent', 'ils se lèvent'),
    ('se lever', 'elles', 'Présent', 'elles se lèvent'),
    ('se coucher', 'je', 'Présent', 'je me couche'),
    ('se coucher', 'tu', 'Présent', 'tu te couches'),
    ('se coucher', 'il', 'Présent', 'il se couche'),
    ('se coucher', 'elle', 'Présent', 'elle se couche'),
    ('se coucher', 'on', 'Présent', 'on se couche'),
    ('se coucher', 'nous', 'Présent', 'nous nous couchons'),
    ('se coucher', 'vous', 'Présent', 'vous vous couchez'),
    ('se coucher', 'ils', 'Présent', 'ils se couchent'),
    ('se coucher', 'elles', 'Présent', 'elles se couchent'),
    ('s’habiller', 'je', 'Présent', 'je m''habille'),
    ('s’habiller', 'tu', 'Présent', 'tu t''habilles'),
    ('s’habiller', 'il', 'Présent', 'il s''habille'),
    ('s’habiller', 'elle', 'Présent', 'elle s''habille'),
    ('s’habiller', 'on', 'Présent', 'on s''habille'),
    ('s’habiller', 'nous', 'Présent', 'nous nous habillons'),
    ('s’habiller', 'vous', 'Présent', 'vous vous habillez'),
    ('s’habiller', 'ils', 'Présent', 'ils s''habillent'),
    ('s’habiller', 'elles', 'Présent', 'elles s''habillent'),
    ('se laver', 'je', 'Présent', 'je me lave'),
    ('se laver', 'tu', 'Présent', 'tu te laves'),
    ('se laver', 'il', 'Présent', 'il se lave'),
    ('se laver', 'elle', 'Présent', 'elle se lave'),
    ('se laver', 'on', 'Présent', 'on se lave'),
    ('se laver', 'nous', 'Présent', 'nous nous lavons'),
    ('se laver', 'vous', 'Présent', 'vous vous lavez'),
    ('se laver', 'ils', 'Présent', 'ils se lavent'),
    ('se laver', 'elles', 'Présent', 'elles se lavent'),
    ('se brosser', 'je', 'Présent', 'je me brosse'),
    ('se brosser', 'tu', 'Présent', 'tu te brosses'),
    ('se brosser', 'il', 'Présent', 'il se brosse'),
    ('se brosser', 'elle', 'Présent', 'elle se brosse'),
    ('se brosser', 'on', 'Présent', 'on se brosse'),
    ('se brosser', 'nous', 'Présent', 'nous nous brossons'),
    ('se brosser', 'vous', 'Présent', 'vous vous brossez'),
    ('se brosser', 'ils', 'Présent', 'ils se brossent'),
    ('se brosser', 'elles', 'Présent', 'elles se brossent'),
    ('se réveiller', 'je', 'Présent', 'je me réveille'),
    ('se réveiller', 'tu', 'Présent', 'tu te réveilles'),
    ('se réveiller', 'il', 'Présent', 'il se réveille'),
    ('se réveiller', 'elle', 'Présent', 'elle se réveille'),
    ('se réveiller', 'on', 'Présent', 'on se réveille'),
    ('se réveiller', 'nous', 'Présent', 'nous nous réveillons'),
    ('se réveiller', 'vous', 'Présent', 'vous vous réveillez'),
    ('se réveiller', 'ils', 'Présent', 'ils se réveillent'),
    ('se réveiller', 'elles', 'Présent', 'elles se réveillent'),
    ('se reposer', 'je', 'Présent', 'je me repose'),
    ('se reposer', 'tu', 'Présent', 'tu te reposes'),
    ('se reposer', 'il', 'Présent', 'il se repose'),
    ('se reposer', 'elle', 'Présent', 'elle se repose'),
    ('se reposer', 'on', 'Présent', 'on se repose'),
    ('se reposer', 'nous', 'Présent', 'nous nous reposons'),
    ('se reposer', 'vous', 'Présent', 'vous vous reposez'),
    ('se reposer', 'ils', 'Présent', 'ils se reposent'),
    ('se reposer', 'elles', 'Présent', 'elles se reposent'),
    ('se dépêcher', 'je', 'Présent', 'je me dépêche'),
    ('se dépêcher', 'tu', 'Présent', 'tu te dépêches'),
    ('se dépêcher', 'il', 'Présent', 'il se dépêche'),
    ('se dépêcher', 'elle', 'Présent', 'elle se dépêche'),
    ('se dépêcher', 'on', 'Présent', 'on se dépêche'),
    ('se dépêcher', 'nous', 'Présent', 'nous nous dépêchons'),
    ('se dépêcher', 'vous', 'Présent', 'vous vous dépêchez'),
    ('se dépêcher', 'ils', 'Présent', 'ils se dépêchent'),
    ('se dépêcher', 'elles', 'Présent', 'elles se dépêchent'),
    ('se souvenir', 'je', 'Présent', 'je me souviens'),
    ('se souvenir', 'tu', 'Présent', 'tu te souviens'),
    ('se souvenir', 'il', 'Présent', 'il se souvient'),
    ('se souvenir', 'elle', 'Présent', 'elle se souvient'),
    ('se souvenir', 'on', 'Présent', 'on se souvient'),
    ('se souvenir', 'nous', 'Présent', 'nous nous souvenons'),
    ('se souvenir', 'vous', 'Présent', 'vous vous souvenez'),
    ('se souvenir', 'ils', 'Présent', 'ils se souviennent'),
    ('se souvenir', 'elles', 'Présent', 'elles se souviennent'),
    ('se rendre compte', 'je', 'Présent', 'je me rends compte'),
    ('se rendre compte', 'tu', 'Présent', 'tu te rends compte'),
    ('se rendre compte', 'il', 'Présent', 'il se rend compte'),
    ('se rendre compte', 'elle', 'Présent', 'elle se rend compte'),
    ('se rendre compte', 'on', 'Présent', 'on se rend compte'),
    ('se rendre compte', 'nous', 'Présent', 'nous nous rendons compte'),
    ('se rendre compte', 'vous', 'Présent', 'vous vous rendez compte'),
    ('se rendre compte', 'ils', 'Présent', 'ils se rendent compte'),
    ('se rendre compte', 'elles', 'Présent', 'elles se rendent compte'),
    ('s’intéresser', 'je', 'Présent', 'je m''intéresse'),
    ('s’intéresser', 'tu', 'Présent', 'tu t''intéresses'),
    ('s’intéresser', 'il', 'Présent', 'il s''intéresse'),
    ('s’intéresser', 'elle', 'Présent', 'elle s''intéresse'),
    ('s’intéresser', 'on', 'Présent', 'on s''intéresse'),
    ('s’intéresser', 'nous', 'Présent', 'nous nous intéressons'),
    ('s’intéresser', 'vous', 'Présent', 'vous vous intéressez'),
    ('s’intéresser', 'ils', 'Présent', 'ils s''intéressent'),
    ('s’intéresser', 'elles', 'Présent', 'elles s''intéressent'),
    ('s’ennuyer', 'je', 'Présent', 'je m''ennuie'),
    ('s’ennuyer', 'tu', 'Présent', 'tu t''ennuies'),
    ('s’ennuyer', 'il', 'Présent', 'il s''ennuie'),
    ('s’ennuyer', 'elle', 'Présent', 'elle s''ennuie'),
    ('s’ennuyer', 'on', 'Présent', 'on s''ennuie'),
    ('s’ennuyer', 'nous', 'Présent', 'nous nous ennuyons'),
    ('s’ennuyer', 'vous', 'Présent', 'vous vous ennuyez'),
    ('s’ennuyer', 'ils', 'Présent', 'ils s''ennuient'),
    ('s’ennuyer', 'elles', 'Présent', 'elles s''ennuient'),
    ('se fâcher', 'je', 'Présent', 'je me fâche'),
    ('se fâcher', 'tu', 'Présent', 'tu te fâches'),
    ('se fâcher', 'il', 'Présent', 'il se fâche'),
    ('se fâcher', 'elle', 'Présent', 'elle se fâche'),
    ('se fâcher', 'on', 'Présent', 'on se fâche'),
    ('se fâcher', 'nous', 'Présent', 'nous nous fâchons'),
    ('se fâcher', 'vous', 'Présent', 'vous vous fâchez'),
    ('se fâcher', 'ils', 'Présent', 'ils se fâchent'),
    ('se fâcher', 'elles', 'Présent', 'elles se fâchent'),
    ('se tromper', 'je', 'Présent', 'je me trompe'),
    ('se tromper', 'tu', 'Présent', 'tu te trompes'),
    ('se tromper', 'il', 'Présent', 'il se trompe'),
    ('se tromper', 'elle', 'Présent', 'elle se trompe'),
    ('se tromper', 'on', 'Présent', 'on se trompe'),
    ('se tromper', 'nous', 'Présent', 'nous nous trompons'),
    ('se tromper', 'vous', 'Présent', 'vous vous trompez'),
    ('se tromper', 'ils', 'Présent', 'ils se trompent'),
    ('se tromper', 'elles', 'Présent', 'elles se trompent'),
    ('se taire', 'je', 'Présent', 'je me tais'),
    ('se taire', 'tu', 'Présent', 'tu te tais'),
    ('se taire', 'il', 'Présent', 'il se taît'),
    ('se taire', 'elle', 'Présent', 'elle se taît'),
    ('se taire', 'on', 'Présent', 'on se taît'),
    ('se taire', 'nous', 'Présent', 'nous nous taisons'),
    ('se taire', 'vous', 'Présent', 'vous vous taisez'),
    ('se taire', 'ils', 'Présent', 'ils se taisent'),
    ('se taire', 'elles', 'Présent', 'elles se taisent'),
    ('s’asseoir', 'je', 'Présent', 'je m''assois'),
    ('s’asseoir', 'tu', 'Présent', 'tu t''assois'),
    ('s’asseoir', 'il', 'Présent', 'il s''assoit'),
    ('s’asseoir', 'elle', 'Présent', 'elle s''assoit'),
    ('s’asseoir', 'on', 'Présent', 'on s''assoit'),
    ('s’asseoir', 'nous', 'Présent', 'nous nous assoyons'),
    ('s’asseoir', 'vous', 'Présent', 'vous vous assoyez'),
    ('s’asseoir', 'ils', 'Présent', 'ils s''assoient'),
    ('s’asseoir', 'elles', 'Présent', 'elles s''assoient'),
    ('s’entendre', 'je', 'Présent', 'je m''entends'),
    ('s’entendre', 'tu', 'Présent', 'tu t''entends'),
    ('s’entendre', 'il', 'Présent', 'il s''entend'),
    ('s’entendre', 'elle', 'Présent', 'elle s''entend'),
    ('s’entendre', 'on', 'Présent', 'on s''entend'),
    ('s’entendre', 'nous', 'Présent', 'nous nous entendons'),
    ('s’entendre', 'vous', 'Présent', 'vous vous entendez'),
    ('s’entendre', 'ils', 'Présent', 'ils s''entendent'),
    ('s’entendre', 'elles', 'Présent', 'elles s''entendent'),
    ('se disputer', 'je', 'Présent', 'je me dispute'),
    ('se disputer', 'tu', 'Présent', 'tu te disputes'),
    ('se disputer', 'il', 'Présent', 'il se dispute'),
    ('se disputer', 'elle', 'Présent', 'elle se dispute'),
    ('se disputer', 'on', 'Présent', 'on se dispute'),
    ('se disputer', 'nous', 'Présent', 'nous nous disputons'),
    ('se disputer', 'vous', 'Présent', 'vous vous disputez'),
    ('se disputer', 'ils', 'Présent', 'ils se disputent'),
    ('se disputer', 'elles', 'Présent', 'elles se disputent'),
    ('se marier', 'je', 'Présent', 'je me marie'),
    ('se marier', 'tu', 'Présent', 'tu te maries'),
    ('se marier', 'il', 'Présent', 'il se marie'),
    ('se marier', 'elle', 'Présent', 'elle se marie'),
    ('se marier', 'on', 'Présent', 'on se marie'),
    ('se marier', 'nous', 'Présent', 'nous nous marions'),
    ('se marier', 'vous', 'Présent', 'vous vous mariez'),
    ('se marier', 'ils', 'Présent', 'ils se marient'),
    ('se marier', 'elles', 'Présent', 'elles se marient'),
    ('se divorcer', 'je', 'Présent', 'je me divorce'),
    ('se divorcer', 'tu', 'Présent', 'tu te divorces'),
    ('se divorcer', 'il', 'Présent', 'il se divorce'),
    ('se divorcer', 'elle', 'Présent', 'elle se divorce'),
    ('se divorcer', 'on', 'Présent', 'on se divorce'),
    ('se divorcer', 'nous', 'Présent', 'nous nous divorçons'),
    ('se divorcer', 'vous', 'Présent', 'vous vous divorcez'),
    ('se divorcer', 'ils', 'Présent', 'ils se divorcent'),
    ('se divorcer', 'elles', 'Présent', 'elles se divorcent'),
    ('se battre', 'je', 'Présent', 'je me bats'),
    ('se battre', 'tu', 'Présent', 'tu te bats'),
    ('se battre', 'il', 'Présent', 'il se bat'),
    ('se battre', 'elle', 'Présent', 'elle se bat'),
    ('se battre', 'on', 'Présent', 'on se bat'),
    ('se battre', 'nous', 'Présent', 'nous nous battons'),
    ('se battre', 'vous', 'Présent', 'vous vous battez'),
    ('se battre', 'ils', 'Présent', 'ils se battent'),
    ('se battre', 'elles', 'Présent', 'elles se battent'),
    ('s’en aller', 'je', 'Présent', 'je m''en vais'),
    ('s’en aller', 'tu', 'Présent', 'tu t''en vas'),
    ('s’en aller', 'il', 'Présent', 'il s''en va'),
    ('s’en aller', 'elle', 'Présent', 'elle s''en va'),
    ('s’en aller', 'on', 'Présent', 'on s''en va'),
    ('s’en aller', 'nous', 'Présent', 'nous nous en allons'),
    ('s’en aller', 'vous', 'Présent', 'vous vous en allez'),
    ('s’en aller', 'ils', 'Présent', 'ils s''en vont'),
    ('s’en aller', 'elles', 'Présent', 'elles s''en vont'),
    ('se rendre', 'je', 'Présent', 'je me rends'),
    ('se rendre', 'tu', 'Présent', 'tu te rends'),
    ('se rendre', 'il', 'Présent', 'il se rend'),
    ('se rendre', 'elle', 'Présent', 'elle se rend'),
    ('se rendre', 'on', 'Présent', 'on se rend'),
    ('se rendre', 'nous', 'Présent', 'nous nous rendons'),
    ('se rendre', 'vous', 'Présent', 'vous vous rendez'),
    ('se rendre', 'ils', 'Présent', 'ils se rendent'),
    ('se rendre', 'elles', 'Présent', 'elles se rendent'),
    ('se servir', 'je', 'Présent', 'je me sers'),
    ('se servir', 'tu', 'Présent', 'tu te sers'),
    ('se servir', 'il', 'Présent', 'il se sert'),
    ('se servir', 'elle', 'Présent', 'elle se sert'),
    ('se servir', 'on', 'Présent', 'on se sert'),
    ('se servir', 'nous', 'Présent', 'nous nous servons'),
    ('se servir', 'vous', 'Présent', 'vous vous servez'),
    ('se servir', 'ils', 'Présent', 'ils se servent'),
    ('se servir', 'elles', 'Présent', 'elles se servent'),
    ('s’apercevoir', 'je', 'Présent', 'je m''aperçois'),
    ('s’apercevoir', 'tu', 'Présent', 'tu t''aperçois'),
    ('s’apercevoir', 'il', 'Présent', 'il s''aperçoit'),
    ('s’apercevoir', 'elle', 'Présent', 'elle s''aperçoit'),
    ('s’apercevoir', 'on', 'Présent', 'on s''aperçoit'),
    ('s’apercevoir', 'nous', 'Présent', 'nous nous apercevons'),
    ('s’apercevoir', 'vous', 'Présent', 'vous vous apercevez'),
    ('s’apercevoir', 'ils', 'Présent', 'ils s''aperçoivent'),
    ('s’apercevoir', 'elles', 'Présent', 'elles s''aperçoivent'),
    ('se douter', 'je', 'Présent', 'je me doute'),
    ('se douter', 'tu', 'Présent', 'tu te doutes'),
    ('se douter', 'il', 'Présent', 'il se doute'),
    ('se douter', 'elle', 'Présent', 'elle se doute'),
    ('se douter', 'on', 'Présent', 'on se doute'),
    ('se douter', 'nous', 'Présent', 'nous nous doutons'),
    ('se douter', 'vous', 'Présent', 'vous vous doutez'),
    ('se douter', 'ils', 'Présent', 'ils se doutent'),
    ('se douter', 'elles', 'Présent', 'elles se doutent'),
    ('se passer', 'je', 'Présent', 'je me passe'),
    ('se passer', 'tu', 'Présent', 'tu te passes'),
    ('se passer', 'il', 'Présent', 'il se passe'),
    ('se passer', 'elle', 'Présent', 'elle se passe'),
    ('se passer', 'on', 'Présent', 'on se passe'),
    ('se passer', 'nous', 'Présent', 'nous nous passons'),
    ('se passer', 'vous', 'Présent', 'vous vous passez'),
    ('se passer', 'ils', 'Présent', 'ils se passent'),
    ('se passer', 'elles', 'Présent', 'elles se passent'),
    ('se trouver', 'je', 'Présent', 'je me trouve'),
    ('se trouver', 'tu', 'Présent', 'tu te trouves'),
    ('se trouver', 'il', 'Présent', 'il se trouve'),
    ('se trouver', 'elle', 'Présent', 'elle se trouve'),
    ('se trouver', 'on', 'Présent', 'on se trouve'),
    ('se trouver', 'nous', 'Présent', 'nous nous trouvons'),
    ('se trouver', 'vous', 'Présent', 'vous vous trouvez'),
    ('se trouver', 'ils', 'Présent', 'ils se trouvent'),
    ('se trouver', 'elles', 'Présent', 'elles se trouvent'),
    ('se mettre', 'je', 'Présent', 'je me mets'),
    ('se mettre', 'tu', 'Présent', 'tu te mets'),
    ('se mettre', 'il', 'Présent', 'il se met'),
    ('se mettre', 'elle', 'Présent', 'elle se met'),
    ('se mettre', 'on', 'Présent', 'on se met'),
    ('se mettre', 'nous', 'Présent', 'nous nous mettons'),
    ('se mettre', 'vous', 'Présent', 'vous vous mettez'),
    ('se mettre', 'ils', 'Présent', 'ils se mettent'),
    ('se mettre', 'elles', 'Présent', 'elles se mettent'),
    ('se faire', 'je', 'Présent', 'je me fais'),
    ('se faire', 'tu', 'Présent', 'tu te fais'),
    ('se faire', 'il', 'Présent', 'il se fait'),
    ('se faire', 'elle', 'Présent', 'elle se fait'),
    ('se faire', 'on', 'Présent', 'on se fait'),
    ('se faire', 'nous', 'Présent', 'nous nous faisons'),
    ('se faire', 'vous', 'Présent', 'vous vous faites'),
    ('se faire', 'ils', 'Présent', 'ils se font'),
    ('se faire', 'elles', 'Présent', 'elles se font'),
    ('se demander', 'je', 'Présent', 'je me demande'),
    ('se demander', 'tu', 'Présent', 'tu te demandes'),
    ('se demander', 'il', 'Présent', 'il se demande'),
    ('se demander', 'elle', 'Présent', 'elle se demande'),
    ('se demander', 'on', 'Présent', 'on se demande'),
    ('se demander', 'nous', 'Présent', 'nous nous demandons'),
    ('se demander', 'vous', 'Présent', 'vous vous demandez'),
    ('se demander', 'ils', 'Présent', 'ils se demandent'),
    ('se demander', 'elles', 'Présent', 'elles se demandent'),
    ('se plaindre', 'je', 'Présent', 'je me plains'),
    ('se plaindre', 'tu', 'Présent', 'tu te plains'),
    ('se plaindre', 'il', 'Présent', 'il se plaint'),
    ('se plaindre', 'elle', 'Présent', 'elle se plaint'),
    ('se plaindre', 'on', 'Présent', 'on se plaint'),
    ('se plaindre', 'nous', 'Présent', 'nous nous plaignons'),
    ('se plaindre', 'vous', 'Présent', 'vous vous plaignez'),
    ('se plaindre', 'ils', 'Présent', 'ils se plaignent'),
    ('se plaindre', 'elles', 'Présent', 'elles se plaignent'),
    ('se voir', 'je', 'Présent', 'je me vois'),
    ('se voir', 'tu', 'Présent', 'tu te vois'),
    ('se voir', 'il', 'Présent', 'il se voit'),
    ('se voir', 'elle', 'Présent', 'elle se voit'),
    ('se voir', 'on', 'Présent', 'on se voit'),
    ('se voir', 'nous', 'Présent', 'nous nous voyons'),
    ('se voir', 'vous', 'Présent', 'vous vous voyez'),
    ('se voir', 'ils', 'Présent', 'ils se voient'),
    ('se voir', 'elles', 'Présent', 'elles se voient'),
    ('s’imaginer', 'je', 'Présent', 'je m''imagine'),
    ('s’imaginer', 'tu', 'Présent', 'tu t''imagines'),
    ('s’imaginer', 'il', 'Présent', 'il s''imagine'),
    ('s’imaginer', 'elle', 'Présent', 'elle s''imagine'),
    ('s’imaginer', 'on', 'Présent', 'on s''imagine'),
    ('s’imaginer', 'nous', 'Présent', 'nous nous imaginons'),
    ('s’imaginer', 'vous', 'Présent', 'vous vous imaginez'),
    ('s’imaginer', 'ils', 'Présent', 'ils s''imaginent'),
    ('s’imaginer', 'elles', 'Présent', 'elles s''imaginent'),
    ('s’efforcer', 'je', 'Présent', 'je m''efforce'),
    ('s’efforcer', 'tu', 'Présent', 'tu t''efforces'),
    ('s’efforcer', 'il', 'Présent', 'il s''efforce'),
    ('s’efforcer', 'elle', 'Présent', 'elle s''efforce'),
    ('s’efforcer', 'on', 'Présent', 'on s''efforce'),
    ('s’efforcer', 'nous', 'Présent', 'nous nous efforçons'),
    ('s’efforcer', 'vous', 'Présent', 'vous vous efforcez'),
    ('s’efforcer', 'ils', 'Présent', 'ils s''efforcent'),
    ('s’efforcer', 'elles', 'Présent', 'elles s''efforcent'),
    ('s’évanouir', 'je', 'Présent', 'je m''évanouis'),
    ('s’évanouir', 'tu', 'Présent', 'tu t''évanouis'),
    ('s’évanouir', 'il', 'Présent', 'il s''évanouit'),
    ('s’évanouir', 'elle', 'Présent', 'elle s''évanouit'),
    ('s’évanouir', 'on', 'Présent', 'on s''évanouit'),
    ('s’évanouir', 'nous', 'Présent', 'nous nous évanouissons'),
    ('s’évanouir', 'vous', 'Présent', 'vous vous évanouissez'),
    ('s’évanouir', 'ils', 'Présent', 'ils s''évanouissent'),
    ('s’évanouir', 'elles', 'Présent', 'elles s''évanouissent'),
    ('s’indigner', 'je', 'Présent', 'je m''indigne'),
    ('s’indigner', 'tu', 'Présent', 'tu t''indignes'),
    ('s’indigner', 'il', 'Présent', 'il s''indigne'),
    ('s’indigner', 'elle', 'Présent', 'elle s''indigne'),
    ('s’indigner', 'on', 'Présent', 'on s''indigne'),
    ('s’indigner', 'nous', 'Présent', 'nous nous indignons'),
    ('s’indigner', 'vous', 'Présent', 'vous vous indignez'),
    ('s’indigner', 'ils', 'Présent', 'ils s''indignent'),
    ('s’indigner', 'elles', 'Présent', 'elles s''indignent'),
    ('s’épanouir', 'je', 'Présent', 'je m''épanouis'),
    ('s’épanouir', 'tu', 'Présent', 'tu t''épanouis'),
    ('s’épanouir', 'il', 'Présent', 'il s''épanouit'),
    ('s’épanouir', 'elle', 'Présent', 'elle s''épanouit'),
    ('s’épanouir', 'on', 'Présent', 'on s''épanouit'),
    ('s’épanouir', 'nous', 'Présent', 'nous nous épanouissons'),
    ('s’épanouir', 'vous', 'Présent', 'vous vous épanouissez'),
    ('s’épanouir', 'ils', 'Présent', 'ils s''épanouissent'),
    ('s’épanouir', 'elles', 'Présent', 'elles s''épanouissent'),
    ('s’en sortir', 'je', 'Présent', 'je m''en sors'),
    ('s’en sortir', 'tu', 'Présent', 'tu t''en sors'),
    ('s’en sortir', 'il', 'Présent', 'il s''en sort'),
    ('s’en sortir', 'elle', 'Présent', 'elle s''en sort'),
    ('s’en sortir', 'on', 'Présent', 'on s''en sort'),
    ('s’en sortir', 'nous', 'Présent', 'nous nous en sortons'),
    ('s’en sortir', 'vous', 'Présent', 'vous vous en sortez'),
    ('s’en sortir', 'ils', 'Présent', 'ils s''en sortent'),
    ('s’en sortir', 'elles', 'Présent', 'elles s''en sortent'),
    ('s’attendre', 'je', 'Présent', 'je m''attends'),
    ('s’attendre', 'tu', 'Présent', 'tu t''attends'),
    ('s’attendre', 'il', 'Présent', 'il s''attend'),
    ('s’attendre', 'elle', 'Présent', 'elle s''attend'),
    ('s’attendre', 'on', 'Présent', 'on s''attend'),
    ('s’attendre', 'nous', 'Présent', 'nous nous attendons'),
    ('s’attendre', 'vous', 'Présent', 'vous vous attendez'),
    ('s’attendre', 'ils', 'Présent', 'ils s''attendent'),
    ('s’attendre', 'elles', 'Présent', 'elles s''attendent'),
    ('s’interroger', 'je', 'Présent', 'je m''interroge'),
    ('s’interroger', 'tu', 'Présent', 'tu t''interroges'),
    ('s’interroger', 'il', 'Présent', 'il s''interroge'),
    ('s’interroger', 'elle', 'Présent', 'elle s''interroge'),
    ('s’interroger', 'on', 'Présent', 'on s''interroge'),
    ('s’interroger', 'nous', 'Présent', 'nous nous interrogeons'),
    ('s’interroger', 'vous', 'Présent', 'vous vous interrogez'),
    ('s’interroger', 'ils', 'Présent', 'ils s''interrogent'),
    ('s’interroger', 'elles', 'Présent', 'elles s''interrogent'),
    ('se heurter', 'je', 'Présent', 'je me heurte'),
    ('se heurter', 'tu', 'Présent', 'tu te heurtes'),
    ('se heurter', 'il', 'Présent', 'il se heurte'),
    ('se heurter', 'elle', 'Présent', 'elle se heurte'),
    ('se heurter', 'on', 'Présent', 'on se heurte'),
    ('se heurter', 'nous', 'Présent', 'nous nous heurtons'),
    ('se heurter', 'vous', 'Présent', 'vous vous heurtez'),
    ('se heurter', 'ils', 'Présent', 'ils se heurtent'),
    ('se heurter', 'elles', 'Présent', 'elles se heurtent'),
    ('se méfier', 'je', 'Présent', 'je me méfie'),
    ('se méfier', 'tu', 'Présent', 'tu te méfies'),
    ('se méfier', 'il', 'Présent', 'il se méfie'),
    ('se méfier', 'elle', 'Présent', 'elle se méfie'),
    ('se méfier', 'on', 'Présent', 'on se méfie'),
    ('se méfier', 'nous', 'Présent', 'nous nous méfions'),
    ('se méfier', 'vous', 'Présent', 'vous vous méfiez'),
    ('se méfier', 'ils', 'Présent', 'ils se méfient'),
    ('se méfier', 'elles', 'Présent', 'elles se méfient'),
    ('se replier sur soi-même', 'je', 'Présent', 'je me replie sur moi-même'),
    ('se replier sur soi-même', 'tu', 'Présent', 'tu te replies sur toi-même'),
    ('se replier sur soi-même', 'il', 'Présent', 'il se replie sur lui-même'),
    ('se replier sur soi-même', 'elle', 'Présent', 'elle se replie sur elle-même'),
    ('se replier sur soi-même', 'on', 'Présent', 'on se replie sur soi-même'),
    ('se replier sur soi-même', 'nous', 'Présent', 'nous nous replions sur nous-mêmes'),
    ('se replier sur soi-même', 'vous', 'Présent', 'vous vous repliez sur vous-mêmes'),
    ('se replier sur soi-même', 'ils', 'Présent', 'ils se replient sur eux-mêmes'),
    ('se replier sur soi-même', 'elles', 'Présent', 'elles se replient sur elles-mêmes'),
    ('se raviser', 'je', 'Présent', 'je me ravise'),
    ('se raviser', 'tu', 'Présent', 'tu te ravises'),
    ('se raviser', 'il', 'Présent', 'il se ravise'),
    ('se raviser', 'elle', 'Présent', 'elle se ravise'),
    ('se raviser', 'on', 'Présent', 'on se ravise'),
    ('se raviser', 'nous', 'Présent', 'nous nous ravisons'),
    ('se raviser', 'vous', 'Présent', 'vous vous ravisez'),
    ('se raviser', 'ils', 'Présent', 'ils se ravisent'),
    ('se raviser', 'elles', 'Présent', 'elles se ravisent'),
    ('se débrouiller', 'je', 'Présent', 'je me débrouille'),
    ('se débrouiller', 'tu', 'Présent', 'tu te débrouilles'),
    ('se débrouiller', 'il', 'Présent', 'il se débrouille'),
    ('se débrouiller', 'elle', 'Présent', 'elle se débrouille'),
    ('se débrouiller', 'on', 'Présent', 'on se débrouille'),
    ('se débrouiller', 'nous', 'Présent', 'nous nous débrouillons'),
    ('se débrouiller', 'vous', 'Présent', 'vous vous débrouillez'),
    ('se débrouiller', 'ils', 'Présent', 'ils se débrouillent'),
    ('se débrouiller', 'elles', 'Présent', 'elles se débrouillent'),
    ('se réconcilier', 'je', 'Présent', 'je me réconcilie'),
    ('se réconcilier', 'tu', 'Présent', 'tu te réconcilies'),
    ('se réconcilier', 'il', 'Présent', 'il se réconcilie'),
    ('se réconcilier', 'elle', 'Présent', 'elle se réconcilie'),
    ('se réconcilier', 'on', 'Présent', 'on se réconcilie'),
    ('se réconcilier', 'nous', 'Présent', 'nous nous réconcilions'),
    ('se réconcilier', 'vous', 'Présent', 'vous vous réconciliez'),
    ('se réconcilier', 'ils', 'Présent', 'ils se réconcilient'),
    ('se réconcilier', 'elles', 'Présent', 'elles se réconcilient'),
    ('se précipiter', 'je', 'Présent', 'je me précipite'),
    ('se précipiter', 'tu', 'Présent', 'tu te précipites'),
    ('se précipiter', 'il', 'Présent', 'il se précipite'),
    ('se précipiter', 'elle', 'Présent', 'elle se précipite'),
    ('se précipiter', 'on', 'Présent', 'on se précipite'),
    ('se précipiter', 'nous', 'Présent', 'nous nous précipitons'),
    ('se précipiter', 'vous', 'Présent', 'vous vous précipitez'),
    ('se précipiter', 'ils', 'Présent', 'ils se précipitent'),
    ('se précipiter', 'elles', 'Présent', 'elles se précipitent'),
    ('se figurer', 'je', 'Présent', 'je me figure'),
    ('se figurer', 'tu', 'Présent', 'tu te figures'),
    ('se figurer', 'il', 'Présent', 'il se figure'),
    ('se figurer', 'elle', 'Présent', 'elle se figure'),
    ('se figurer', 'on', 'Présent', 'on se figure'),
    ('se figurer', 'nous', 'Présent', 'nous nous figurons'),
    ('se figurer', 'vous', 'Présent', 'vous vous figurez'),
    ('se figurer', 'ils', 'Présent', 'ils se figurent'),
    ('se figurer', 'elles', 'Présent', 'elles se figurent'),
    ('acheter', 'je', 'Présent', 'j''achète'),
    ('acheter', 'tu', 'Présent', 'tu achètes'),
    ('acheter', 'il', 'Présent', 'il achète'),
    ('acheter', 'elle', 'Présent', 'elle achète'),
    ('acheter', 'on', 'Présent', 'on achète'),
    ('acheter', 'nous', 'Présent', 'nous achetons'),
    ('acheter', 'vous', 'Présent', 'vous achetez'),
    ('acheter', 'ils', 'Présent', 'ils achètent'),
    ('acheter', 'elles', 'Présent', 'elles achètent'),
    ('aller', 'je', 'Présent', 'je vais'),
    ('aller', 'tu', 'Présent', 'tu vas'),
    ('aller', 'il', 'Présent', 'il va'),
    ('aller', 'elle', 'Présent', 'elle va'),
    ('aller', 'on', 'Présent', 'on va'),
    ('aller', 'nous', 'Présent', 'nous allons'),
    ('aller', 'vous', 'Présent', 'vous allez'),
    ('aller', 'ils', 'Présent', 'ils vont'),
    ('aller', 'elles', 'Présent', 'elles vont'),
    ('appeler', 'je', 'Présent', 'j''appelle'),
    ('appeler', 'tu', 'Présent', 'tu appelles'),
    ('appeler', 'il', 'Présent', 'il appelle'),
    ('appeler', 'elle', 'Présent', 'elle appelle'),
    ('appeler', 'on', 'Présent', 'on appelle'),
    ('appeler', 'nous', 'Présent', 'nous appelons'),
    ('appeler', 'vous', 'Présent', 'vous appelez'),
    ('appeler', 'ils', 'Présent', 'ils appellent'),
    ('appeler', 'elles', 'Présent', 'elles appellent'),
    ('attendre', 'je', 'Présent', 'j''attends'),
    ('attendre', 'tu', 'Présent', 'tu attends'),
    ('attendre', 'il', 'Présent', 'il attend'),
    ('attendre', 'elle', 'Présent', 'elle attend'),
    ('attendre', 'on', 'Présent', 'on attend'),
    ('attendre', 'nous', 'Présent', 'nous attendons'),
    ('attendre', 'vous', 'Présent', 'vous attendez'),
    ('attendre', 'ils', 'Présent', 'ils attendent'),
    ('attendre', 'elles', 'Présent', 'elles attendent'),
    ('courir', 'je', 'Présent', 'je cours'),
    ('courir', 'tu', 'Présent', 'tu cours'),
    ('courir', 'il', 'Présent', 'il court'),
    ('courir', 'elle', 'Présent', 'elle court'),
    ('courir', 'on', 'Présent', 'on court'),
    ('courir', 'nous', 'Présent', 'nous courons'),
    ('courir', 'vous', 'Présent', 'vous courez'),
    ('courir', 'ils', 'Présent', 'ils courent'),
    ('courir', 'elles', 'Présent', 'elles courent'),
    ('descendre', 'je', 'Présent', 'je descends'),
    ('descendre', 'tu', 'Présent', 'tu descends'),
    ('descendre', 'il', 'Présent', 'il descend'),
    ('descendre', 'elle', 'Présent', 'elle descend'),
    ('descendre', 'on', 'Présent', 'on descend'),
    ('descendre', 'nous', 'Présent', 'nous descendons'),
    ('descendre', 'vous', 'Présent', 'vous descendez'),
    ('descendre', 'ils', 'Présent', 'ils descendent'),
    ('descendre', 'elles', 'Présent', 'elles descendent'),
    ('dormir', 'je', 'Présent', 'je dors'),
    ('dormir', 'tu', 'Présent', 'tu dors'),
    ('dormir', 'il', 'Présent', 'il dort'),
    ('dormir', 'elle', 'Présent', 'elle dort'),
    ('dormir', 'on', 'Présent', 'on dort'),
    ('dormir', 'nous', 'Présent', 'nous dormons'),
    ('dormir', 'vous', 'Présent', 'vous dormez'),
    ('dormir', 'ils', 'Présent', 'ils dorment'),
    ('dormir', 'elles', 'Présent', 'elles dorment'),
    ('entendre', 'je', 'Présent', 'j''entends'),
    ('entendre', 'tu', 'Présent', 'tu entends'),
    ('entendre', 'il', 'Présent', 'il entend'),
    ('entendre', 'elle', 'Présent', 'elle entend'),
    ('entendre', 'on', 'Présent', 'on entend'),
    ('entendre', 'nous', 'Présent', 'nous entendons'),
    ('entendre', 'vous', 'Présent', 'vous entendez'),
    ('entendre', 'ils', 'Présent', 'ils entendent'),
    ('entendre', 'elles', 'Présent', 'elles entendent'),
    ('envoyer', 'je', 'Présent', 'j''envoie'),
    ('envoyer', 'tu', 'Présent', 'tu envoies'),
    ('envoyer', 'il', 'Présent', 'il envoie'),
    ('envoyer', 'elle', 'Présent', 'elle envoie'),
    ('envoyer', 'on', 'Présent', 'on envoie'),
    ('envoyer', 'nous', 'Présent', 'nous envoyons'),
    ('envoyer', 'vous', 'Présent', 'vous envoyez'),
    ('envoyer', 'ils', 'Présent', 'ils envoient'),
    ('envoyer', 'elles', 'Présent', 'elles envoient'),
    ('jeter', 'je', 'Présent', 'je jette'),
    ('jeter', 'tu', 'Présent', 'tu jettes'),
    ('jeter', 'il', 'Présent', 'il jette'),
    ('jeter', 'elle', 'Présent', 'elle jette'),
    ('jeter', 'on', 'Présent', 'on jette'),
    ('jeter', 'nous', 'Présent', 'nous jetons'),
    ('jeter', 'vous', 'Présent', 'vous jetez'),
    ('jeter', 'ils', 'Présent', 'ils jettent'),
    ('jeter', 'elles', 'Présent', 'elles jettent'),
    ('partir', 'je', 'Présent', 'je pars'),
    ('partir', 'tu', 'Présent', 'tu pars'),
    ('partir', 'il', 'Présent', 'il part'),
    ('partir', 'elle', 'Présent', 'elle part'),
    ('partir', 'on', 'Présent', 'on part'),
    ('partir', 'nous', 'Présent', 'nous partons'),
    ('partir', 'vous', 'Présent', 'vous partez'),
    ('partir', 'ils', 'Présent', 'ils partent'),
    ('partir', 'elles', 'Présent', 'elles partent'),
    ('payer', 'je', 'Présent', 'je paye'),
    ('payer', 'tu', 'Présent', 'tu payes'),
    ('payer', 'il', 'Présent', 'il paye'),
    ('payer', 'elle', 'Présent', 'elle paye'),
    ('payer', 'on', 'Présent', 'on paye'),
    ('payer', 'nous', 'Présent', 'nous payons'),
    ('payer', 'vous', 'Présent', 'vous payez'),
    ('payer', 'ils', 'Présent', 'ils payent'),
    ('payer', 'elles', 'Présent', 'elles payent'),
    ('perdre', 'je', 'Présent', 'je perds'),
    ('perdre', 'tu', 'Présent', 'tu perds'),
    ('perdre', 'il', 'Présent', 'il perd'),
    ('perdre', 'elle', 'Présent', 'elle perd'),
    ('perdre', 'on', 'Présent', 'on perd'),
    ('perdre', 'nous', 'Présent', 'nous perdons'),
    ('perdre', 'vous', 'Présent', 'vous perdez'),
    ('perdre', 'ils', 'Présent', 'ils perdent'),
    ('perdre', 'elles', 'Présent', 'elles perdent'),
    ('préférer', 'je', 'Présent', 'je préfère'),
    ('préférer', 'tu', 'Présent', 'tu préfères'),
    ('préférer', 'il', 'Présent', 'il préfère'),
    ('préférer', 'elle', 'Présent', 'elle préfère'),
    ('préférer', 'on', 'Présent', 'on préfère'),
    ('préférer', 'nous', 'Présent', 'nous préférons'),
    ('préférer', 'vous', 'Présent', 'vous préférez'),
    ('préférer', 'ils', 'Présent', 'ils préfèrent'),
    ('préférer', 'elles', 'Présent', 'elles préfèrent'),
    ('répondre', 'je', 'Présent', 'je réponds'),
    ('répondre', 'tu', 'Présent', 'tu réponds'),
    ('répondre', 'il', 'Présent', 'il répond'),
    ('répondre', 'elle', 'Présent', 'elle répond'),
    ('répondre', 'on', 'Présent', 'on répond'),
    ('répondre', 'nous', 'Présent', 'nous répondons'),
    ('répondre', 'vous', 'Présent', 'vous répondez'),
    ('répondre', 'ils', 'Présent', 'ils répondent'),
    ('répondre', 'elles', 'Présent', 'elles répondent'),
    ('servir', 'je', 'Présent', 'je sers'),
    ('servir', 'tu', 'Présent', 'tu sers'),
    ('servir', 'il', 'Présent', 'il sert'),
    ('servir', 'elle', 'Présent', 'elle sert'),
    ('servir', 'on', 'Présent', 'on sert'),
    ('servir', 'nous', 'Présent', 'nous servons'),
    ('servir', 'vous', 'Présent', 'vous servez'),
    ('servir', 'ils', 'Présent', 'ils servent'),
    ('servir', 'elles', 'Présent', 'elles servent'),
    ('sortir', 'je', 'Présent', 'je sors'),
    ('sortir', 'tu', 'Présent', 'tu sors'),
    ('sortir', 'il', 'Présent', 'il sort'),
    ('sortir', 'elle', 'Présent', 'elle sort'),
    ('sortir', 'on', 'Présent', 'on sort'),
    ('sortir', 'nous', 'Présent', 'nous sortons'),
    ('sortir', 'vous', 'Présent', 'vous sortez'),
    ('sortir', 'ils', 'Présent', 'ils sortent'),
    ('sortir', 'elles', 'Présent', 'elles sortent'),
    ('vendre', 'je', 'Présent', 'je vends'),
    ('vendre', 'tu', 'Présent', 'tu vends'),
    ('vendre', 'il', 'Présent', 'il vend'),
    ('vendre', 'elle', 'Présent', 'elle vend'),
    ('vendre', 'on', 'Présent', 'on vend'),
    ('vendre', 'nous', 'Présent', 'nous vendons'),
    ('vendre', 'vous', 'Présent', 'vous vendez'),
    ('vendre', 'ils', 'Présent', 'ils vendent'),
    ('vendre', 'elles', 'Présent', 'elles vendent')
) AS c("verb_name", "subject_name", "tense_name", "text")
JOIN "Verb" v ON v."name" = c."verb_name"
JOIN "Subject" s ON s."name" = c."subject_name"
JOIN "Tense" t ON t."name" = c."tense_name"
ON CONFLICT ("verb_id", "subject_id", "tense_id")
DO UPDATE SET "text" = EXCLUDED."text";
