INSERT INTO "Conjugation" ("verb_id", "subject_id", "tense_id", "text")
SELECT v."id", s."id", t."id", c."text"
FROM (
  VALUES
    ('être', 'je', 'Imparfait', 'j''étais'),
    ('être', 'tu', 'Imparfait', 'tu étais'),
    ('être', 'il', 'Imparfait', 'il était'),
    ('être', 'elle', 'Imparfait', 'elle était'),
    ('être', 'on', 'Imparfait', 'on était'),
    ('être', 'nous', 'Imparfait', 'nous étions'),
    ('être', 'vous', 'Imparfait', 'vous étiez'),
    ('être', 'ils', 'Imparfait', 'ils étaient'),
    ('être', 'elles', 'Imparfait', 'elles étaient'),
    ('avoir', 'je', 'Imparfait', 'j''avais'),
    ('avoir', 'tu', 'Imparfait', 'tu avais'),
    ('avoir', 'il', 'Imparfait', 'il avait'),
    ('avoir', 'elle', 'Imparfait', 'elle avait'),
    ('avoir', 'on', 'Imparfait', 'on avait'),
    ('avoir', 'nous', 'Imparfait', 'nous avions'),
    ('avoir', 'vous', 'Imparfait', 'vous aviez'),
    ('avoir', 'ils', 'Imparfait', 'ils avaient'),
    ('avoir', 'elles', 'Imparfait', 'elles avaient'),
    ('faire', 'je', 'Imparfait', 'je faisais'),
    ('faire', 'tu', 'Imparfait', 'tu faisais'),
    ('faire', 'il', 'Imparfait', 'il faisait'),
    ('faire', 'elle', 'Imparfait', 'elle faisait'),
    ('faire', 'on', 'Imparfait', 'on faisait'),
    ('faire', 'nous', 'Imparfait', 'nous faisions'),
    ('faire', 'vous', 'Imparfait', 'vous faisiez'),
    ('faire', 'ils', 'Imparfait', 'ils faisaient'),
    ('faire', 'elles', 'Imparfait', 'elles faisaient'),
    ('mettre', 'je', 'Imparfait', 'je mettais'),
    ('mettre', 'tu', 'Imparfait', 'tu mettais'),
    ('mettre', 'il', 'Imparfait', 'il mettait'),
    ('mettre', 'elle', 'Imparfait', 'elle mettait'),
    ('mettre', 'on', 'Imparfait', 'on mettait'),
    ('mettre', 'nous', 'Imparfait', 'nous mettions'),
    ('mettre', 'vous', 'Imparfait', 'vous mettiez'),
    ('mettre', 'ils', 'Imparfait', 'ils mettaient'),
    ('mettre', 'elles', 'Imparfait', 'elles mettaient'),
    ('prendre', 'je', 'Imparfait', 'je prenais'),
    ('prendre', 'tu', 'Imparfait', 'tu prenais'),
    ('prendre', 'il', 'Imparfait', 'il prenait'),
    ('prendre', 'elle', 'Imparfait', 'elle prenait'),
    ('prendre', 'on', 'Imparfait', 'on prenait'),
    ('prendre', 'nous', 'Imparfait', 'nous prenions'),
    ('prendre', 'vous', 'Imparfait', 'vous preniez'),
    ('prendre', 'ils', 'Imparfait', 'ils prenaient'),
    ('prendre', 'elles', 'Imparfait', 'elles prenaient'),
    ('dire', 'je', 'Imparfait', 'je disais'),
    ('dire', 'tu', 'Imparfait', 'tu disais'),
    ('dire', 'il', 'Imparfait', 'il disait'),
    ('dire', 'elle', 'Imparfait', 'elle disait'),
    ('dire', 'on', 'Imparfait', 'on disait'),
    ('dire', 'nous', 'Imparfait', 'nous disions'),
    ('dire', 'vous', 'Imparfait', 'vous disiez'),
    ('dire', 'ils', 'Imparfait', 'ils disaient'),
    ('dire', 'elles', 'Imparfait', 'elles disaient'),
    ('écrire', 'je', 'Imparfait', 'j''écrivais'),
    ('écrire', 'tu', 'Imparfait', 'tu écrivais'),
    ('écrire', 'il', 'Imparfait', 'il écrivait'),
    ('écrire', 'elle', 'Imparfait', 'elle écrivait'),
    ('écrire', 'on', 'Imparfait', 'on écrivait'),
    ('écrire', 'nous', 'Imparfait', 'nous écrivions'),
    ('écrire', 'vous', 'Imparfait', 'vous écriviez'),
    ('écrire', 'ils', 'Imparfait', 'ils écrivaient'),
    ('écrire', 'elles', 'Imparfait', 'elles écrivaient'),
    ('voir', 'je', 'Imparfait', 'je voyais'),
    ('voir', 'tu', 'Imparfait', 'tu voyais'),
    ('voir', 'il', 'Imparfait', 'il voyait'),
    ('voir', 'elle', 'Imparfait', 'elle voyait'),
    ('voir', 'on', 'Imparfait', 'on voyait'),
    ('voir', 'nous', 'Imparfait', 'nous voyions'),
    ('voir', 'vous', 'Imparfait', 'vous voyiez'),
    ('voir', 'ils', 'Imparfait', 'ils voyaient'),
    ('voir', 'elles', 'Imparfait', 'elles voyaient'),
    ('pouvoir', 'je', 'Imparfait', 'je pouvais'),
    ('pouvoir', 'tu', 'Imparfait', 'tu pouvais'),
    ('pouvoir', 'il', 'Imparfait', 'il pouvait'),
    ('pouvoir', 'elle', 'Imparfait', 'elle pouvait'),
    ('pouvoir', 'on', 'Imparfait', 'on pouvait'),
    ('pouvoir', 'nous', 'Imparfait', 'nous pouvions'),
    ('pouvoir', 'vous', 'Imparfait', 'vous pouviez'),
    ('pouvoir', 'ils', 'Imparfait', 'ils pouvaient'),
    ('pouvoir', 'elles', 'Imparfait', 'elles pouvaient'),
    ('vouloir', 'je', 'Imparfait', 'je voulais'),
    ('vouloir', 'tu', 'Imparfait', 'tu voulais'),
    ('vouloir', 'il', 'Imparfait', 'il voulait'),
    ('vouloir', 'elle', 'Imparfait', 'elle voulait'),
    ('vouloir', 'on', 'Imparfait', 'on voulait'),
    ('vouloir', 'nous', 'Imparfait', 'nous voulions'),
    ('vouloir', 'vous', 'Imparfait', 'vous vouliez'),
    ('vouloir', 'ils', 'Imparfait', 'ils voulaient'),
    ('vouloir', 'elles', 'Imparfait', 'elles voulaient'),
    ('savoir', 'je', 'Imparfait', 'je savais'),
    ('savoir', 'tu', 'Imparfait', 'tu savais'),
    ('savoir', 'il', 'Imparfait', 'il savait'),
    ('savoir', 'elle', 'Imparfait', 'elle savait'),
    ('savoir', 'on', 'Imparfait', 'on savait'),
    ('savoir', 'nous', 'Imparfait', 'nous savions'),
    ('savoir', 'vous', 'Imparfait', 'vous saviez'),
    ('savoir', 'ils', 'Imparfait', 'ils savaient'),
    ('savoir', 'elles', 'Imparfait', 'elles savaient'),
    ('connaître', 'je', 'Imparfait', 'je connaissais'),
    ('connaître', 'tu', 'Imparfait', 'tu connaissais'),
    ('connaître', 'il', 'Imparfait', 'il connaissait'),
    ('connaître', 'elle', 'Imparfait', 'elle connaissait'),
    ('connaître', 'on', 'Imparfait', 'on connaissait'),
    ('connaître', 'nous', 'Imparfait', 'nous connaissions'),
    ('connaître', 'vous', 'Imparfait', 'vous connaissiez'),
    ('connaître', 'ils', 'Imparfait', 'ils connaissaient'),
    ('connaître', 'elles', 'Imparfait', 'elles connaissaient'),
    ('venir', 'je', 'Imparfait', 'je venais'),
    ('venir', 'tu', 'Imparfait', 'tu venais'),
    ('venir', 'il', 'Imparfait', 'il venait'),
    ('venir', 'elle', 'Imparfait', 'elle venait'),
    ('venir', 'on', 'Imparfait', 'on venait'),
    ('venir', 'nous', 'Imparfait', 'nous venions'),
    ('venir', 'vous', 'Imparfait', 'vous veniez'),
    ('venir', 'ils', 'Imparfait', 'ils venaient'),
    ('venir', 'elles', 'Imparfait', 'elles venaient'),
    ('devoir', 'je', 'Imparfait', 'je devais'),
    ('devoir', 'tu', 'Imparfait', 'tu devais'),
    ('devoir', 'il', 'Imparfait', 'il devait'),
    ('devoir', 'elle', 'Imparfait', 'elle devait'),
    ('devoir', 'on', 'Imparfait', 'on devait'),
    ('devoir', 'nous', 'Imparfait', 'nous devions'),
    ('devoir', 'vous', 'Imparfait', 'vous deviez'),
    ('devoir', 'ils', 'Imparfait', 'ils devaient'),
    ('devoir', 'elles', 'Imparfait', 'elles devaient'),
    ('croire', 'je', 'Imparfait', 'je croyais'),
    ('croire', 'tu', 'Imparfait', 'tu croyais'),
    ('croire', 'il', 'Imparfait', 'il croyait'),
    ('croire', 'elle', 'Imparfait', 'elle croyait'),
    ('croire', 'on', 'Imparfait', 'on croyait'),
    ('croire', 'nous', 'Imparfait', 'nous croyions'),
    ('croire', 'vous', 'Imparfait', 'vous croyiez'),
    ('croire', 'ils', 'Imparfait', 'ils croyaient'),
    ('croire', 'elles', 'Imparfait', 'elles croyaient'),
    ('boire', 'je', 'Imparfait', 'je buvais'),
    ('boire', 'tu', 'Imparfait', 'tu buvais'),
    ('boire', 'il', 'Imparfait', 'il buvait'),
    ('boire', 'elle', 'Imparfait', 'elle buvait'),
    ('boire', 'on', 'Imparfait', 'on buvait'),
    ('boire', 'nous', 'Imparfait', 'nous buvions'),
    ('boire', 'vous', 'Imparfait', 'vous buviez'),
    ('boire', 'ils', 'Imparfait', 'ils buvaient'),
    ('boire', 'elles', 'Imparfait', 'elles buvaient'),
    ('lire', 'je', 'Imparfait', 'je lisais'),
    ('lire', 'tu', 'Imparfait', 'tu lisais'),
    ('lire', 'il', 'Imparfait', 'il lisait'),
    ('lire', 'elle', 'Imparfait', 'elle lisait'),
    ('lire', 'on', 'Imparfait', 'on lisait'),
    ('lire', 'nous', 'Imparfait', 'nous lisions'),
    ('lire', 'vous', 'Imparfait', 'vous lisiez'),
    ('lire', 'ils', 'Imparfait', 'ils lisaient'),
    ('lire', 'elles', 'Imparfait', 'elles lisaient'),
    ('vivre', 'je', 'Imparfait', 'je vivais'),
    ('vivre', 'tu', 'Imparfait', 'tu vivais'),
    ('vivre', 'il', 'Imparfait', 'il vivait'),
    ('vivre', 'elle', 'Imparfait', 'elle vivait'),
    ('vivre', 'on', 'Imparfait', 'on vivait'),
    ('vivre', 'nous', 'Imparfait', 'nous vivions'),
    ('vivre', 'vous', 'Imparfait', 'vous viviez'),
    ('vivre', 'ils', 'Imparfait', 'ils vivaient'),
    ('vivre', 'elles', 'Imparfait', 'elles vivaient'),
    ('recevoir', 'je', 'Imparfait', 'je recevais'),
    ('recevoir', 'tu', 'Imparfait', 'tu recevais'),
    ('recevoir', 'il', 'Imparfait', 'il recevait'),
    ('recevoir', 'elle', 'Imparfait', 'elle recevait'),
    ('recevoir', 'on', 'Imparfait', 'on recevait'),
    ('recevoir', 'nous', 'Imparfait', 'nous recevions'),
    ('recevoir', 'vous', 'Imparfait', 'vous receviez'),
    ('recevoir', 'ils', 'Imparfait', 'ils recevaient'),
    ('recevoir', 'elles', 'Imparfait', 'elles recevaient'),
    ('ouvrir', 'je', 'Imparfait', 'j''ouvrais'),
    ('ouvrir', 'tu', 'Imparfait', 'tu ouvrais'),
    ('ouvrir', 'il', 'Imparfait', 'il ouvrait'),
    ('ouvrir', 'elle', 'Imparfait', 'elle ouvrait'),
    ('ouvrir', 'on', 'Imparfait', 'on ouvrait'),
    ('ouvrir', 'nous', 'Imparfait', 'nous ouvrions'),
    ('ouvrir', 'vous', 'Imparfait', 'vous ouvriez'),
    ('ouvrir', 'ils', 'Imparfait', 'ils ouvraient'),
    ('ouvrir', 'elles', 'Imparfait', 'elles ouvraient'),
    ('offrir', 'je', 'Imparfait', 'j''offrais'),
    ('offrir', 'tu', 'Imparfait', 'tu offrais'),
    ('offrir', 'il', 'Imparfait', 'il offrait'),
    ('offrir', 'elle', 'Imparfait', 'elle offrait'),
    ('offrir', 'on', 'Imparfait', 'on offrait'),
    ('offrir', 'nous', 'Imparfait', 'nous offrions'),
    ('offrir', 'vous', 'Imparfait', 'vous offriez'),
    ('offrir', 'ils', 'Imparfait', 'ils offraient'),
    ('offrir', 'elles', 'Imparfait', 'elles offraient'),
    ('naître', 'je', 'Imparfait', 'je naissais'),
    ('naître', 'tu', 'Imparfait', 'tu naissais'),
    ('naître', 'il', 'Imparfait', 'il naissait'),
    ('naître', 'elle', 'Imparfait', 'elle naissait'),
    ('naître', 'on', 'Imparfait', 'on naissait'),
    ('naître', 'nous', 'Imparfait', 'nous naissions'),
    ('naître', 'vous', 'Imparfait', 'vous naissiez'),
    ('naître', 'ils', 'Imparfait', 'ils naissaient'),
    ('naître', 'elles', 'Imparfait', 'elles naissaient'),
    ('mourir', 'je', 'Imparfait', 'je mourais'),
    ('mourir', 'tu', 'Imparfait', 'tu mourais'),
    ('mourir', 'il', 'Imparfait', 'il mourait'),
    ('mourir', 'elle', 'Imparfait', 'elle mourait'),
    ('mourir', 'on', 'Imparfait', 'on mourait'),
    ('mourir', 'nous', 'Imparfait', 'nous mourions'),
    ('mourir', 'vous', 'Imparfait', 'vous mouriez'),
    ('mourir', 'ils', 'Imparfait', 'ils mouraient'),
    ('mourir', 'elles', 'Imparfait', 'elles mouraient'),
    ('tenir', 'je', 'Imparfait', 'je tenais'),
    ('tenir', 'tu', 'Imparfait', 'tu tenais'),
    ('tenir', 'il', 'Imparfait', 'il tenait'),
    ('tenir', 'elle', 'Imparfait', 'elle tenait'),
    ('tenir', 'on', 'Imparfait', 'on tenait'),
    ('tenir', 'nous', 'Imparfait', 'nous tenions'),
    ('tenir', 'vous', 'Imparfait', 'vous teniez'),
    ('tenir', 'ils', 'Imparfait', 'ils tenaient'),
    ('tenir', 'elles', 'Imparfait', 'elles tenaient'),
    ('suivre', 'je', 'Imparfait', 'je suivais'),
    ('suivre', 'tu', 'Imparfait', 'tu suivais'),
    ('suivre', 'il', 'Imparfait', 'il suivait'),
    ('suivre', 'elle', 'Imparfait', 'elle suivait'),
    ('suivre', 'on', 'Imparfait', 'on suivait'),
    ('suivre', 'nous', 'Imparfait', 'nous suivions'),
    ('suivre', 'vous', 'Imparfait', 'vous suiviez'),
    ('suivre', 'ils', 'Imparfait', 'ils suivaient'),
    ('suivre', 'elles', 'Imparfait', 'elles suivaient'),
    ('rire', 'je', 'Imparfait', 'je riais'),
    ('rire', 'tu', 'Imparfait', 'tu riais'),
    ('rire', 'il', 'Imparfait', 'il riait'),
    ('rire', 'elle', 'Imparfait', 'elle riait'),
    ('rire', 'on', 'Imparfait', 'on riait'),
    ('rire', 'nous', 'Imparfait', 'nous riions'),
    ('rire', 'vous', 'Imparfait', 'vous riiez'),
    ('rire', 'ils', 'Imparfait', 'ils riaient'),
    ('rire', 'elles', 'Imparfait', 'elles riaient'),
    ('plaire', 'je', 'Imparfait', 'je plaisais'),
    ('plaire', 'tu', 'Imparfait', 'tu plaisais'),
    ('plaire', 'il', 'Imparfait', 'il plaisait'),
    ('plaire', 'elle', 'Imparfait', 'elle plaisait'),
    ('plaire', 'on', 'Imparfait', 'on plaisait'),
    ('plaire', 'nous', 'Imparfait', 'nous plaisions'),
    ('plaire', 'vous', 'Imparfait', 'vous plaisiez'),
    ('plaire', 'ils', 'Imparfait', 'ils plaisaient'),
    ('plaire', 'elles', 'Imparfait', 'elles plaisaient'),
    ('falloir', 'je', 'Imparfait', 'il fallait'),
    ('falloir', 'tu', 'Imparfait', 'il fallait'),
    ('falloir', 'il', 'Imparfait', 'il fallait'),
    ('falloir', 'elle', 'Imparfait', 'il fallait'),
    ('falloir', 'on', 'Imparfait', 'il fallait'),
    ('falloir', 'nous', 'Imparfait', 'il fallait'),
    ('falloir', 'vous', 'Imparfait', 'il fallait'),
    ('falloir', 'ils', 'Imparfait', 'il fallait'),
    ('falloir', 'elles', 'Imparfait', 'il fallait'),
    ('valoir', 'je', 'Imparfait', 'je valais'),
    ('valoir', 'tu', 'Imparfait', 'tu valais'),
    ('valoir', 'il', 'Imparfait', 'il valait'),
    ('valoir', 'elle', 'Imparfait', 'elle valait'),
    ('valoir', 'on', 'Imparfait', 'on valait'),
    ('valoir', 'nous', 'Imparfait', 'nous valions'),
    ('valoir', 'vous', 'Imparfait', 'vous valiez'),
    ('valoir', 'ils', 'Imparfait', 'ils valaient'),
    ('valoir', 'elles', 'Imparfait', 'elles valaient'),
    ('pleuvoir', 'je', 'Imparfait', 'il pleuvait'),
    ('pleuvoir', 'tu', 'Imparfait', 'il pleuvait'),
    ('pleuvoir', 'il', 'Imparfait', 'il pleuvait'),
    ('pleuvoir', 'elle', 'Imparfait', 'il pleuvait'),
    ('pleuvoir', 'on', 'Imparfait', 'il pleuvait'),
    ('pleuvoir', 'nous', 'Imparfait', 'il pleuvait'),
    ('pleuvoir', 'vous', 'Imparfait', 'il pleuvait'),
    ('pleuvoir', 'ils', 'Imparfait', 'il pleuvait'),
    ('pleuvoir', 'elles', 'Imparfait', 'il pleuvait'),
    ('apprendre', 'je', 'Imparfait', 'j''apprenais'),
    ('apprendre', 'tu', 'Imparfait', 'tu apprenais'),
    ('apprendre', 'il', 'Imparfait', 'il apprenait'),
    ('apprendre', 'elle', 'Imparfait', 'elle apprenait'),
    ('apprendre', 'on', 'Imparfait', 'on apprenait'),
    ('apprendre', 'nous', 'Imparfait', 'nous apprenions'),
    ('apprendre', 'vous', 'Imparfait', 'vous appreniez'),
    ('apprendre', 'ils', 'Imparfait', 'ils apprenaient'),
    ('apprendre', 'elles', 'Imparfait', 'elles apprenaient'),
    ('comprendre', 'je', 'Imparfait', 'je comprenais'),
    ('comprendre', 'tu', 'Imparfait', 'tu comprenais'),
    ('comprendre', 'il', 'Imparfait', 'il comprenait'),
    ('comprendre', 'elle', 'Imparfait', 'elle comprenait'),
    ('comprendre', 'on', 'Imparfait', 'on comprenait'),
    ('comprendre', 'nous', 'Imparfait', 'nous comprenions'),
    ('comprendre', 'vous', 'Imparfait', 'vous compreniez'),
    ('comprendre', 'ils', 'Imparfait', 'ils comprenaient'),
    ('comprendre', 'elles', 'Imparfait', 'elles comprenaient'),
    ('surprendre', 'je', 'Imparfait', 'je surprenais'),
    ('surprendre', 'tu', 'Imparfait', 'tu surprenais'),
    ('surprendre', 'il', 'Imparfait', 'il surprenait'),
    ('surprendre', 'elle', 'Imparfait', 'elle surprenait'),
    ('surprendre', 'on', 'Imparfait', 'on surprenait'),
    ('surprendre', 'nous', 'Imparfait', 'nous surprenions'),
    ('surprendre', 'vous', 'Imparfait', 'vous surpreniez'),
    ('surprendre', 'ils', 'Imparfait', 'ils surprenaient'),
    ('surprendre', 'elles', 'Imparfait', 'elles surprenaient'),
    ('découvrir', 'je', 'Imparfait', 'je découvrais'),
    ('découvrir', 'tu', 'Imparfait', 'tu découvrais'),
    ('découvrir', 'il', 'Imparfait', 'il découvrait'),
    ('découvrir', 'elle', 'Imparfait', 'elle découvrait'),
    ('découvrir', 'on', 'Imparfait', 'on découvrait'),
    ('découvrir', 'nous', 'Imparfait', 'nous découvrions'),
    ('découvrir', 'vous', 'Imparfait', 'vous découvriez'),
    ('découvrir', 'ils', 'Imparfait', 'ils découvraient'),
    ('découvrir', 'elles', 'Imparfait', 'elles découvraient'),
    ('souffrir', 'je', 'Imparfait', 'je souffrais'),
    ('souffrir', 'tu', 'Imparfait', 'tu souffrais'),
    ('souffrir', 'il', 'Imparfait', 'il souffrait'),
    ('souffrir', 'elle', 'Imparfait', 'elle souffrait'),
    ('souffrir', 'on', 'Imparfait', 'on souffrait'),
    ('souffrir', 'nous', 'Imparfait', 'nous souffrions'),
    ('souffrir', 'vous', 'Imparfait', 'vous souffriez'),
    ('souffrir', 'ils', 'Imparfait', 'ils souffraient'),
    ('souffrir', 'elles', 'Imparfait', 'elles souffraient'),
    ('conduire', 'je', 'Imparfait', 'je conduisais'),
    ('conduire', 'tu', 'Imparfait', 'tu conduisais'),
    ('conduire', 'il', 'Imparfait', 'il conduisait'),
    ('conduire', 'elle', 'Imparfait', 'elle conduisait'),
    ('conduire', 'on', 'Imparfait', 'on conduisait'),
    ('conduire', 'nous', 'Imparfait', 'nous conduisions'),
    ('conduire', 'vous', 'Imparfait', 'vous conduisiez'),
    ('conduire', 'ils', 'Imparfait', 'ils conduisaient'),
    ('conduire', 'elles', 'Imparfait', 'elles conduisaient'),
    ('produire', 'je', 'Imparfait', 'je produisais'),
    ('produire', 'tu', 'Imparfait', 'tu produisais'),
    ('produire', 'il', 'Imparfait', 'il produisait'),
    ('produire', 'elle', 'Imparfait', 'elle produisait'),
    ('produire', 'on', 'Imparfait', 'on produisait'),
    ('produire', 'nous', 'Imparfait', 'nous produisions'),
    ('produire', 'vous', 'Imparfait', 'vous produisiez'),
    ('produire', 'ils', 'Imparfait', 'ils produisaient'),
    ('produire', 'elles', 'Imparfait', 'elles produisaient'),
    ('traduire', 'je', 'Imparfait', 'je traduisais'),
    ('traduire', 'tu', 'Imparfait', 'tu traduisais'),
    ('traduire', 'il', 'Imparfait', 'il traduisait'),
    ('traduire', 'elle', 'Imparfait', 'elle traduisait'),
    ('traduire', 'on', 'Imparfait', 'on traduisait'),
    ('traduire', 'nous', 'Imparfait', 'nous traduisions'),
    ('traduire', 'vous', 'Imparfait', 'vous traduisiez'),
    ('traduire', 'ils', 'Imparfait', 'ils traduisaient'),
    ('traduire', 'elles', 'Imparfait', 'elles traduisaient'),
    ('atteindre', 'je', 'Imparfait', 'j''atteignais'),
    ('atteindre', 'tu', 'Imparfait', 'tu atteignais'),
    ('atteindre', 'il', 'Imparfait', 'il atteignait'),
    ('atteindre', 'elle', 'Imparfait', 'elle atteignait'),
    ('atteindre', 'on', 'Imparfait', 'on atteignait'),
    ('atteindre', 'nous', 'Imparfait', 'nous atteignions'),
    ('atteindre', 'vous', 'Imparfait', 'vous atteigniez'),
    ('atteindre', 'ils', 'Imparfait', 'ils atteignaient'),
    ('atteindre', 'elles', 'Imparfait', 'elles atteignaient'),
    ('craindre', 'je', 'Imparfait', 'je craignais'),
    ('craindre', 'tu', 'Imparfait', 'tu craignais'),
    ('craindre', 'il', 'Imparfait', 'il craignait'),
    ('craindre', 'elle', 'Imparfait', 'elle craignait'),
    ('craindre', 'on', 'Imparfait', 'on craignait'),
    ('craindre', 'nous', 'Imparfait', 'nous craignions'),
    ('craindre', 'vous', 'Imparfait', 'vous craigniez'),
    ('craindre', 'ils', 'Imparfait', 'ils craignaient'),
    ('craindre', 'elles', 'Imparfait', 'elles craignaient'),
    ('éteindre', 'je', 'Imparfait', 'j''éteignais'),
    ('éteindre', 'tu', 'Imparfait', 'tu éteignais'),
    ('éteindre', 'il', 'Imparfait', 'il éteignait'),
    ('éteindre', 'elle', 'Imparfait', 'elle éteignait'),
    ('éteindre', 'on', 'Imparfait', 'on éteignait'),
    ('éteindre', 'nous', 'Imparfait', 'nous éteignions'),
    ('éteindre', 'vous', 'Imparfait', 'vous éteigniez'),
    ('éteindre', 'ils', 'Imparfait', 'ils éteignaient'),
    ('éteindre', 'elles', 'Imparfait', 'elles éteignaient'),
    ('joindre', 'je', 'Imparfait', 'je joignais'),
    ('joindre', 'tu', 'Imparfait', 'tu joignais'),
    ('joindre', 'il', 'Imparfait', 'il joignait'),
    ('joindre', 'elle', 'Imparfait', 'elle joignait'),
    ('joindre', 'on', 'Imparfait', 'on joignait'),
    ('joindre', 'nous', 'Imparfait', 'nous joignions'),
    ('joindre', 'vous', 'Imparfait', 'vous joigniez'),
    ('joindre', 'ils', 'Imparfait', 'ils joignaient'),
    ('joindre', 'elles', 'Imparfait', 'elles joignaient'),
    ('peindre', 'je', 'Imparfait', 'je peignais'),
    ('peindre', 'tu', 'Imparfait', 'tu peignais'),
    ('peindre', 'il', 'Imparfait', 'il peignait'),
    ('peindre', 'elle', 'Imparfait', 'elle peignait'),
    ('peindre', 'on', 'Imparfait', 'on peignait'),
    ('peindre', 'nous', 'Imparfait', 'nous peignions'),
    ('peindre', 'vous', 'Imparfait', 'vous peigniez'),
    ('peindre', 'ils', 'Imparfait', 'ils peignaient'),
    ('peindre', 'elles', 'Imparfait', 'elles peignaient'),
    ('clore', 'je', 'Imparfait', 'je closais'),
    ('clore', 'tu', 'Imparfait', 'tu closais'),
    ('clore', 'il', 'Imparfait', 'il closait'),
    ('clore', 'elle', 'Imparfait', 'elle closait'),
    ('clore', 'on', 'Imparfait', 'on closait'),
    ('clore', 'nous', 'Imparfait', 'nous closions'),
    ('clore', 'vous', 'Imparfait', 'vous closiez'),
    ('clore', 'ils', 'Imparfait', 'ils closaient'),
    ('clore', 'elles', 'Imparfait', 'elles closaient'),
    ('inclure', 'je', 'Imparfait', 'j''incluais'),
    ('inclure', 'tu', 'Imparfait', 'tu incluais'),
    ('inclure', 'il', 'Imparfait', 'il incluait'),
    ('inclure', 'elle', 'Imparfait', 'elle incluait'),
    ('inclure', 'on', 'Imparfait', 'on incluait'),
    ('inclure', 'nous', 'Imparfait', 'nous incluions'),
    ('inclure', 'vous', 'Imparfait', 'vous incluiez'),
    ('inclure', 'ils', 'Imparfait', 'ils incluaient'),
    ('inclure', 'elles', 'Imparfait', 'elles incluaient'),
    ('cuire', 'je', 'Imparfait', 'je cuisais'),
    ('cuire', 'tu', 'Imparfait', 'tu cuisais'),
    ('cuire', 'il', 'Imparfait', 'il cuisait'),
    ('cuire', 'elle', 'Imparfait', 'elle cuisait'),
    ('cuire', 'on', 'Imparfait', 'on cuisait'),
    ('cuire', 'nous', 'Imparfait', 'nous cuisions'),
    ('cuire', 'vous', 'Imparfait', 'vous cuisiez'),
    ('cuire', 'ils', 'Imparfait', 'ils cuisaient'),
    ('cuire', 'elles', 'Imparfait', 'elles cuisaient'),
    ('resoudre', 'je', 'Imparfait', 'je résolvais'),
    ('resoudre', 'tu', 'Imparfait', 'tu résolvais'),
    ('resoudre', 'il', 'Imparfait', 'il résolvait'),
    ('resoudre', 'elle', 'Imparfait', 'elle résolvait'),
    ('resoudre', 'on', 'Imparfait', 'on résolvait'),
    ('resoudre', 'nous', 'Imparfait', 'nous résolvions'),
    ('resoudre', 'vous', 'Imparfait', 'vous résolviez'),
    ('resoudre', 'ils', 'Imparfait', 'ils résolvaient'),
    ('resoudre', 'elles', 'Imparfait', 'elles résolvaient'),
    ('absoudre', 'je', 'Imparfait', 'j''absolvais'),
    ('absoudre', 'tu', 'Imparfait', 'tu absolvais'),
    ('absoudre', 'il', 'Imparfait', 'il absolvait'),
    ('absoudre', 'elle', 'Imparfait', 'elle absolvait'),
    ('absoudre', 'on', 'Imparfait', 'on absolvait'),
    ('absoudre', 'nous', 'Imparfait', 'nous absolvions'),
    ('absoudre', 'vous', 'Imparfait', 'vous absolviez'),
    ('absoudre', 'ils', 'Imparfait', 'ils absolvaient'),
    ('absoudre', 'elles', 'Imparfait', 'elles absolvaient'),
    ('se lever', 'je', 'Imparfait', 'je me levais'),
    ('se lever', 'tu', 'Imparfait', 'tu te levais'),
    ('se lever', 'il', 'Imparfait', 'il se levait'),
    ('se lever', 'elle', 'Imparfait', 'elle se levait'),
    ('se lever', 'on', 'Imparfait', 'on se levait'),
    ('se lever', 'nous', 'Imparfait', 'nous nous levions'),
    ('se lever', 'vous', 'Imparfait', 'vous vous leviez'),
    ('se lever', 'ils', 'Imparfait', 'ils se levaient'),
    ('se lever', 'elles', 'Imparfait', 'elles se levaient'),
    ('se coucher', 'je', 'Imparfait', 'je me couchais'),
    ('se coucher', 'tu', 'Imparfait', 'tu te couchais'),
    ('se coucher', 'il', 'Imparfait', 'il se couchait'),
    ('se coucher', 'elle', 'Imparfait', 'elle se couchait'),
    ('se coucher', 'on', 'Imparfait', 'on se couchait'),
    ('se coucher', 'nous', 'Imparfait', 'nous nous couchions'),
    ('se coucher', 'vous', 'Imparfait', 'vous vous couchiez'),
    ('se coucher', 'ils', 'Imparfait', 'ils se couchaient'),
    ('se coucher', 'elles', 'Imparfait', 'elles se couchaient'),
    ('s’habiller', 'je', 'Imparfait', 'je m''habillais'),
    ('s’habiller', 'tu', 'Imparfait', 'tu t''habillais'),
    ('s’habiller', 'il', 'Imparfait', 'il s''habillait'),
    ('s’habiller', 'elle', 'Imparfait', 'elle s''habillait'),
    ('s’habiller', 'on', 'Imparfait', 'on s''habillait'),
    ('s’habiller', 'nous', 'Imparfait', 'nous nous habillions'),
    ('s’habiller', 'vous', 'Imparfait', 'vous vous habilliez'),
    ('s’habiller', 'ils', 'Imparfait', 'ils s''habillaient'),
    ('s’habiller', 'elles', 'Imparfait', 'elles s''habillaient'),
    ('se laver', 'je', 'Imparfait', 'je me lavais'),
    ('se laver', 'tu', 'Imparfait', 'tu te lavais'),
    ('se laver', 'il', 'Imparfait', 'il se lavait'),
    ('se laver', 'elle', 'Imparfait', 'elle se lavait'),
    ('se laver', 'on', 'Imparfait', 'on se lavait'),
    ('se laver', 'nous', 'Imparfait', 'nous nous lavions'),
    ('se laver', 'vous', 'Imparfait', 'vous vous laviez'),
    ('se laver', 'ils', 'Imparfait', 'ils se lavaient'),
    ('se laver', 'elles', 'Imparfait', 'elles se lavaient'),
    ('se brosser', 'je', 'Imparfait', 'je me brossais'),
    ('se brosser', 'tu', 'Imparfait', 'tu te brossais'),
    ('se brosser', 'il', 'Imparfait', 'il se brossait'),
    ('se brosser', 'elle', 'Imparfait', 'elle se brossait'),
    ('se brosser', 'on', 'Imparfait', 'on se brossait'),
    ('se brosser', 'nous', 'Imparfait', 'nous nous brossions'),
    ('se brosser', 'vous', 'Imparfait', 'vous vous brossiez'),
    ('se brosser', 'ils', 'Imparfait', 'ils se brossaient'),
    ('se brosser', 'elles', 'Imparfait', 'elles se brossaient'),
    ('se réveiller', 'je', 'Imparfait', 'je me réveillais'),
    ('se réveiller', 'tu', 'Imparfait', 'tu te réveillais'),
    ('se réveiller', 'il', 'Imparfait', 'il se réveillait'),
    ('se réveiller', 'elle', 'Imparfait', 'elle se réveillait'),
    ('se réveiller', 'on', 'Imparfait', 'on se réveillait'),
    ('se réveiller', 'nous', 'Imparfait', 'nous nous réveillions'),
    ('se réveiller', 'vous', 'Imparfait', 'vous vous réveilliez'),
    ('se réveiller', 'ils', 'Imparfait', 'ils se réveillaient'),
    ('se réveiller', 'elles', 'Imparfait', 'elles se réveillaient'),
    ('se reposer', 'je', 'Imparfait', 'je me reposais'),
    ('se reposer', 'tu', 'Imparfait', 'tu te reposais'),
    ('se reposer', 'il', 'Imparfait', 'il se reposait'),
    ('se reposer', 'elle', 'Imparfait', 'elle se reposait'),
    ('se reposer', 'on', 'Imparfait', 'on se reposait'),
    ('se reposer', 'nous', 'Imparfait', 'nous nous reposions'),
    ('se reposer', 'vous', 'Imparfait', 'vous vous reposiez'),
    ('se reposer', 'ils', 'Imparfait', 'ils se reposaient'),
    ('se reposer', 'elles', 'Imparfait', 'elles se reposaient'),
    ('se dépêcher', 'je', 'Imparfait', 'je me dépêchais'),
    ('se dépêcher', 'tu', 'Imparfait', 'tu te dépêchais'),
    ('se dépêcher', 'il', 'Imparfait', 'il se dépêchait'),
    ('se dépêcher', 'elle', 'Imparfait', 'elle se dépêchait'),
    ('se dépêcher', 'on', 'Imparfait', 'on se dépêchait'),
    ('se dépêcher', 'nous', 'Imparfait', 'nous nous dépêchions'),
    ('se dépêcher', 'vous', 'Imparfait', 'vous vous dépêchiez'),
    ('se dépêcher', 'ils', 'Imparfait', 'ils se dépêchaient'),
    ('se dépêcher', 'elles', 'Imparfait', 'elles se dépêchaient'),
    ('se souvenir', 'je', 'Imparfait', 'je me souvenais'),
    ('se souvenir', 'tu', 'Imparfait', 'tu te souvenais'),
    ('se souvenir', 'il', 'Imparfait', 'il se souvenait'),
    ('se souvenir', 'elle', 'Imparfait', 'elle se souvenait'),
    ('se souvenir', 'on', 'Imparfait', 'on se souvenait'),
    ('se souvenir', 'nous', 'Imparfait', 'nous nous souvenions'),
    ('se souvenir', 'vous', 'Imparfait', 'vous vous souveniez'),
    ('se souvenir', 'ils', 'Imparfait', 'ils se souvenaient'),
    ('se souvenir', 'elles', 'Imparfait', 'elles se souvenaient'),
    ('se rendre compte', 'je', 'Imparfait', 'je me rendais compte'),
    ('se rendre compte', 'tu', 'Imparfait', 'tu te rendais compte'),
    ('se rendre compte', 'il', 'Imparfait', 'il se rendait compte'),
    ('se rendre compte', 'elle', 'Imparfait', 'elle se rendait compte'),
    ('se rendre compte', 'on', 'Imparfait', 'on se rendait compte'),
    ('se rendre compte', 'nous', 'Imparfait', 'nous nous rendions compte'),
    ('se rendre compte', 'vous', 'Imparfait', 'vous vous rendiez compte'),
    ('se rendre compte', 'ils', 'Imparfait', 'ils se rendaient compte'),
    ('se rendre compte', 'elles', 'Imparfait', 'elles se rendaient compte'),
    ('s’intéresser', 'je', 'Imparfait', 'je m''intéressais'),
    ('s’intéresser', 'tu', 'Imparfait', 'tu t''intéressais'),
    ('s’intéresser', 'il', 'Imparfait', 'il s''intéressait'),
    ('s’intéresser', 'elle', 'Imparfait', 'elle s''intéressait'),
    ('s’intéresser', 'on', 'Imparfait', 'on s''intéressait'),
    ('s’intéresser', 'nous', 'Imparfait', 'nous nous intéressions'),
    ('s’intéresser', 'vous', 'Imparfait', 'vous vous intéressiez'),
    ('s’intéresser', 'ils', 'Imparfait', 'ils s''intéressaient'),
    ('s’intéresser', 'elles', 'Imparfait', 'elles s''intéressaient'),
    ('s’ennuyer', 'je', 'Imparfait', 'je m''ennuyais'),
    ('s’ennuyer', 'tu', 'Imparfait', 'tu t''ennuyais'),
    ('s’ennuyer', 'il', 'Imparfait', 'il s''ennuyait'),
    ('s’ennuyer', 'elle', 'Imparfait', 'elle s''ennuyait'),
    ('s’ennuyer', 'on', 'Imparfait', 'on s''ennuyait'),
    ('s’ennuyer', 'nous', 'Imparfait', 'nous nous ennuyions'),
    ('s’ennuyer', 'vous', 'Imparfait', 'vous vous ennuyiez'),
    ('s’ennuyer', 'ils', 'Imparfait', 'ils s''ennuyaient'),
    ('s’ennuyer', 'elles', 'Imparfait', 'elles s''ennuyaient'),
    ('se fâcher', 'je', 'Imparfait', 'je me fâchais'),
    ('se fâcher', 'tu', 'Imparfait', 'tu te fâchais'),
    ('se fâcher', 'il', 'Imparfait', 'il se fâchait'),
    ('se fâcher', 'elle', 'Imparfait', 'elle se fâchait'),
    ('se fâcher', 'on', 'Imparfait', 'on se fâchait'),
    ('se fâcher', 'nous', 'Imparfait', 'nous nous fâchions'),
    ('se fâcher', 'vous', 'Imparfait', 'vous vous fâchiez'),
    ('se fâcher', 'ils', 'Imparfait', 'ils se fâchaient'),
    ('se fâcher', 'elles', 'Imparfait', 'elles se fâchaient'),
    ('se tromper', 'je', 'Imparfait', 'je me trompais'),
    ('se tromper', 'tu', 'Imparfait', 'tu te trompais'),
    ('se tromper', 'il', 'Imparfait', 'il se trompait'),
    ('se tromper', 'elle', 'Imparfait', 'elle se trompait'),
    ('se tromper', 'on', 'Imparfait', 'on se trompait'),
    ('se tromper', 'nous', 'Imparfait', 'nous nous trompions'),
    ('se tromper', 'vous', 'Imparfait', 'vous vous trompiez'),
    ('se tromper', 'ils', 'Imparfait', 'ils se trompaient'),
    ('se tromper', 'elles', 'Imparfait', 'elles se trompaient'),
    ('se taire', 'je', 'Imparfait', 'je me taisais'),
    ('se taire', 'tu', 'Imparfait', 'tu te taisais'),
    ('se taire', 'il', 'Imparfait', 'il se taisait'),
    ('se taire', 'elle', 'Imparfait', 'elle se taisait'),
    ('se taire', 'on', 'Imparfait', 'on se taisait'),
    ('se taire', 'nous', 'Imparfait', 'nous nous taisions'),
    ('se taire', 'vous', 'Imparfait', 'vous vous taisiez'),
    ('se taire', 'ils', 'Imparfait', 'ils se taisaient'),
    ('se taire', 'elles', 'Imparfait', 'elles se taisaient'),
    ('s’asseoir', 'je', 'Imparfait', 'je m''assoyais'),
    ('s’asseoir', 'tu', 'Imparfait', 'tu t''assoyais'),
    ('s’asseoir', 'il', 'Imparfait', 'il s''assoyait'),
    ('s’asseoir', 'elle', 'Imparfait', 'elle s''assoyait'),
    ('s’asseoir', 'on', 'Imparfait', 'on s''assoyait'),
    ('s’asseoir', 'nous', 'Imparfait', 'nous nous assoyions'),
    ('s’asseoir', 'vous', 'Imparfait', 'vous vous assoyiez'),
    ('s’asseoir', 'ils', 'Imparfait', 'ils s''assoyaient'),
    ('s’asseoir', 'elles', 'Imparfait', 'elles s''assoyaient'),
    ('s’entendre', 'je', 'Imparfait', 'je m''entendais'),
    ('s’entendre', 'tu', 'Imparfait', 'tu t''entendais'),
    ('s’entendre', 'il', 'Imparfait', 'il s''entendait'),
    ('s’entendre', 'elle', 'Imparfait', 'elle s''entendait'),
    ('s’entendre', 'on', 'Imparfait', 'on s''entendait'),
    ('s’entendre', 'nous', 'Imparfait', 'nous nous entendions'),
    ('s’entendre', 'vous', 'Imparfait', 'vous vous entendiez'),
    ('s’entendre', 'ils', 'Imparfait', 'ils s''entendaient'),
    ('s’entendre', 'elles', 'Imparfait', 'elles s''entendaient'),
    ('se disputer', 'je', 'Imparfait', 'je me disputais'),
    ('se disputer', 'tu', 'Imparfait', 'tu te disputais'),
    ('se disputer', 'il', 'Imparfait', 'il se disputait'),
    ('se disputer', 'elle', 'Imparfait', 'elle se disputait'),
    ('se disputer', 'on', 'Imparfait', 'on se disputait'),
    ('se disputer', 'nous', 'Imparfait', 'nous nous disputions'),
    ('se disputer', 'vous', 'Imparfait', 'vous vous disputiez'),
    ('se disputer', 'ils', 'Imparfait', 'ils se disputaient'),
    ('se disputer', 'elles', 'Imparfait', 'elles se disputaient'),
    ('se marier', 'je', 'Imparfait', 'je me mariais'),
    ('se marier', 'tu', 'Imparfait', 'tu te mariais'),
    ('se marier', 'il', 'Imparfait', 'il se mariait'),
    ('se marier', 'elle', 'Imparfait', 'elle se mariait'),
    ('se marier', 'on', 'Imparfait', 'on se mariait'),
    ('se marier', 'nous', 'Imparfait', 'nous nous mariions'),
    ('se marier', 'vous', 'Imparfait', 'vous vous mariiez'),
    ('se marier', 'ils', 'Imparfait', 'ils se mariaient'),
    ('se marier', 'elles', 'Imparfait', 'elles se mariaient'),
    ('se divorcer', 'je', 'Imparfait', 'je me divorçais'),
    ('se divorcer', 'tu', 'Imparfait', 'tu te divorçais'),
    ('se divorcer', 'il', 'Imparfait', 'il se divorçait'),
    ('se divorcer', 'elle', 'Imparfait', 'elle se divorçait'),
    ('se divorcer', 'on', 'Imparfait', 'on se divorçait'),
    ('se divorcer', 'nous', 'Imparfait', 'nous nous divorcions'),
    ('se divorcer', 'vous', 'Imparfait', 'vous vous divorciez'),
    ('se divorcer', 'ils', 'Imparfait', 'ils se divorçaient'),
    ('se divorcer', 'elles', 'Imparfait', 'elles se divorçaient'),
    ('se battre', 'je', 'Imparfait', 'je me battais'),
    ('se battre', 'tu', 'Imparfait', 'tu te battais'),
    ('se battre', 'il', 'Imparfait', 'il se battait'),
    ('se battre', 'elle', 'Imparfait', 'elle se battait'),
    ('se battre', 'on', 'Imparfait', 'on se battait'),
    ('se battre', 'nous', 'Imparfait', 'nous nous battions'),
    ('se battre', 'vous', 'Imparfait', 'vous vous battiez'),
    ('se battre', 'ils', 'Imparfait', 'ils se battaient'),
    ('se battre', 'elles', 'Imparfait', 'elles se battaient'),
    ('s’en aller', 'je', 'Imparfait', 'je m''en allais'),
    ('s’en aller', 'tu', 'Imparfait', 'tu t''en allais'),
    ('s’en aller', 'il', 'Imparfait', 'il s''en allait'),
    ('s’en aller', 'elle', 'Imparfait', 'elle s''en allait'),
    ('s’en aller', 'on', 'Imparfait', 'on s''en allait'),
    ('s’en aller', 'nous', 'Imparfait', 'nous nous en allions'),
    ('s’en aller', 'vous', 'Imparfait', 'vous vous en alliez'),
    ('s’en aller', 'ils', 'Imparfait', 'ils s''en allaient'),
    ('s’en aller', 'elles', 'Imparfait', 'elles s''en allaient'),
    ('se rendre', 'je', 'Imparfait', 'je me rendais'),
    ('se rendre', 'tu', 'Imparfait', 'tu te rendais'),
    ('se rendre', 'il', 'Imparfait', 'il se rendait'),
    ('se rendre', 'elle', 'Imparfait', 'elle se rendait'),
    ('se rendre', 'on', 'Imparfait', 'on se rendait'),
    ('se rendre', 'nous', 'Imparfait', 'nous nous rendions'),
    ('se rendre', 'vous', 'Imparfait', 'vous vous rendiez'),
    ('se rendre', 'ils', 'Imparfait', 'ils se rendaient'),
    ('se rendre', 'elles', 'Imparfait', 'elles se rendaient'),
    ('se servir', 'je', 'Imparfait', 'je me servais'),
    ('se servir', 'tu', 'Imparfait', 'tu te servais'),
    ('se servir', 'il', 'Imparfait', 'il se servait'),
    ('se servir', 'elle', 'Imparfait', 'elle se servait'),
    ('se servir', 'on', 'Imparfait', 'on se servait'),
    ('se servir', 'nous', 'Imparfait', 'nous nous servions'),
    ('se servir', 'vous', 'Imparfait', 'vous vous serviez'),
    ('se servir', 'ils', 'Imparfait', 'ils se servaient'),
    ('se servir', 'elles', 'Imparfait', 'elles se servaient'),
    ('s’apercevoir', 'je', 'Imparfait', 'je m''apercevais'),
    ('s’apercevoir', 'tu', 'Imparfait', 'tu t''apercevais'),
    ('s’apercevoir', 'il', 'Imparfait', 'il s''apercevait'),
    ('s’apercevoir', 'elle', 'Imparfait', 'elle s''apercevait'),
    ('s’apercevoir', 'on', 'Imparfait', 'on s''apercevait'),
    ('s’apercevoir', 'nous', 'Imparfait', 'nous nous apercevions'),
    ('s’apercevoir', 'vous', 'Imparfait', 'vous vous aperceviez'),
    ('s’apercevoir', 'ils', 'Imparfait', 'ils s''apercevaient'),
    ('s’apercevoir', 'elles', 'Imparfait', 'elles s''apercevaient'),
    ('se douter', 'je', 'Imparfait', 'je me doutais'),
    ('se douter', 'tu', 'Imparfait', 'tu te doutais'),
    ('se douter', 'il', 'Imparfait', 'il se doutait'),
    ('se douter', 'elle', 'Imparfait', 'elle se doutait'),
    ('se douter', 'on', 'Imparfait', 'on se doutait'),
    ('se douter', 'nous', 'Imparfait', 'nous nous doutions'),
    ('se douter', 'vous', 'Imparfait', 'vous vous doutiez'),
    ('se douter', 'ils', 'Imparfait', 'ils se doutaient'),
    ('se douter', 'elles', 'Imparfait', 'elles se doutaient'),
    ('se passer', 'je', 'Imparfait', 'je me passais'),
    ('se passer', 'tu', 'Imparfait', 'tu te passais'),
    ('se passer', 'il', 'Imparfait', 'il se passait'),
    ('se passer', 'elle', 'Imparfait', 'elle se passait'),
    ('se passer', 'on', 'Imparfait', 'on se passait'),
    ('se passer', 'nous', 'Imparfait', 'nous nous passions'),
    ('se passer', 'vous', 'Imparfait', 'vous vous passiez'),
    ('se passer', 'ils', 'Imparfait', 'ils se passaient'),
    ('se passer', 'elles', 'Imparfait', 'elles se passaient'),
    ('se trouver', 'je', 'Imparfait', 'je me trouvais'),
    ('se trouver', 'tu', 'Imparfait', 'tu te trouvais'),
    ('se trouver', 'il', 'Imparfait', 'il se trouvait'),
    ('se trouver', 'elle', 'Imparfait', 'elle se trouvait'),
    ('se trouver', 'on', 'Imparfait', 'on se trouvait'),
    ('se trouver', 'nous', 'Imparfait', 'nous nous trouvions'),
    ('se trouver', 'vous', 'Imparfait', 'vous vous trouviez'),
    ('se trouver', 'ils', 'Imparfait', 'ils se trouvaient'),
    ('se trouver', 'elles', 'Imparfait', 'elles se trouvaient'),
    ('se mettre', 'je', 'Imparfait', 'je me mettais'),
    ('se mettre', 'tu', 'Imparfait', 'tu te mettais'),
    ('se mettre', 'il', 'Imparfait', 'il se mettait'),
    ('se mettre', 'elle', 'Imparfait', 'elle se mettait'),
    ('se mettre', 'on', 'Imparfait', 'on se mettait'),
    ('se mettre', 'nous', 'Imparfait', 'nous nous mettions'),
    ('se mettre', 'vous', 'Imparfait', 'vous vous mettiez'),
    ('se mettre', 'ils', 'Imparfait', 'ils se mettaient'),
    ('se mettre', 'elles', 'Imparfait', 'elles se mettaient'),
    ('se faire', 'je', 'Imparfait', 'je me faisais'),
    ('se faire', 'tu', 'Imparfait', 'tu te faisais'),
    ('se faire', 'il', 'Imparfait', 'il se faisait'),
    ('se faire', 'elle', 'Imparfait', 'elle se faisait'),
    ('se faire', 'on', 'Imparfait', 'on se faisait'),
    ('se faire', 'nous', 'Imparfait', 'nous nous faisions'),
    ('se faire', 'vous', 'Imparfait', 'vous vous faisiez'),
    ('se faire', 'ils', 'Imparfait', 'ils se faisaient'),
    ('se faire', 'elles', 'Imparfait', 'elles se faisaient'),
    ('se demander', 'je', 'Imparfait', 'je me demandais'),
    ('se demander', 'tu', 'Imparfait', 'tu te demandais'),
    ('se demander', 'il', 'Imparfait', 'il se demandait'),
    ('se demander', 'elle', 'Imparfait', 'elle se demandait'),
    ('se demander', 'on', 'Imparfait', 'on se demandait'),
    ('se demander', 'nous', 'Imparfait', 'nous nous demandions'),
    ('se demander', 'vous', 'Imparfait', 'vous vous demandiez'),
    ('se demander', 'ils', 'Imparfait', 'ils se demandaient'),
    ('se demander', 'elles', 'Imparfait', 'elles se demandaient'),
    ('se plaindre', 'je', 'Imparfait', 'je me plaignais'),
    ('se plaindre', 'tu', 'Imparfait', 'tu te plaignais'),
    ('se plaindre', 'il', 'Imparfait', 'il se plaignait'),
    ('se plaindre', 'elle', 'Imparfait', 'elle se plaignait'),
    ('se plaindre', 'on', 'Imparfait', 'on se plaignait'),
    ('se plaindre', 'nous', 'Imparfait', 'nous nous plaignions'),
    ('se plaindre', 'vous', 'Imparfait', 'vous vous plaigniez'),
    ('se plaindre', 'ils', 'Imparfait', 'ils se plaignaient'),
    ('se plaindre', 'elles', 'Imparfait', 'elles se plaignaient'),
    ('se voir', 'je', 'Imparfait', 'je me voyais'),
    ('se voir', 'tu', 'Imparfait', 'tu te voyais'),
    ('se voir', 'il', 'Imparfait', 'il se voyait'),
    ('se voir', 'elle', 'Imparfait', 'elle se voyait'),
    ('se voir', 'on', 'Imparfait', 'on se voyait'),
    ('se voir', 'nous', 'Imparfait', 'nous nous voyions'),
    ('se voir', 'vous', 'Imparfait', 'vous vous voyiez'),
    ('se voir', 'ils', 'Imparfait', 'ils se voyaient'),
    ('se voir', 'elles', 'Imparfait', 'elles se voyaient'),
    ('s’imaginer', 'je', 'Imparfait', 'je m''imaginais'),
    ('s’imaginer', 'tu', 'Imparfait', 'tu t''imaginais'),
    ('s’imaginer', 'il', 'Imparfait', 'il s''imaginait'),
    ('s’imaginer', 'elle', 'Imparfait', 'elle s''imaginait'),
    ('s’imaginer', 'on', 'Imparfait', 'on s''imaginait'),
    ('s’imaginer', 'nous', 'Imparfait', 'nous nous imaginions'),
    ('s’imaginer', 'vous', 'Imparfait', 'vous vous imaginiez'),
    ('s’imaginer', 'ils', 'Imparfait', 'ils s''imaginaient'),
    ('s’imaginer', 'elles', 'Imparfait', 'elles s''imaginaient'),
    ('s’efforcer', 'je', 'Imparfait', 'je m''efforçais'),
    ('s’efforcer', 'tu', 'Imparfait', 'tu t''efforçais'),
    ('s’efforcer', 'il', 'Imparfait', 'il s''efforçait'),
    ('s’efforcer', 'elle', 'Imparfait', 'elle s''efforçait'),
    ('s’efforcer', 'on', 'Imparfait', 'on s''efforçait'),
    ('s’efforcer', 'nous', 'Imparfait', 'nous nous efforcions'),
    ('s’efforcer', 'vous', 'Imparfait', 'vous vous efforciez'),
    ('s’efforcer', 'ils', 'Imparfait', 'ils s''efforçaient'),
    ('s’efforcer', 'elles', 'Imparfait', 'elles s''efforçaient'),
    ('s’évanouir', 'je', 'Imparfait', 'je m''évanouissais'),
    ('s’évanouir', 'tu', 'Imparfait', 'tu t''évanouissais'),
    ('s’évanouir', 'il', 'Imparfait', 'il s''évanouissait'),
    ('s’évanouir', 'elle', 'Imparfait', 'elle s''évanouissait'),
    ('s’évanouir', 'on', 'Imparfait', 'on s''évanouissait'),
    ('s’évanouir', 'nous', 'Imparfait', 'nous nous évanouissions'),
    ('s’évanouir', 'vous', 'Imparfait', 'vous vous évanouissiez'),
    ('s’évanouir', 'ils', 'Imparfait', 'ils s''évanouissaient'),
    ('s’évanouir', 'elles', 'Imparfait', 'elles s''évanouissaient'),
    ('s’indigner', 'je', 'Imparfait', 'je m''indignais'),
    ('s’indigner', 'tu', 'Imparfait', 'tu t''indignais'),
    ('s’indigner', 'il', 'Imparfait', 'il s''indignait'),
    ('s’indigner', 'elle', 'Imparfait', 'elle s''indignait'),
    ('s’indigner', 'on', 'Imparfait', 'on s''indignait'),
    ('s’indigner', 'nous', 'Imparfait', 'nous nous indignions'),
    ('s’indigner', 'vous', 'Imparfait', 'vous vous indigniez'),
    ('s’indigner', 'ils', 'Imparfait', 'ils s''indignaient'),
    ('s’indigner', 'elles', 'Imparfait', 'elles s''indignaient'),
    ('s’épanouir', 'je', 'Imparfait', 'je m''épanouissais'),
    ('s’épanouir', 'tu', 'Imparfait', 'tu t''épanouissais'),
    ('s’épanouir', 'il', 'Imparfait', 'il s''épanouissait'),
    ('s’épanouir', 'elle', 'Imparfait', 'elle s''épanouissait'),
    ('s’épanouir', 'on', 'Imparfait', 'on s''épanouissait'),
    ('s’épanouir', 'nous', 'Imparfait', 'nous nous épanouissions'),
    ('s’épanouir', 'vous', 'Imparfait', 'vous vous épanouissiez'),
    ('s’épanouir', 'ils', 'Imparfait', 'ils s''épanouissaient'),
    ('s’épanouir', 'elles', 'Imparfait', 'elles s''épanouissaient'),
    ('s’en sortir', 'je', 'Imparfait', 'je m''en sortais'),
    ('s’en sortir', 'tu', 'Imparfait', 'tu t''en sortais'),
    ('s’en sortir', 'il', 'Imparfait', 'il s''en sortait'),
    ('s’en sortir', 'elle', 'Imparfait', 'elle s''en sortait'),
    ('s’en sortir', 'on', 'Imparfait', 'on s''en sortait'),
    ('s’en sortir', 'nous', 'Imparfait', 'nous nous en sortions'),
    ('s’en sortir', 'vous', 'Imparfait', 'vous vous en sortiez'),
    ('s’en sortir', 'ils', 'Imparfait', 'ils s''en sortaient'),
    ('s’en sortir', 'elles', 'Imparfait', 'elles s''en sortaient'),
    ('s’attendre', 'je', 'Imparfait', 'je m''attendais'),
    ('s’attendre', 'tu', 'Imparfait', 'tu t''attendais'),
    ('s’attendre', 'il', 'Imparfait', 'il s''attendait'),
    ('s’attendre', 'elle', 'Imparfait', 'elle s''attendait'),
    ('s’attendre', 'on', 'Imparfait', 'on s''attendait'),
    ('s’attendre', 'nous', 'Imparfait', 'nous nous attendions'),
    ('s’attendre', 'vous', 'Imparfait', 'vous vous attendiez'),
    ('s’attendre', 'ils', 'Imparfait', 'ils s''attendaient'),
    ('s’attendre', 'elles', 'Imparfait', 'elles s''attendaient'),
    ('s’interroger', 'je', 'Imparfait', 'je m''interrogeais'),
    ('s’interroger', 'tu', 'Imparfait', 'tu t''interrogeais'),
    ('s’interroger', 'il', 'Imparfait', 'il s''interrogeait'),
    ('s’interroger', 'elle', 'Imparfait', 'elle s''interrogeait'),
    ('s’interroger', 'on', 'Imparfait', 'on s''interrogeait'),
    ('s’interroger', 'nous', 'Imparfait', 'nous nous interrogions'),
    ('s’interroger', 'vous', 'Imparfait', 'vous vous interrogiez'),
    ('s’interroger', 'ils', 'Imparfait', 'ils s''interrogeaient'),
    ('s’interroger', 'elles', 'Imparfait', 'elles s''interrogeaient'),
    ('se heurter', 'je', 'Imparfait', 'je me heurtais'),
    ('se heurter', 'tu', 'Imparfait', 'tu te heurtais'),
    ('se heurter', 'il', 'Imparfait', 'il se heurtait'),
    ('se heurter', 'elle', 'Imparfait', 'elle se heurtait'),
    ('se heurter', 'on', 'Imparfait', 'on se heurtait'),
    ('se heurter', 'nous', 'Imparfait', 'nous nous heurtions'),
    ('se heurter', 'vous', 'Imparfait', 'vous vous heurtiez'),
    ('se heurter', 'ils', 'Imparfait', 'ils se heurtaient'),
    ('se heurter', 'elles', 'Imparfait', 'elles se heurtaient'),
    ('se méfier', 'je', 'Imparfait', 'je me méfiais'),
    ('se méfier', 'tu', 'Imparfait', 'tu te méfiais'),
    ('se méfier', 'il', 'Imparfait', 'il se méfiait'),
    ('se méfier', 'elle', 'Imparfait', 'elle se méfiait'),
    ('se méfier', 'on', 'Imparfait', 'on se méfiait'),
    ('se méfier', 'nous', 'Imparfait', 'nous nous méfiions'),
    ('se méfier', 'vous', 'Imparfait', 'vous vous méfiiez'),
    ('se méfier', 'ils', 'Imparfait', 'ils se méfiaient'),
    ('se méfier', 'elles', 'Imparfait', 'elles se méfiaient'),
    ('se replier sur soi-même', 'je', 'Imparfait', 'je me repliais sur moi-même'),
    ('se replier sur soi-même', 'tu', 'Imparfait', 'tu te repliais sur toi-même'),
    ('se replier sur soi-même', 'il', 'Imparfait', 'il se repliait sur lui-même'),
    ('se replier sur soi-même', 'elle', 'Imparfait', 'elle se repliait sur elle-même'),
    ('se replier sur soi-même', 'on', 'Imparfait', 'on se repliait sur soi-même'),
    ('se replier sur soi-même', 'nous', 'Imparfait', 'nous nous repliions sur nous-mêmes'),
    ('se replier sur soi-même', 'vous', 'Imparfait', 'vous vous repliiez sur vous-mêmes'),
    ('se replier sur soi-même', 'ils', 'Imparfait', 'ils se repliaient sur eux-mêmes'),
    ('se replier sur soi-même', 'elles', 'Imparfait', 'elles se repliaient sur elles-mêmes'),
    ('se raviser', 'je', 'Imparfait', 'je me ravisais'),
    ('se raviser', 'tu', 'Imparfait', 'tu te ravisais'),
    ('se raviser', 'il', 'Imparfait', 'il se ravisait'),
    ('se raviser', 'elle', 'Imparfait', 'elle se ravisait'),
    ('se raviser', 'on', 'Imparfait', 'on se ravisait'),
    ('se raviser', 'nous', 'Imparfait', 'nous nous ravisions'),
    ('se raviser', 'vous', 'Imparfait', 'vous vous ravisiez'),
    ('se raviser', 'ils', 'Imparfait', 'ils se ravisaient'),
    ('se raviser', 'elles', 'Imparfait', 'elles se ravisaient'),
    ('se débrouiller', 'je', 'Imparfait', 'je me débrouillais'),
    ('se débrouiller', 'tu', 'Imparfait', 'tu te débrouillais'),
    ('se débrouiller', 'il', 'Imparfait', 'il se débrouillait'),
    ('se débrouiller', 'elle', 'Imparfait', 'elle se débrouillait'),
    ('se débrouiller', 'on', 'Imparfait', 'on se débrouillait'),
    ('se débrouiller', 'nous', 'Imparfait', 'nous nous débrouillions'),
    ('se débrouiller', 'vous', 'Imparfait', 'vous vous débrouilliez'),
    ('se débrouiller', 'ils', 'Imparfait', 'ils se débrouillaient'),
    ('se débrouiller', 'elles', 'Imparfait', 'elles se débrouillaient'),
    ('se réconcilier', 'je', 'Imparfait', 'je me réconciliais'),
    ('se réconcilier', 'tu', 'Imparfait', 'tu te réconciliais'),
    ('se réconcilier', 'il', 'Imparfait', 'il se réconciliait'),
    ('se réconcilier', 'elle', 'Imparfait', 'elle se réconciliait'),
    ('se réconcilier', 'on', 'Imparfait', 'on se réconciliait'),
    ('se réconcilier', 'nous', 'Imparfait', 'nous nous réconciliions'),
    ('se réconcilier', 'vous', 'Imparfait', 'vous vous réconciliiez'),
    ('se réconcilier', 'ils', 'Imparfait', 'ils se réconciliaient'),
    ('se réconcilier', 'elles', 'Imparfait', 'elles se réconciliaient'),
    ('se précipiter', 'je', 'Imparfait', 'je me précipitais'),
    ('se précipiter', 'tu', 'Imparfait', 'tu te précipitais'),
    ('se précipiter', 'il', 'Imparfait', 'il se précipitait'),
    ('se précipiter', 'elle', 'Imparfait', 'elle se précipitait'),
    ('se précipiter', 'on', 'Imparfait', 'on se précipitait'),
    ('se précipiter', 'nous', 'Imparfait', 'nous nous précipitions'),
    ('se précipiter', 'vous', 'Imparfait', 'vous vous précipitiez'),
    ('se précipiter', 'ils', 'Imparfait', 'ils se précipitaient'),
    ('se précipiter', 'elles', 'Imparfait', 'elles se précipitaient'),
    ('se figurer', 'je', 'Imparfait', 'je me figurais'),
    ('se figurer', 'tu', 'Imparfait', 'tu te figurais'),
    ('se figurer', 'il', 'Imparfait', 'il se figurait'),
    ('se figurer', 'elle', 'Imparfait', 'elle se figurait'),
    ('se figurer', 'on', 'Imparfait', 'on se figurait'),
    ('se figurer', 'nous', 'Imparfait', 'nous nous figurions'),
    ('se figurer', 'vous', 'Imparfait', 'vous vous figuriez'),
    ('se figurer', 'ils', 'Imparfait', 'ils se figuraient'),
    ('se figurer', 'elles', 'Imparfait', 'elles se figuraient'),
    ('acheter', 'je', 'Imparfait', 'j''achetais'),
    ('acheter', 'tu', 'Imparfait', 'tu achetais'),
    ('acheter', 'il', 'Imparfait', 'il achetait'),
    ('acheter', 'elle', 'Imparfait', 'elle achetait'),
    ('acheter', 'on', 'Imparfait', 'on achetait'),
    ('acheter', 'nous', 'Imparfait', 'nous achetions'),
    ('acheter', 'vous', 'Imparfait', 'vous achetiez'),
    ('acheter', 'ils', 'Imparfait', 'ils achetaient'),
    ('acheter', 'elles', 'Imparfait', 'elles achetaient'),
    ('aller', 'je', 'Imparfait', 'j''allais'),
    ('aller', 'tu', 'Imparfait', 'tu allais'),
    ('aller', 'il', 'Imparfait', 'il allait'),
    ('aller', 'elle', 'Imparfait', 'elle allait'),
    ('aller', 'on', 'Imparfait', 'on allait'),
    ('aller', 'nous', 'Imparfait', 'nous allions'),
    ('aller', 'vous', 'Imparfait', 'vous alliez'),
    ('aller', 'ils', 'Imparfait', 'ils allaient'),
    ('aller', 'elles', 'Imparfait', 'elles allaient'),
    ('appeler', 'je', 'Imparfait', 'j''appelais'),
    ('appeler', 'tu', 'Imparfait', 'tu appelais'),
    ('appeler', 'il', 'Imparfait', 'il appelait'),
    ('appeler', 'elle', 'Imparfait', 'elle appelait'),
    ('appeler', 'on', 'Imparfait', 'on appelait'),
    ('appeler', 'nous', 'Imparfait', 'nous appelions'),
    ('appeler', 'vous', 'Imparfait', 'vous appeliez'),
    ('appeler', 'ils', 'Imparfait', 'ils appelaient'),
    ('appeler', 'elles', 'Imparfait', 'elles appelaient'),
    ('attendre', 'je', 'Imparfait', 'j''attendais'),
    ('attendre', 'tu', 'Imparfait', 'tu attendais'),
    ('attendre', 'il', 'Imparfait', 'il attendait'),
    ('attendre', 'elle', 'Imparfait', 'elle attendait'),
    ('attendre', 'on', 'Imparfait', 'on attendait'),
    ('attendre', 'nous', 'Imparfait', 'nous attendions'),
    ('attendre', 'vous', 'Imparfait', 'vous attendiez'),
    ('attendre', 'ils', 'Imparfait', 'ils attendaient'),
    ('attendre', 'elles', 'Imparfait', 'elles attendaient'),
    ('courir', 'je', 'Imparfait', 'je courais'),
    ('courir', 'tu', 'Imparfait', 'tu courais'),
    ('courir', 'il', 'Imparfait', 'il courait'),
    ('courir', 'elle', 'Imparfait', 'elle courait'),
    ('courir', 'on', 'Imparfait', 'on courait'),
    ('courir', 'nous', 'Imparfait', 'nous courions'),
    ('courir', 'vous', 'Imparfait', 'vous couriez'),
    ('courir', 'ils', 'Imparfait', 'ils couraient'),
    ('courir', 'elles', 'Imparfait', 'elles couraient'),
    ('descendre', 'je', 'Imparfait', 'je descendais'),
    ('descendre', 'tu', 'Imparfait', 'tu descendais'),
    ('descendre', 'il', 'Imparfait', 'il descendait'),
    ('descendre', 'elle', 'Imparfait', 'elle descendait'),
    ('descendre', 'on', 'Imparfait', 'on descendait'),
    ('descendre', 'nous', 'Imparfait', 'nous descendions'),
    ('descendre', 'vous', 'Imparfait', 'vous descendiez'),
    ('descendre', 'ils', 'Imparfait', 'ils descendaient'),
    ('descendre', 'elles', 'Imparfait', 'elles descendaient'),
    ('dormir', 'je', 'Imparfait', 'je dormais'),
    ('dormir', 'tu', 'Imparfait', 'tu dormais'),
    ('dormir', 'il', 'Imparfait', 'il dormait'),
    ('dormir', 'elle', 'Imparfait', 'elle dormait'),
    ('dormir', 'on', 'Imparfait', 'on dormait'),
    ('dormir', 'nous', 'Imparfait', 'nous dormions'),
    ('dormir', 'vous', 'Imparfait', 'vous dormiez'),
    ('dormir', 'ils', 'Imparfait', 'ils dormaient'),
    ('dormir', 'elles', 'Imparfait', 'elles dormaient'),
    ('entendre', 'je', 'Imparfait', 'j''entendais'),
    ('entendre', 'tu', 'Imparfait', 'tu entendais'),
    ('entendre', 'il', 'Imparfait', 'il entendait'),
    ('entendre', 'elle', 'Imparfait', 'elle entendait'),
    ('entendre', 'on', 'Imparfait', 'on entendait'),
    ('entendre', 'nous', 'Imparfait', 'nous entendions'),
    ('entendre', 'vous', 'Imparfait', 'vous entendiez'),
    ('entendre', 'ils', 'Imparfait', 'ils entendaient'),
    ('entendre', 'elles', 'Imparfait', 'elles entendaient'),
    ('envoyer', 'je', 'Imparfait', 'j''envoyais'),
    ('envoyer', 'tu', 'Imparfait', 'tu envoyais'),
    ('envoyer', 'il', 'Imparfait', 'il envoyait'),
    ('envoyer', 'elle', 'Imparfait', 'elle envoyait'),
    ('envoyer', 'on', 'Imparfait', 'on envoyait'),
    ('envoyer', 'nous', 'Imparfait', 'nous envoyions'),
    ('envoyer', 'vous', 'Imparfait', 'vous envoyiez'),
    ('envoyer', 'ils', 'Imparfait', 'ils envoyaient'),
    ('envoyer', 'elles', 'Imparfait', 'elles envoyaient'),
    ('jeter', 'je', 'Imparfait', 'je jetais'),
    ('jeter', 'tu', 'Imparfait', 'tu jetais'),
    ('jeter', 'il', 'Imparfait', 'il jetait'),
    ('jeter', 'elle', 'Imparfait', 'elle jetait'),
    ('jeter', 'on', 'Imparfait', 'on jetait'),
    ('jeter', 'nous', 'Imparfait', 'nous jetions'),
    ('jeter', 'vous', 'Imparfait', 'vous jetiez'),
    ('jeter', 'ils', 'Imparfait', 'ils jetaient'),
    ('jeter', 'elles', 'Imparfait', 'elles jetaient'),
    ('partir', 'je', 'Imparfait', 'je partais'),
    ('partir', 'tu', 'Imparfait', 'tu partais'),
    ('partir', 'il', 'Imparfait', 'il partait'),
    ('partir', 'elle', 'Imparfait', 'elle partait'),
    ('partir', 'on', 'Imparfait', 'on partait'),
    ('partir', 'nous', 'Imparfait', 'nous partions'),
    ('partir', 'vous', 'Imparfait', 'vous partiez'),
    ('partir', 'ils', 'Imparfait', 'ils partaient'),
    ('partir', 'elles', 'Imparfait', 'elles partaient'),
    ('payer', 'je', 'Imparfait', 'je payais'),
    ('payer', 'tu', 'Imparfait', 'tu payais'),
    ('payer', 'il', 'Imparfait', 'il payait'),
    ('payer', 'elle', 'Imparfait', 'elle payait'),
    ('payer', 'on', 'Imparfait', 'on payait'),
    ('payer', 'nous', 'Imparfait', 'nous payions'),
    ('payer', 'vous', 'Imparfait', 'vous payiez'),
    ('payer', 'ils', 'Imparfait', 'ils payaient'),
    ('payer', 'elles', 'Imparfait', 'elles payaient'),
    ('perdre', 'je', 'Imparfait', 'je perdais'),
    ('perdre', 'tu', 'Imparfait', 'tu perdais'),
    ('perdre', 'il', 'Imparfait', 'il perdait'),
    ('perdre', 'elle', 'Imparfait', 'elle perdait'),
    ('perdre', 'on', 'Imparfait', 'on perdait'),
    ('perdre', 'nous', 'Imparfait', 'nous perdions'),
    ('perdre', 'vous', 'Imparfait', 'vous perdiez'),
    ('perdre', 'ils', 'Imparfait', 'ils perdaient'),
    ('perdre', 'elles', 'Imparfait', 'elles perdaient'),
    ('préférer', 'je', 'Imparfait', 'je préférais'),
    ('préférer', 'tu', 'Imparfait', 'tu préférais'),
    ('préférer', 'il', 'Imparfait', 'il préférait'),
    ('préférer', 'elle', 'Imparfait', 'elle préférait'),
    ('préférer', 'on', 'Imparfait', 'on préférait'),
    ('préférer', 'nous', 'Imparfait', 'nous préférions'),
    ('préférer', 'vous', 'Imparfait', 'vous préfériez'),
    ('préférer', 'ils', 'Imparfait', 'ils préféraient'),
    ('préférer', 'elles', 'Imparfait', 'elles préféraient'),
    ('répondre', 'je', 'Imparfait', 'je répondais'),
    ('répondre', 'tu', 'Imparfait', 'tu répondais'),
    ('répondre', 'il', 'Imparfait', 'il répondait'),
    ('répondre', 'elle', 'Imparfait', 'elle répondait'),
    ('répondre', 'on', 'Imparfait', 'on répondait'),
    ('répondre', 'nous', 'Imparfait', 'nous répondions'),
    ('répondre', 'vous', 'Imparfait', 'vous répondiez'),
    ('répondre', 'ils', 'Imparfait', 'ils répondaient'),
    ('répondre', 'elles', 'Imparfait', 'elles répondaient'),
    ('servir', 'je', 'Imparfait', 'je servais'),
    ('servir', 'tu', 'Imparfait', 'tu servais'),
    ('servir', 'il', 'Imparfait', 'il servait'),
    ('servir', 'elle', 'Imparfait', 'elle servait'),
    ('servir', 'on', 'Imparfait', 'on servait'),
    ('servir', 'nous', 'Imparfait', 'nous servions'),
    ('servir', 'vous', 'Imparfait', 'vous serviez'),
    ('servir', 'ils', 'Imparfait', 'ils servaient'),
    ('servir', 'elles', 'Imparfait', 'elles servaient'),
    ('sortir', 'je', 'Imparfait', 'je sortais'),
    ('sortir', 'tu', 'Imparfait', 'tu sortais'),
    ('sortir', 'il', 'Imparfait', 'il sortait'),
    ('sortir', 'elle', 'Imparfait', 'elle sortait'),
    ('sortir', 'on', 'Imparfait', 'on sortait'),
    ('sortir', 'nous', 'Imparfait', 'nous sortions'),
    ('sortir', 'vous', 'Imparfait', 'vous sortiez'),
    ('sortir', 'ils', 'Imparfait', 'ils sortaient'),
    ('sortir', 'elles', 'Imparfait', 'elles sortaient'),
    ('vendre', 'je', 'Imparfait', 'je vendais'),
    ('vendre', 'tu', 'Imparfait', 'tu vendais'),
    ('vendre', 'il', 'Imparfait', 'il vendait'),
    ('vendre', 'elle', 'Imparfait', 'elle vendait'),
    ('vendre', 'on', 'Imparfait', 'on vendait'),
    ('vendre', 'nous', 'Imparfait', 'nous vendions'),
    ('vendre', 'vous', 'Imparfait', 'vous vendiez'),
    ('vendre', 'ils', 'Imparfait', 'ils vendaient'),
    ('vendre', 'elles', 'Imparfait', 'elles vendaient'),
    ('manger', 'je', 'Imparfait', 'je mangeais'),
    ('manger', 'tu', 'Imparfait', 'tu mangeais'),
    ('manger', 'il', 'Imparfait', 'il mangeait'),
    ('manger', 'elle', 'Imparfait', 'elle mangeait'),
    ('manger', 'on', 'Imparfait', 'on mangeait'),
    ('manger', 'nous', 'Imparfait', 'nous mangions'),
    ('manger', 'vous', 'Imparfait', 'vous mangiez'),
    ('manger', 'ils', 'Imparfait', 'ils mangeaient'),
    ('manger', 'elles', 'Imparfait', 'elles mangeaient'),
    ('nager', 'je', 'Imparfait', 'je nageais'),
    ('nager', 'tu', 'Imparfait', 'tu nageais'),
    ('nager', 'il', 'Imparfait', 'il nageait'),
    ('nager', 'elle', 'Imparfait', 'elle nageait'),
    ('nager', 'on', 'Imparfait', 'on nageait'),
    ('nager', 'nous', 'Imparfait', 'nous nagions'),
    ('nager', 'vous', 'Imparfait', 'vous nagiez'),
    ('nager', 'ils', 'Imparfait', 'ils nageaient'),
    ('nager', 'elles', 'Imparfait', 'elles nageaient'),
    ('voyager', 'je', 'Imparfait', 'je voyageais'),
    ('voyager', 'tu', 'Imparfait', 'tu voyageais'),
    ('voyager', 'il', 'Imparfait', 'il voyageait'),
    ('voyager', 'elle', 'Imparfait', 'elle voyageait'),
    ('voyager', 'on', 'Imparfait', 'on voyageait'),
    ('voyager', 'nous', 'Imparfait', 'nous voyagions'),
    ('voyager', 'vous', 'Imparfait', 'vous voyagiez'),
    ('voyager', 'ils', 'Imparfait', 'ils voyageaient'),
    ('voyager', 'elles', 'Imparfait', 'elles voyageaient'),
    ('changer', 'je', 'Imparfait', 'je changeais'),
    ('changer', 'tu', 'Imparfait', 'tu changeais'),
    ('changer', 'il', 'Imparfait', 'il changeait'),
    ('changer', 'elle', 'Imparfait', 'elle changeait'),
    ('changer', 'on', 'Imparfait', 'on changeait'),
    ('changer', 'nous', 'Imparfait', 'nous changions'),
    ('changer', 'vous', 'Imparfait', 'vous changiez'),
    ('changer', 'ils', 'Imparfait', 'ils changeaient'),
    ('changer', 'elles', 'Imparfait', 'elles changeaient'),
    ('ranger', 'je', 'Imparfait', 'je rangeais'),
    ('ranger', 'tu', 'Imparfait', 'tu rangeais'),
    ('ranger', 'il', 'Imparfait', 'il rangeait'),
    ('ranger', 'elle', 'Imparfait', 'elle rangeait'),
    ('ranger', 'on', 'Imparfait', 'on rangeait'),
    ('ranger', 'nous', 'Imparfait', 'nous rangions'),
    ('ranger', 'vous', 'Imparfait', 'vous rangiez'),
    ('ranger', 'ils', 'Imparfait', 'ils rangeaient'),
    ('ranger', 'elles', 'Imparfait', 'elles rangeaient'),
    ('partager', 'je', 'Imparfait', 'je partageais'),
    ('partager', 'tu', 'Imparfait', 'tu partageais'),
    ('partager', 'il', 'Imparfait', 'il partageait'),
    ('partager', 'elle', 'Imparfait', 'elle partageait'),
    ('partager', 'on', 'Imparfait', 'on partageait'),
    ('partager', 'nous', 'Imparfait', 'nous partagions'),
    ('partager', 'vous', 'Imparfait', 'vous partagiez'),
    ('partager', 'ils', 'Imparfait', 'ils partageaient'),
    ('partager', 'elles', 'Imparfait', 'elles partageaient'),
    ('corriger', 'je', 'Imparfait', 'je corrigeais'),
    ('corriger', 'tu', 'Imparfait', 'tu corrigeais'),
    ('corriger', 'il', 'Imparfait', 'il corrigeait'),
    ('corriger', 'elle', 'Imparfait', 'elle corrigeait'),
    ('corriger', 'on', 'Imparfait', 'on corrigeait'),
    ('corriger', 'nous', 'Imparfait', 'nous corrigions'),
    ('corriger', 'vous', 'Imparfait', 'vous corrigiez'),
    ('corriger', 'ils', 'Imparfait', 'ils corrigeaient'),
    ('corriger', 'elles', 'Imparfait', 'elles corrigeaient'),
    ('protéger', 'je', 'Imparfait', 'je protégeais'),
    ('protéger', 'tu', 'Imparfait', 'tu protégeais'),
    ('protéger', 'il', 'Imparfait', 'il protégeait'),
    ('protéger', 'elle', 'Imparfait', 'elle protégeait'),
    ('protéger', 'on', 'Imparfait', 'on protégeait'),
    ('protéger', 'nous', 'Imparfait', 'nous protégions'),
    ('protéger', 'vous', 'Imparfait', 'vous protégiez'),
    ('protéger', 'ils', 'Imparfait', 'ils protégeaient'),
    ('protéger', 'elles', 'Imparfait', 'elles protégeaient'),
    ('interroger', 'je', 'Imparfait', 'j''interrogeais'),
    ('interroger', 'tu', 'Imparfait', 'tu interrogeais'),
    ('interroger', 'il', 'Imparfait', 'il interrogeait'),
    ('interroger', 'elle', 'Imparfait', 'elle interrogeait'),
    ('interroger', 'on', 'Imparfait', 'on interrogeait'),
    ('interroger', 'nous', 'Imparfait', 'nous interrogions'),
    ('interroger', 'vous', 'Imparfait', 'vous interrogiez'),
    ('interroger', 'ils', 'Imparfait', 'ils interrogeaient'),
    ('interroger', 'elles', 'Imparfait', 'elles interrogeaient'),
    ('déménager', 'je', 'Imparfait', 'je déménageais'),
    ('déménager', 'tu', 'Imparfait', 'tu déménageais'),
    ('déménager', 'il', 'Imparfait', 'il déménageait'),
    ('déménager', 'elle', 'Imparfait', 'elle déménageait'),
    ('déménager', 'on', 'Imparfait', 'on déménageait'),
    ('déménager', 'nous', 'Imparfait', 'nous déménagions'),
    ('déménager', 'vous', 'Imparfait', 'vous déménagiez'),
    ('déménager', 'ils', 'Imparfait', 'ils déménageaient'),
    ('déménager', 'elles', 'Imparfait', 'elles déménageaient'),
    ('commencer', 'je', 'Imparfait', 'je commençais'),
    ('commencer', 'tu', 'Imparfait', 'tu commençais'),
    ('commencer', 'il', 'Imparfait', 'il commençait'),
    ('commencer', 'elle', 'Imparfait', 'elle commençait'),
    ('commencer', 'on', 'Imparfait', 'on commençait'),
    ('commencer', 'nous', 'Imparfait', 'nous commencions'),
    ('commencer', 'vous', 'Imparfait', 'vous commenciez'),
    ('commencer', 'ils', 'Imparfait', 'ils commençaient'),
    ('commencer', 'elles', 'Imparfait', 'elles commençaient'),
    ('placer', 'je', 'Imparfait', 'je plaçais'),
    ('placer', 'tu', 'Imparfait', 'tu plaçais'),
    ('placer', 'il', 'Imparfait', 'il plaçait'),
    ('placer', 'elle', 'Imparfait', 'elle plaçait'),
    ('placer', 'on', 'Imparfait', 'on plaçait'),
    ('placer', 'nous', 'Imparfait', 'nous placions'),
    ('placer', 'vous', 'Imparfait', 'vous placiez'),
    ('placer', 'ils', 'Imparfait', 'ils plaçaient'),
    ('placer', 'elles', 'Imparfait', 'elles plaçaient'),
    ('annoncer', 'je', 'Imparfait', 'j''annonçais'),
    ('annoncer', 'tu', 'Imparfait', 'tu annonçais'),
    ('annoncer', 'il', 'Imparfait', 'il annonçait'),
    ('annoncer', 'elle', 'Imparfait', 'elle annonçait'),
    ('annoncer', 'on', 'Imparfait', 'on annonçait'),
    ('annoncer', 'nous', 'Imparfait', 'nous annoncions'),
    ('annoncer', 'vous', 'Imparfait', 'vous annonciez'),
    ('annoncer', 'ils', 'Imparfait', 'ils annonçaient'),
    ('annoncer', 'elles', 'Imparfait', 'elles annonçaient'),
    ('avancer', 'je', 'Imparfait', 'j''avançais'),
    ('avancer', 'tu', 'Imparfait', 'tu avançais'),
    ('avancer', 'il', 'Imparfait', 'il avançait'),
    ('avancer', 'elle', 'Imparfait', 'elle avançait'),
    ('avancer', 'on', 'Imparfait', 'on avançait'),
    ('avancer', 'nous', 'Imparfait', 'nous avancions'),
    ('avancer', 'vous', 'Imparfait', 'vous avanciez'),
    ('avancer', 'ils', 'Imparfait', 'ils avançaient'),
    ('avancer', 'elles', 'Imparfait', 'elles avançaient'),
    ('lancer', 'je', 'Imparfait', 'je lançais'),
    ('lancer', 'tu', 'Imparfait', 'tu lançais'),
    ('lancer', 'il', 'Imparfait', 'il lançait'),
    ('lancer', 'elle', 'Imparfait', 'elle lançait'),
    ('lancer', 'on', 'Imparfait', 'on lançait'),
    ('lancer', 'nous', 'Imparfait', 'nous lancions'),
    ('lancer', 'vous', 'Imparfait', 'vous lanciez'),
    ('lancer', 'ils', 'Imparfait', 'ils lançaient'),
    ('lancer', 'elles', 'Imparfait', 'elles lançaient'),
    ('prononcer', 'je', 'Imparfait', 'je prononçais'),
    ('prononcer', 'tu', 'Imparfait', 'tu prononçais'),
    ('prononcer', 'il', 'Imparfait', 'il prononçait'),
    ('prononcer', 'elle', 'Imparfait', 'elle prononçait'),
    ('prononcer', 'on', 'Imparfait', 'on prononçait'),
    ('prononcer', 'nous', 'Imparfait', 'nous prononcions'),
    ('prononcer', 'vous', 'Imparfait', 'vous prononciez'),
    ('prononcer', 'ils', 'Imparfait', 'ils prononçaient'),
    ('prononcer', 'elles', 'Imparfait', 'elles prononçaient'),
    ('renoncer', 'je', 'Imparfait', 'je renonçais'),
    ('renoncer', 'tu', 'Imparfait', 'tu renonçais'),
    ('renoncer', 'il', 'Imparfait', 'il renonçait'),
    ('renoncer', 'elle', 'Imparfait', 'elle renonçait'),
    ('renoncer', 'on', 'Imparfait', 'on renonçait'),
    ('renoncer', 'nous', 'Imparfait', 'nous renoncions'),
    ('renoncer', 'vous', 'Imparfait', 'vous renonciez'),
    ('renoncer', 'ils', 'Imparfait', 'ils renonçaient'),
    ('renoncer', 'elles', 'Imparfait', 'elles renonçaient'),
    ('effacer', 'je', 'Imparfait', 'j''effaçais'),
    ('effacer', 'tu', 'Imparfait', 'tu effaçais'),
    ('effacer', 'il', 'Imparfait', 'il effaçait'),
    ('effacer', 'elle', 'Imparfait', 'elle effaçait'),
    ('effacer', 'on', 'Imparfait', 'on effaçait'),
    ('effacer', 'nous', 'Imparfait', 'nous effacions'),
    ('effacer', 'vous', 'Imparfait', 'vous effaciez'),
    ('effacer', 'ils', 'Imparfait', 'ils effaçaient'),
    ('effacer', 'elles', 'Imparfait', 'elles effaçaient'),
    ('menacer', 'je', 'Imparfait', 'je menaçais'),
    ('menacer', 'tu', 'Imparfait', 'tu menaçais'),
    ('menacer', 'il', 'Imparfait', 'il menaçait'),
    ('menacer', 'elle', 'Imparfait', 'elle menaçait'),
    ('menacer', 'on', 'Imparfait', 'on menaçait'),
    ('menacer', 'nous', 'Imparfait', 'nous menacions'),
    ('menacer', 'vous', 'Imparfait', 'vous menaciez'),
    ('menacer', 'ils', 'Imparfait', 'ils menaçaient'),
    ('menacer', 'elles', 'Imparfait', 'elles menaçaient'),
    ('tracer', 'je', 'Imparfait', 'je traçais'),
    ('tracer', 'tu', 'Imparfait', 'tu traçais'),
    ('tracer', 'il', 'Imparfait', 'il traçait'),
    ('tracer', 'elle', 'Imparfait', 'elle traçait'),
    ('tracer', 'on', 'Imparfait', 'on traçait'),
    ('tracer', 'nous', 'Imparfait', 'nous tracions'),
    ('tracer', 'vous', 'Imparfait', 'vous traciez'),
    ('tracer', 'ils', 'Imparfait', 'ils traçaient'),
    ('tracer', 'elles', 'Imparfait', 'elles traçaient'),
    ('étudier', 'je', 'Imparfait', 'j''étudiais'),
    ('étudier', 'tu', 'Imparfait', 'tu étudiais'),
    ('étudier', 'il', 'Imparfait', 'il étudiait'),
    ('étudier', 'elle', 'Imparfait', 'elle étudiait'),
    ('étudier', 'on', 'Imparfait', 'on étudiait'),
    ('étudier', 'nous', 'Imparfait', 'nous étudiions'),
    ('étudier', 'vous', 'Imparfait', 'vous étudiiez'),
    ('étudier', 'ils', 'Imparfait', 'ils étudiaient'),
    ('étudier', 'elles', 'Imparfait', 'elles étudiaient'),
    ('crier', 'je', 'Imparfait', 'je criais'),
    ('crier', 'tu', 'Imparfait', 'tu criais'),
    ('crier', 'il', 'Imparfait', 'il criait'),
    ('crier', 'elle', 'Imparfait', 'elle criait'),
    ('crier', 'on', 'Imparfait', 'on criait'),
    ('crier', 'nous', 'Imparfait', 'nous criions'),
    ('crier', 'vous', 'Imparfait', 'vous criiez'),
    ('crier', 'ils', 'Imparfait', 'ils criaient'),
    ('crier', 'elles', 'Imparfait', 'elles criaient'),
    ('prier', 'je', 'Imparfait', 'je priais'),
    ('prier', 'tu', 'Imparfait', 'tu priais'),
    ('prier', 'il', 'Imparfait', 'il priait'),
    ('prier', 'elle', 'Imparfait', 'elle priait'),
    ('prier', 'on', 'Imparfait', 'on priait'),
    ('prier', 'nous', 'Imparfait', 'nous priions'),
    ('prier', 'vous', 'Imparfait', 'vous priiez'),
    ('prier', 'ils', 'Imparfait', 'ils priaient'),
    ('prier', 'elles', 'Imparfait', 'elles priaient'),
    ('oublier', 'je', 'Imparfait', 'j''oubliais'),
    ('oublier', 'tu', 'Imparfait', 'tu oubliais'),
    ('oublier', 'il', 'Imparfait', 'il oubliait'),
    ('oublier', 'elle', 'Imparfait', 'elle oubliait'),
    ('oublier', 'on', 'Imparfait', 'on oubliait'),
    ('oublier', 'nous', 'Imparfait', 'nous oubliions'),
    ('oublier', 'vous', 'Imparfait', 'vous oubliiez'),
    ('oublier', 'ils', 'Imparfait', 'ils oubliaient'),
    ('oublier', 'elles', 'Imparfait', 'elles oubliaient'),
    ('marier', 'je', 'Imparfait', 'je mariais'),
    ('marier', 'tu', 'Imparfait', 'tu mariais'),
    ('marier', 'il', 'Imparfait', 'il mariait'),
    ('marier', 'elle', 'Imparfait', 'elle mariait'),
    ('marier', 'on', 'Imparfait', 'on mariait'),
    ('marier', 'nous', 'Imparfait', 'nous mariions'),
    ('marier', 'vous', 'Imparfait', 'vous mariiez'),
    ('marier', 'ils', 'Imparfait', 'ils mariaient'),
    ('marier', 'elles', 'Imparfait', 'elles mariaient'),
    ('copier', 'je', 'Imparfait', 'je copiais'),
    ('copier', 'tu', 'Imparfait', 'tu copiais'),
    ('copier', 'il', 'Imparfait', 'il copiait'),
    ('copier', 'elle', 'Imparfait', 'elle copiait'),
    ('copier', 'on', 'Imparfait', 'on copiait'),
    ('copier', 'nous', 'Imparfait', 'nous copiions'),
    ('copier', 'vous', 'Imparfait', 'vous copiiez'),
    ('copier', 'ils', 'Imparfait', 'ils copiaient'),
    ('copier', 'elles', 'Imparfait', 'elles copiaient'),
    ('publier', 'je', 'Imparfait', 'je publiais'),
    ('publier', 'tu', 'Imparfait', 'tu publiais'),
    ('publier', 'il', 'Imparfait', 'il publiait'),
    ('publier', 'elle', 'Imparfait', 'elle publiait'),
    ('publier', 'on', 'Imparfait', 'on publiait'),
    ('publier', 'nous', 'Imparfait', 'nous publiions'),
    ('publier', 'vous', 'Imparfait', 'vous publiiez'),
    ('publier', 'ils', 'Imparfait', 'ils publiaient'),
    ('publier', 'elles', 'Imparfait', 'elles publiaient'),
    ('appuyer', 'je', 'Imparfait', 'j''appuyais'),
    ('appuyer', 'tu', 'Imparfait', 'tu appuyais'),
    ('appuyer', 'il', 'Imparfait', 'il appuyait'),
    ('appuyer', 'elle', 'Imparfait', 'elle appuyait'),
    ('appuyer', 'on', 'Imparfait', 'on appuyait'),
    ('appuyer', 'nous', 'Imparfait', 'nous appuyions'),
    ('appuyer', 'vous', 'Imparfait', 'vous appuyiez'),
    ('appuyer', 'ils', 'Imparfait', 'ils appuyaient'),
    ('appuyer', 'elles', 'Imparfait', 'elles appuyaient'),
    ('ennuyer', 'je', 'Imparfait', 'j''ennuyais'),
    ('ennuyer', 'tu', 'Imparfait', 'tu ennuyais'),
    ('ennuyer', 'il', 'Imparfait', 'il ennuyait'),
    ('ennuyer', 'elle', 'Imparfait', 'elle ennuyait'),
    ('ennuyer', 'on', 'Imparfait', 'on ennuyait'),
    ('ennuyer', 'nous', 'Imparfait', 'nous ennuyions'),
    ('ennuyer', 'vous', 'Imparfait', 'vous ennuyiez'),
    ('ennuyer', 'ils', 'Imparfait', 'ils ennuyaient'),
    ('ennuyer', 'elles', 'Imparfait', 'elles ennuyaient'),
    ('nettoyer', 'je', 'Imparfait', 'je nettoyais'),
    ('nettoyer', 'tu', 'Imparfait', 'tu nettoyais'),
    ('nettoyer', 'il', 'Imparfait', 'il nettoyait'),
    ('nettoyer', 'elle', 'Imparfait', 'elle nettoyait'),
    ('nettoyer', 'on', 'Imparfait', 'on nettoyait'),
    ('nettoyer', 'nous', 'Imparfait', 'nous nettoyions'),
    ('nettoyer', 'vous', 'Imparfait', 'vous nettoyiez'),
    ('nettoyer', 'ils', 'Imparfait', 'ils nettoyaient'),
    ('nettoyer', 'elles', 'Imparfait', 'elles nettoyaient')
) AS c("verb_name", "subject_name", "tense_name", "text")
JOIN "Verb" v ON v."name" = c."verb_name"
JOIN "Subject" s ON s."name" = c."subject_name"
JOIN "Tense" t ON t."name" = c."tense_name"
ON CONFLICT ("verb_id", "subject_id", "tense_id")
DO UPDATE SET "text" = EXCLUDED."text";
