INSERT INTO "Irregular" ("verb_id", "tense_id")
SELECT v."id", t."id"
FROM (
  VALUES
    ('avoir', 'Passé Composé'),
    ('être', 'Passé Composé'),
    ('faire', 'Passé Composé'),
    ('mettre', 'Passé Composé'),
    ('prendre', 'Passé Composé'),
    ('dire', 'Passé Composé'),
    ('écrire', 'Passé Composé'),
    ('voir', 'Passé Composé'),
    ('pouvoir', 'Passé Composé'),
    ('vouloir', 'Passé Composé'),
    ('savoir', 'Passé Composé'),
    ('connaître', 'Passé Composé'),
    ('venir', 'Passé Composé'),
    ('devoir', 'Passé Composé'),
    ('croire', 'Passé Composé'),
    ('boire', 'Passé Composé'),
    ('lire', 'Passé Composé'),
    ('vivre', 'Passé Composé'),
    ('recevoir', 'Passé Composé'),
    ('ouvrir', 'Passé Composé'),
    ('offrir', 'Passé Composé'),
    ('naître', 'Passé Composé'),
    ('mourir', 'Passé Composé'),
    ('tenir', 'Passé Composé'),
    ('suivre', 'Passé Composé'),
    ('rire', 'Passé Composé'),
    ('plaire', 'Passé Composé'),
    ('falloir', 'Passé Composé'),
    ('valoir', 'Passé Composé'),
    ('pleuvoir', 'Passé Composé'),
    ('apprendre', 'Passé Composé'),
    ('comprendre', 'Passé Composé'),
    ('surprendre', 'Passé Composé'),
    ('découvrir', 'Passé Composé'),
    ('souffrir', 'Passé Composé'),
    ('conduire', 'Passé Composé'),
    ('produire', 'Passé Composé'),
    ('traduire', 'Passé Composé'),
    ('atteindre', 'Passé Composé'),
    ('craindre', 'Passé Composé'),
    ('éteindre', 'Passé Composé'),
    ('joindre', 'Passé Composé'),
    ('peindre', 'Passé Composé'),
    ('clore', 'Passé Composé'),
    ('inclure', 'Passé Composé'),
    ('cuire', 'Passé Composé'),
    ('resoudre', 'Passé Composé'),
    ('absoudre', 'Passé Composé'),
    
    ('acheter', 'Présent'),
    ('aller', 'Présent'),
    ('appeler', 'Présent'),
    ('avoir', 'Présent'),
    ('boire', 'Présent'),
    ('conduire', 'Présent'),
    ('connaître', 'Présent'),
    ('courir', 'Présent'),
    ('craindre', 'Présent'),
    ('croire', 'Présent'),
    ('descendre', 'Présent'),
    ('devoir', 'Présent'),
    ('dire', 'Présent'),
    ('dormir', 'Présent'),
    ('entendre', 'Présent'),
    ('envoyer', 'Présent'),
    ('écrire', 'Présent'),
    ('être', 'Présent'),
    ('faire', 'Présent'),
    ('falloir', 'Présent'),
    ('jeter', 'Présent'),
    ('lire', 'Présent'),
    ('mettre', 'Présent'),
    ('mourir', 'Présent'),
    ('naître', 'Présent'),
    ('offrir', 'Présent'),
    ('ouvrir', 'Présent'),
    ('partir', 'Présent'),
    ('payer', 'Présent'),
    ('perdre', 'Présent'),
    ('plaire', 'Présent'),
    ('pleuvoir', 'Présent'),
    ('pouvoir', 'Présent'),
    ('préférer', 'Présent'),
    ('prendre', 'Présent'),
    ('recevoir', 'Présent'),
    ('répondre', 'Présent'),
    ('rire', 'Présent'),
    ('savoir', 'Présent'),
    ('servir', 'Présent'),
    ('sortir', 'Présent'),
    ('suivre', 'Présent'),
    ('tenir', 'Présent'),
    ('valoir', 'Présent'),
    ('vendre', 'Présent'),
    ('venir', 'Présent'),
    ('vivre', 'Présent'),
    ('voir', 'Présent'),
    ('vouloir', 'Présent'),

    ('être', 'Imparfait'),
    ('manger', 'Imparfait'),
    ('nager', 'Imparfait'),
    ('voyager', 'Imparfait'),
    ('changer', 'Imparfait'),
    ('ranger', 'Imparfait'),
    ('partager', 'Imparfait'),
    ('corriger', 'Imparfait'),
    ('protéger', 'Imparfait'),
    ('interroger', 'Imparfait'),
    ('déménager', 'Imparfait'),
    ('commencer', 'Imparfait'),
    ('placer', 'Imparfait'),
    ('annoncer', 'Imparfait'),
    ('avancer', 'Imparfait'),
    ('lancer', 'Imparfait'),
    ('prononcer', 'Imparfait'),
    ('renoncer', 'Imparfait'),
    ('effacer', 'Imparfait'),
    ('menacer', 'Imparfait'),
    ('tracer', 'Imparfait'),
    ('étudier', 'Imparfait'),
    ('crier', 'Imparfait'),
    ('prier', 'Imparfait'),
    ('oublier', 'Imparfait'),
    ('marier', 'Imparfait'),
    ('copier', 'Imparfait'),
    ('publier', 'Imparfait'),
    ('appuyer', 'Imparfait'),
    ('ennuyer', 'Imparfait'),
    ('nettoyer', 'Imparfait'),

    ('s’interroger', 'Imparfait'),
    ('s’ennuyer', 'Imparfait'),
    ('se marier', 'Imparfait')
) AS i("verb_name", "tense_name")
JOIN "Verb" v ON v."name" = i."verb_name"
JOIN "Tense" t ON t."name" = i."tense_name"
ON CONFLICT ("verb_id", "tense_id") DO NOTHING;
