WITH input("text", "placement", "tense_name") AS (
  VALUES
    ('hier', 'beginningOfSentence', 'Passé Composé'),
    ('avant-hier', 'beginningOfSentence', 'Passé Composé'),
    ('hier matin', 'beginningOfSentence', 'Passé Composé'),
    ('hier soir', 'beginningOfSentence', 'Passé Composé'),
    ('hier après-midi', 'beginningOfSentence', 'Passé Composé'),
    ('ce matin', 'beginningOfSentence', 'Passé Composé'),
    ('dans la matinée', 'beginningOfSentence', 'Passé Composé'),
    ('en fin de matinée', 'beginningOfSentence', 'Passé Composé'),
    ('ce midi', 'beginningOfSentence', 'Passé Composé'),
    ('en début d’après-midi', 'beginningOfSentence', 'Passé Composé'),
    ('cet après-midi', 'beginningOfSentence', 'Passé Composé'),
    ('en fin d’après-midi', 'beginningOfSentence', 'Passé Composé'),
    ('en début de soirée', 'beginningOfSentence', 'Passé Composé'),
    ('ce soir', 'beginningOfSentence', 'Passé Composé'),
    ('dans la soirée', 'beginningOfSentence', 'Passé Composé'),
    ('cette nuit', 'beginningOfSentence', 'Passé Composé'),
    ('en pleine nuit', 'beginningOfSentence', 'Passé Composé'),
    ('la semaine dernière', 'beginningOfSentence', 'Passé Composé'),
    ('le week-end dernier', 'beginningOfSentence', 'Passé Composé'),
    ('le mois dernier', 'beginningOfSentence', 'Passé Composé'),
    ('l’année dernière', 'beginningOfSentence', 'Passé Composé'),
    ('l’hiver dernier', 'beginningOfSentence', 'Passé Composé'),
    ('le printemps dernier', 'beginningOfSentence', 'Passé Composé'),
    ('l’été dernier', 'beginningOfSentence', 'Passé Composé'),
    ('l’automne dernier', 'beginningOfSentence', 'Passé Composé'),
    ('lundi dernier', 'beginningOfSentence', 'Passé Composé'),
    ('mardi dernier', 'beginningOfSentence', 'Passé Composé'),
    ('mercredi dernier', 'beginningOfSentence', 'Passé Composé'),
    ('jeudi dernier', 'beginningOfSentence', 'Passé Composé'),
    ('vendredi dernier', 'beginningOfSentence', 'Passé Composé'),
    ('samedi dernier', 'beginningOfSentence', 'Passé Composé'),
    ('dimanche dernier', 'beginningOfSentence', 'Passé Composé'),
    ('à Noël', 'beginningOfSentence', 'Passé Composé'),
    ('à Pâques', 'beginningOfSentence', 'Passé Composé'),
    ('à la Saint-Valentin', 'beginningOfSentence', 'Passé Composé'),
    ('à Halloween', 'beginningOfSentence', 'Passé Composé'),
    ('à la Fête nationale', 'beginningOfSentence', 'Passé Composé'),
    ('Noël dernier', 'beginningOfSentence', 'Passé Composé'),
    ('Pâques dernier', 'beginningOfSentence', 'Passé Composé'),
    ('la dernière fête de Pâques', 'beginningOfSentence', 'Passé Composé'),
    ('à la fête de la musique', 'beginningOfSentence', 'Passé Composé'),
    ('à la Toussaint', 'beginningOfSentence', 'Passé Composé'),
    ('à la fête des pères', 'beginningOfSentence', 'Passé Composé'),
    ('à la fête des mères', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de janvier', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de février', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de mars', 'beginningOfSentence', 'Passé Composé'),
    ('au mois d''avril', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de mai', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de juin', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de juillet', 'beginningOfSentence', 'Passé Composé'),
    ('au mois d''août', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de septembre', 'beginningOfSentence', 'Passé Composé'),
    ('au mois d''octobre', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de novembre', 'beginningOfSentence', 'Passé Composé'),
    ('au mois de décembre', 'beginningOfSentence', 'Passé Composé'),
    ('il y a une minute', 'beginningOfSentence', 'Passé Composé'),
    ('il y a cinq minutes', 'beginningOfSentence', 'Passé Composé'),
    ('il y a dix minutes', 'beginningOfSentence', 'Passé Composé'),
    ('il y a quinze minutes', 'beginningOfSentence', 'Passé Composé'),
    ('il y a trente minutes', 'beginningOfSentence', 'Passé Composé'),
    ('une demi-heure', 'beginningOfSentence', 'Passé Composé'),
    ('il y a une heure', 'beginningOfSentence', 'Passé Composé'),
    ('il y a deux heures', 'beginningOfSentence', 'Passé Composé'),
    ('il y a trois heures', 'beginningOfSentence', 'Passé Composé'),
    ('il y a un jour', 'beginningOfSentence', 'Passé Composé'),
    ('il y a deux jours', 'beginningOfSentence', 'Passé Composé'),
    ('il y a trois jours', 'beginningOfSentence', 'Passé Composé'),
    ('il y a quatre jours', 'beginningOfSentence', 'Passé Composé'),
    ('il y a dix jours', 'beginningOfSentence', 'Passé Composé'),
    ('il y a une semaine', 'beginningOfSentence', 'Passé Composé'),
    ('il y a deux semaines', 'beginningOfSentence', 'Passé Composé'),
    ('il y a trois semaines', 'beginningOfSentence', 'Passé Composé'),
    ('il y a un mois', 'beginningOfSentence', 'Passé Composé'),
    ('il y a deux mois', 'beginningOfSentence', 'Passé Composé'),
    ('il y a trois mois', 'beginningOfSentence', 'Passé Composé'),
    ('il y a six mois', 'beginningOfSentence', 'Passé Composé'),
    ('il y a un an', 'beginningOfSentence', 'Passé Composé'),
    ('il y a deux ans', 'beginningOfSentence', 'Passé Composé'),
    ('il y a trois ans', 'beginningOfSentence', 'Passé Composé'),
    ('il y a quatre ans', 'beginningOfSentence', 'Passé Composé'),
    ('il y a cinq ans', 'beginningOfSentence', 'Passé Composé'),
    ('il y a plusieurs années', 'beginningOfSentence', 'Passé Composé'),
    ('en 1996', 'beginningOfSentence', 'Passé Composé'),
    ('en 1997', 'beginningOfSentence', 'Passé Composé'),
    ('en 1998', 'beginningOfSentence', 'Passé Composé'),
    ('en 1999', 'beginningOfSentence', 'Passé Composé'),
    ('en 2000', 'beginningOfSentence', 'Passé Composé'),
    ('en 2001', 'beginningOfSentence', 'Passé Composé'),
    ('en 2002', 'beginningOfSentence', 'Passé Composé'),
    ('en 2003', 'beginningOfSentence', 'Passé Composé'),
    ('en 2004', 'beginningOfSentence', 'Passé Composé'),
    ('en 2005', 'beginningOfSentence', 'Passé Composé'),
    ('en 2006', 'beginningOfSentence', 'Passé Composé'),
    ('en 2007', 'beginningOfSentence', 'Passé Composé'),
    ('en 2008', 'beginningOfSentence', 'Passé Composé'),
    ('en 2009', 'beginningOfSentence', 'Passé Composé'),
    ('en 2010', 'beginningOfSentence', 'Passé Composé'),
    ('en 2011', 'beginningOfSentence', 'Passé Composé'),
    ('en 2012', 'beginningOfSentence', 'Passé Composé'),
    ('en 2013', 'beginningOfSentence', 'Passé Composé'),
    ('en 2014', 'beginningOfSentence', 'Passé Composé'),
    ('en 2015', 'beginningOfSentence', 'Passé Composé'),
    ('en 2016', 'beginningOfSentence', 'Passé Composé'),
    ('en 2017', 'beginningOfSentence', 'Passé Composé'),
    ('en 2018', 'beginningOfSentence', 'Passé Composé'),
    ('en 2019', 'beginningOfSentence', 'Passé Composé'),
    ('en 2020', 'beginningOfSentence', 'Passé Composé'),
    ('en 2021', 'beginningOfSentence', 'Passé Composé'),
    ('en 2022', 'beginningOfSentence', 'Passé Composé'),
    ('en 2023', 'beginningOfSentence', 'Passé Composé'),
    ('en 2024', 'beginningOfSentence', 'Passé Composé'),
    ('hier', 'endOfSentence', 'Passé Composé'),
    ('avant-hier', 'endOfSentence', 'Passé Composé'),
    ('hier matin', 'endOfSentence', 'Passé Composé'),
    ('hier soir', 'endOfSentence', 'Passé Composé'),
    ('hier après-midi', 'endOfSentence', 'Passé Composé'),
    ('ce matin', 'endOfSentence', 'Passé Composé'),
    ('dans la matinée', 'endOfSentence', 'Passé Composé'),
    ('en fin de matinée', 'endOfSentence', 'Passé Composé'),
    ('ce midi', 'endOfSentence', 'Passé Composé'),
    ('en début d’après-midi', 'endOfSentence', 'Passé Composé'),
    ('cet après-midi', 'endOfSentence', 'Passé Composé'),
    ('en fin d’après-midi', 'endOfSentence', 'Passé Composé'),
    ('en début de soirée', 'endOfSentence', 'Passé Composé'),
    ('ce soir', 'endOfSentence', 'Passé Composé'),
    ('dans la soirée', 'endOfSentence', 'Passé Composé'),
    ('cette nuit', 'endOfSentence', 'Passé Composé'),
    ('en pleine nuit', 'endOfSentence', 'Passé Composé'),
    ('la semaine dernière', 'endOfSentence', 'Passé Composé'),
    ('le week-end dernier', 'endOfSentence', 'Passé Composé'),
    ('le mois dernier', 'endOfSentence', 'Passé Composé'),
    ('l’année dernière', 'endOfSentence', 'Passé Composé'),
    ('l’hiver dernier', 'endOfSentence', 'Passé Composé'),
    ('le printemps dernier', 'endOfSentence', 'Passé Composé'),
    ('l’été dernier', 'endOfSentence', 'Passé Composé'),
    ('l’automne dernier', 'endOfSentence', 'Passé Composé'),
    ('lundi dernier', 'endOfSentence', 'Passé Composé'),
    ('mardi dernier', 'endOfSentence', 'Passé Composé'),
    ('mercredi dernier', 'endOfSentence', 'Passé Composé'),
    ('jeudi dernier', 'endOfSentence', 'Passé Composé'),
    ('vendredi dernier', 'endOfSentence', 'Passé Composé'),
    ('samedi dernier', 'endOfSentence', 'Passé Composé'),
    ('dimanche dernier', 'endOfSentence', 'Passé Composé'),
    ('à Noël', 'endOfSentence', 'Passé Composé'),
    ('à Pâques', 'endOfSentence', 'Passé Composé'),
    ('à la Saint-Valentin', 'endOfSentence', 'Passé Composé'),
    ('à Halloween', 'endOfSentence', 'Passé Composé'),
    ('à la Fête nationale', 'endOfSentence', 'Passé Composé'),
    ('Noël dernier', 'endOfSentence', 'Passé Composé'),
    ('Pâques dernier', 'endOfSentence', 'Passé Composé'),
    ('la dernière fête de Pâques', 'endOfSentence', 'Passé Composé'),
    ('à la fête de la musique', 'endOfSentence', 'Passé Composé'),
    ('à la Toussaint', 'endOfSentence', 'Passé Composé'),
    ('à la fête des pères', 'endOfSentence', 'Passé Composé'),
    ('à la fête des mères', 'endOfSentence', 'Passé Composé'),
    ('au mois de janvier', 'endOfSentence', 'Passé Composé'),
    ('au mois de février', 'endOfSentence', 'Passé Composé'),
    ('au mois de mars', 'endOfSentence', 'Passé Composé'),
    ('au mois d''avril', 'endOfSentence', 'Passé Composé'),
    ('au mois de mai', 'endOfSentence', 'Passé Composé'),
    ('au mois de juin', 'endOfSentence', 'Passé Composé'),
    ('au mois de juillet', 'endOfSentence', 'Passé Composé'),
    ('au mois d''août', 'endOfSentence', 'Passé Composé'),
    ('au mois de septembre', 'endOfSentence', 'Passé Composé'),
    ('au mois d''octobre', 'endOfSentence', 'Passé Composé'),
    ('au mois de novembre', 'endOfSentence', 'Passé Composé'),
    ('au mois de décembre', 'endOfSentence', 'Passé Composé'),
    ('il y a une minute', 'endOfSentence', 'Passé Composé'),
    ('il y a cinq minutes', 'endOfSentence', 'Passé Composé'),
    ('il y a dix minutes', 'endOfSentence', 'Passé Composé'),
    ('il y a quinze minutes', 'endOfSentence', 'Passé Composé'),
    ('il y a trente minutes', 'endOfSentence', 'Passé Composé'),
    ('une demi-heure', 'endOfSentence', 'Passé Composé'),
    ('il y a une heure', 'endOfSentence', 'Passé Composé'),
    ('il y a deux heures', 'endOfSentence', 'Passé Composé'),
    ('il y a trois heures', 'endOfSentence', 'Passé Composé'),
    ('il y a un jour', 'endOfSentence', 'Passé Composé'),
    ('il y a deux jours', 'endOfSentence', 'Passé Composé'),
    ('il y a trois jours', 'endOfSentence', 'Passé Composé'),
    ('il y a quatre jours', 'endOfSentence', 'Passé Composé'),
    ('il y a dix jours', 'endOfSentence', 'Passé Composé'),
    ('il y a une semaine', 'endOfSentence', 'Passé Composé'),
    ('il y a deux semaines', 'endOfSentence', 'Passé Composé'),
    ('il y a trois semaines', 'endOfSentence', 'Passé Composé'),
    ('il y a un mois', 'endOfSentence', 'Passé Composé'),
    ('il y a deux mois', 'endOfSentence', 'Passé Composé'),
    ('il y a trois mois', 'endOfSentence', 'Passé Composé'),
    ('il y a six mois', 'endOfSentence', 'Passé Composé'),
    ('il y a un an', 'endOfSentence', 'Passé Composé'),
    ('il y a deux ans', 'endOfSentence', 'Passé Composé'),
    ('il y a trois ans', 'endOfSentence', 'Passé Composé'),
    ('il y a quatre ans', 'endOfSentence', 'Passé Composé'),
    ('il y a cinq ans', 'endOfSentence', 'Passé Composé'),
    ('il y a plusieurs années', 'endOfSentence', 'Passé Composé'),
    ('en 1996', 'endOfSentence', 'Passé Composé'),
    ('en 1997', 'endOfSentence', 'Passé Composé'),
    ('en 1998', 'endOfSentence', 'Passé Composé'),
    ('en 1999', 'endOfSentence', 'Passé Composé'),
    ('en 2000', 'endOfSentence', 'Passé Composé'),
    ('en 2001', 'endOfSentence', 'Passé Composé'),
    ('en 2002', 'endOfSentence', 'Passé Composé'),
    ('en 2003', 'endOfSentence', 'Passé Composé'),
    ('en 2004', 'endOfSentence', 'Passé Composé'),
    ('en 2005', 'endOfSentence', 'Passé Composé'),
    ('en 2006', 'endOfSentence', 'Passé Composé'),
    ('en 2007', 'endOfSentence', 'Passé Composé'),
    ('en 2008', 'endOfSentence', 'Passé Composé'),
    ('en 2009', 'endOfSentence', 'Passé Composé'),
    ('en 2010', 'endOfSentence', 'Passé Composé'),
    ('en 2011', 'endOfSentence', 'Passé Composé'),
    ('en 2012', 'endOfSentence', 'Passé Composé'),
    ('en 2013', 'endOfSentence', 'Passé Composé'),
    ('en 2014', 'endOfSentence', 'Passé Composé'),
    ('en 2015', 'endOfSentence', 'Passé Composé'),
    ('en 2016', 'endOfSentence', 'Passé Composé'),
    ('en 2017', 'endOfSentence', 'Passé Composé'),
    ('en 2018', 'endOfSentence', 'Passé Composé'),
    ('en 2019', 'endOfSentence', 'Passé Composé'),
    ('en 2020', 'endOfSentence', 'Passé Composé'),
    ('en 2021', 'endOfSentence', 'Passé Composé'),
    ('en 2022', 'endOfSentence', 'Passé Composé'),
    ('en 2023', 'endOfSentence', 'Passé Composé'),
    ('en 2024', 'endOfSentence', 'Passé Composé'),
    ('d’abord', 'beginningOfSentence', 'Passé Composé'),
    ('ensuite', 'beginningOfSentence', 'Passé Composé'),
    ('puis', 'beginningOfSentence', 'Passé Composé'),
    ('enfin', 'beginningOfSentence', 'Passé Composé'),
    ('après cela', 'beginningOfSentence', 'Passé Composé'),
    ('soudain', 'beginningOfSentence', 'Passé Composé'),
    ('tout à coup', 'beginningOfSentence', 'Passé Composé'),
    ('aujourd''hui', 'beginningOfSentence', 'Présent'),
    ('aujourd''hui', 'endOfSentence', 'Présent'),
    ('maintenant', 'beginningOfSentence', 'Présent'),
    ('maintenant', 'endOfSentence', 'Présent'),
    ('en ce moment', 'beginningOfSentence', 'Présent'),
    ('en ce moment', 'endOfSentence', 'Présent'),
    ('actuellement', 'beginningOfSentence', 'Présent'),
    ('dès à présent', 'beginningOfSentence', 'Présent'),
    ('à l''instant', 'beginningOfSentence', 'Présent'),
    ('tous les jours', 'beginningOfSentence', 'Présent'),
    ('tous les jours', 'endOfSentence', 'Présent'),
    ('chaque jour', 'beginningOfSentence', 'Présent'),
    ('chaque jour', 'endOfSentence', 'Présent'),
    ('souvent', 'beginningOfSentence', 'Présent'),
    ('souvent', 'endOfSentence', 'Présent'),
    ('toujours', 'beginningOfSentence', 'Présent'),
    ('toujours', 'endOfSentence', 'Présent'),
    ('d’habitude', 'beginningOfSentence', 'Présent'),
    ('d’habitude', 'endOfSentence', 'Présent'),
    ('parfois', 'beginningOfSentence', 'Présent'),
    ('parfois', 'endOfSentence', 'Présent'),
    ('de temps en temps', 'beginningOfSentence', 'Présent'),
    ('de temps en temps', 'endOfSentence', 'Présent'),
    ('rarement', 'beginningOfSentence', 'Présent'),
    ('rarement', 'endOfSentence', 'Présent'),
    ('déjà', 'beginningOfSentence', 'Présent'),
    ('déjà', 'endOfSentence', 'Présent'),
    ('encore', 'beginningOfSentence', 'Présent'),
    ('encore', 'endOfSentence', 'Présent'),
    ('jamais', 'beginningOfSentence', 'Présent'),
    ('jamais', 'endOfSentence', 'Présent'),
    ('régulièrement', 'beginningOfSentence', 'Présent'),
    ('régulièrement', 'endOfSentence', 'Présent'),
    ('normalement', 'beginningOfSentence', 'Présent'),
    ('normalement', 'endOfSentence', 'Présent'),
    ('généralement', 'beginningOfSentence', 'Présent'),
    ('généralement', 'endOfSentence', 'Présent'),
    ('habituellement', 'beginningOfSentence', 'Présent'),
    ('habituellement', 'endOfSentence', 'Présent'),
    ('en général', 'beginningOfSentence', 'Présent'),
    ('en général', 'endOfSentence', 'Présent'),
    ('tous les matins', 'beginningOfSentence', 'Présent'),
    ('tous les matins', 'endOfSentence', 'Présent'),
    ('toutes les semaines', 'beginningOfSentence', 'Présent'),
    ('toutes les semaines', 'endOfSentence', 'Présent'),
    ('chaque semaine', 'beginningOfSentence', 'Présent'),
    ('chaque semaine', 'endOfSentence', 'Présent'),
    ('chaque mois', 'beginningOfSentence', 'Présent'),
    ('chaque mois', 'endOfSentence', 'Présent'),
    ('tous les mois', 'beginningOfSentence', 'Présent'),
    ('tous les mois', 'endOfSentence', 'Présent'),
    ('tous les ans', 'beginningOfSentence', 'Présent'),
    ('tous les ans', 'endOfSentence', 'Présent'),
    ('chaque année', 'beginningOfSentence', 'Présent'),
    ('chaque année', 'endOfSentence', 'Présent'),
    ('en permanence', 'beginningOfSentence', 'Présent'),
    ('en permanence', 'endOfSentence', 'Présent'),
    ('à présent', 'beginningOfSentence', 'Présent'),
    ('à présent', 'endOfSentence', 'Présent'),
    ('en ce jour', 'beginningOfSentence', 'Présent'),
    ('en ce jour', 'endOfSentence', 'Présent'),
    ('à chaque instant', 'beginningOfSentence', 'Présent'),
    ('à chaque instant', 'endOfSentence', 'Présent'),
    ('tout le temps', 'beginningOfSentence', 'Présent'),
    ('tout le temps', 'endOfSentence', 'Présent')
)
INSERT INTO "TimeMarker" ("text", "placement", "tense_id")
SELECT i."text", i."placement", t."id"
FROM input i
JOIN "Tense" t ON t."name" = i."tense_name"
LEFT JOIN "TimeMarker" tm
  ON tm."text" = i."text"
 AND tm."placement" = i."placement"
 AND tm."tense_id" = t."id"
WHERE tm."id" IS NULL;
