// avoir, être, faire, mettre, prendre, dire, écrire, voir, pouvoir, vouloir, savoir, connaître, venir, devoir, croire, boire, lire, vivre, recevoir, ouvrir, offrir, naître, mourir, tenir, suivre, rire, plaire, falloir, valoir, pleuvoir, apprendre, comprendre, surprendre, découvrir, souffrir, conduire, produire, traduire, atteindre, craindre, éteindre, joindre, peindre
// manger, boire, dormir, lire, écrire, parler, écouter, regarder, travailler, étudier, acheter, vendre, payer, cuisiner, marcher, courir, conduire, attendre, chercher, trouver, aimer, adorer, détester, préférer, vouloir, pouvoir, devoir, espérer, croire, penser, savoir, se souvenir, oublier, regretter, avoir peur, se sentir, aller, venir, arriver, partir, entrer, sortir, monter, descendre, tomber, rester, retourner, passer, naître, mourir, devenir, revenir, se lever, s’habiller, se coucher, se réveiller, s’endormir, se dépêcher, s’amuser, s’ennuyer, s’énerver, se tromper, se rendre compte


export const conjugaisonPasseCompose: Record<string, Record<string, string>> = {
  'être': {
    'je': "j'ai été",
    'tu': "tu as été",
    'il': "il a été",
    'elle': "elle a été",
    'on': "on a été",
    'nous': "nous avons été",
    'vous': "vous avez été",
    'ils': "ils ont été",
    'elles': "elles ont été"
  },
  'avoir': {
    'je': "j'ai eu",
    'tu': "tu as eu",
    'il': "il a eu",
    'elle': "elle a eu",
    'on': "on a eu",
    'nous': "nous avons eu",
    'vous': "vous avez eu",
    'ils': "ils ont eu",
    'elles': "elles ont eu"
  },
  'faire': {
    'je': "j'ai fait",
    'tu': "tu as fait",
    'il': "il a fait",
    'elle': "elle a fait",
    'on': "on a fait",
    'nous': "nous avons fait",
    'vous': "vous avez fait",
    'ils': "ils ont fait",
    'elles': "elles ont fait"
  },
  'mettre': {
    'je': "j'ai mis",
    'tu': "tu as mis",
    'il': "il a mis",
    'elle': "elle a mis",
    'on': "on a mis",
    'nous': "nous avons mis",
    'vous': "vous avez mis",
    'ils': "ils ont mis",
    'elles': "elles ont mis"
  },
  'prendre': {
    'je': "j'ai pris",
    'tu': "tu as pris",
    'il': "il a pris",
    'elle': "elle a pris",
    'on': "on a pris",
    'nous': "nous avons pris",
    'vous': "vous avez pris",
    'ils': "ils ont pris",
    'elles': "elles ont pris"
  },
  'dire': {
    'je': "j'ai dit",
    'tu': "tu as dit",
    'il': "il a dit",
    'elle': "elle a dit",
    'on': "on a dit",
    'nous': "nous avons dit",
    'vous': "vous avez dit",
    'ils': "ils ont dit",
    'elles': "elles ont dit"
  },
  'écrire': {
    'je': "j'ai écrit",
    'tu': "tu as écrit",
    'il': "il a écrit",
    'elle': "elle a écrit",
    'on': "on a écrit",
    'nous': "nous avons écrit",
    'vous': "vous avez écrit",
    'ils': "ils ont écrit",
    'elles': "elles ont écrit"
  },
  'voir': {
    'je': "j'ai vu",
    'tu': "tu as vu",
    'il': "il a vu",
    'elle': "elle a vu",
    'on': "on a vu",
    'nous': "nous avons vu",
    'vous': "vous avez vu",
    'ils': "ils ont vu",
    'elles': "elles ont vu"
  },
  'pouvoir': {
    'je': "j'ai pu",
    'tu': "tu as pu",
    'il': "il a pu",
    'elle': "elle a pu",
    'on': "on a pu",
    'nous': "nous avons pu",
    'vous': "vous avez pu",
    'ils': "ils ont pu",
    'elles': "elles ont pu"
  },
  'vouloir': {
    'je': "j'ai voulu",
    'tu': "tu as voulu",
    'il': "il a voulu",
    'elle': "elle a voulu",
    'on': "on a voulu",
    'nous': "nous avons voulu",
    'vous': "vous avez voulu",
    'ils': "ils ont voulu",
    'elles': "elles ont voulu"
  },
  'savoir': {
    'je': "j'ai su",
    'tu': "tu as su",
    'il': "il a su",
    'elle': "elle a su",
    'on': "on a su",
    'nous': "nous avons su",
    'vous': "vous avez su",
    'ils': "ils ont su",
    'elles': "elles ont su"
  },
  'connaître': {
    'je': "j'ai connu",
    'tu': "tu as connu",
    'il': "il a connu",
    'elle': "elle a connu",
    'on': "on a connu",
    'nous': "nous avons connu",
    'vous': "vous avez connu",
    'ils': "ils ont connu",
    'elles': "elles ont connu"
  },
  'venir': {
    'je': "je suis venu",
    'tu': "tu es venu",
    'il': "il est venu",
    'elle': "elle est venue",
    'on': "on est venu",
    'nous': "nous sommes venus",
    'vous': "vous êtes venus",
    'ils': "ils sont venus",
    'elles': "elles sont venues"
  },
  'devoir': {
    'je': "j'ai dû",
    'tu': "tu as dû",
    'il': "il a dû",
    'elle': "elle a dû",
    'on': "on a dû",
    'nous': "nous avons dû",
    'vous': "vous avez dû",
    'ils': "ils ont dû",
    'elles': "elles ont dû"
  },
  'croire': {
    'je': "j'ai cru",
    'tu': "tu as cru",
    'il': "il a cru",
    'elle': "elle a cru",
    'on': "on a cru",
    'nous': "nous avons cru",
    'vous': "vous avez cru",
    'ils': "ils ont cru",
    'elles': "elles ont cru"
  },
  'boire': {
    'je': "j'ai bu",
    'tu': "tu as bu",
    'il': "il a bu",
    'elle': "elle a bu",
    'on': "on a bu",
    'nous': "nous avons bu",
    'vous': "vous avez bu",
    'ils': "ils ont bu",
    'elles': "elles ont bu"
  },
  'lire': {
    'je': "j'ai lu",
    'tu': "tu as lu",
    'il': "il a lu",
    'elle': "elle a lu",
    'on': "on a lu",
    'nous': "nous avons lu",
    'vous': "vous avez lu",
    'ils': "ils ont lu",
    'elles': "elles ont lu"
  },
  'vivre': {
    'je': "j'ai vécu",
    'tu': "tu as vécu",
    'il': "il a vécu",
    'elle': "elle a vécu",
    'on': "on a vécu",
    'nous': "nous avons vécu",
    'vous': "vous avez vécu",
    'ils': "ils ont vécu",
    'elles': "elles ont vécu"
  },
  'recevoir': {
    'je': "j'ai reçu",
    'tu': "tu as reçu",
    'il': "il a reçu",
    'elle': "elle a reçu",
    'on': "on a reçu",
    'nous': "nous avons reçu",
    'vous': "vous avez reçu",
    'ils': "ils ont reçu",
    'elles': "elles ont reçu"
  },
  'ouvrir': {
    'je': "j'ai ouvert",
    'tu': "tu as ouvert",
    'il': "il a ouvert",
    'elle': "elle a ouvert",
    'on': "on a ouvert",
    'nous': "nous avons ouvert",
    'vous': "vous avez ouvert",
    'ils': "ils ont ouvert",
    'elles': "elles ont ouvert"
  },
  'offrir': {
    'je': "j'ai offert",
    'tu': "tu as offert",
    'il': "il a offert",
    'elle': "elle a offert",
    'on': "on a offert",
    'nous': "nous avons offert",
    'vous': "vous avez offert",
    'ils': "ils ont offert",
    'elles': "elles ont offert"
  },
  'naître': {
    'je': "je suis né",
    'tu': "tu es né",
    'il': "il est né",
    'elle': "elle est née",
    'on': "on est né",
    'nous': "nous sommes nés",
    'vous': "vous êtes nés",
    'ils': "ils sont nés",
    'elles': "elles sont nées"
  },
  'mourir': {
    'je': "je suis mort",
    'tu': "tu es mort",
    'il': "il est mort",
    'elle': "elle est morte",
    'on': "on est mort",
    'nous': "nous sommes morts",
    'vous': "vous êtes morts",
    'ils': "ils sont morts",
    'elles': "elles sont mortes"
  },
  'tenir': {
    'je': "j'ai tenu",
    'tu': "tu as tenu",
    'il': "il a tenu",
    'elle': "elle a tenu",
    'on': "on a tenu",
    'nous': "nous avons tenu",
    'vous': "vous avez tenu",
    'ils': "ils ont tenu",
    'elles': "elles ont tenu"
  },
  'suivre': {
    'je': "j'ai suivi",
    'tu': "tu as suivi",
    'il': "il a suivi",
    'elle': "elle a suivi",
    'on': "on a suivi",
    'nous': "nous avons suivi",
    'vous': "vous avez suivi",
    'ils': "ils ont suivi",
    'elles': "elles ont suivi"
  },
  'rire': {
    'je': "j'ai ri",
    'tu': "tu as ri",
    'il': "il a ri",
    'elle': "elle a ri",
    'on': "on a ri",
    'nous': "nous avons ri",
    'vous': "vous avez ri",
    'ils': "ils ont ri",
    'elles': "elles ont ri"
  },
  'plaire': {
    'je': "j'ai plu",
    'tu': "tu as plu",
    'il': "il a plu",
    'elle': "elle a plu",
    'on': "on a plu",
    'nous': "nous avons plu",
    'vous': "vous avez plu",
    'ils': "ils ont plu",
    'elles': "elles ont plu"
  },
  'falloir': {
    'je': "j'ai fallu",
    'tu': "tu as fallu",
    'il': "il a fallu",
    'elle': "elle a fallu",
    'on': "on a fallu",
    'nous': "nous avons fallu",
    'vous': "vous avez fallu",
    'ils': "ils ont fallu",
    'elles': "elles ont fallu"
  },
  'valoir': {
    'je': "j'ai valu",
    'tu': "tu as valu",
    'il': "il a valu",
    'elle': "elle a valu",
    'on': "on a valu",
    'nous': "nous avons valu",
    'vous': "vous avez valu",
    'ils': "ils ont valu",
    'elles': "elles ont valu"
  },
  'pleuvoir': {
    'je': "il a plu",
    'tu': "il a plu",
    'il': "il a plu",
    'elle': "il a plu",
    'on': "il a plu",
    'nous': "il a plu",
    'vous': "il a plu",
    'ils': "il a plu",
    'elles': "il a plu"
  },
  'apprendre': {
    'je': "j'ai appris",
    'tu': "tu as appris",
    'il': "il a appris",
    'elle': "elle a appris",
    'on': "on a appris",
    'nous': "nous avons appris",
    'vous': "vous avez appris",
    'ils': "ils ont appris",
    'elles': "elles ont appris"
  },
  'comprendre': {
    'je': "j'ai compris",
    'tu': "tu as compris",
    'il': "il a compris",
    'elle': "elle a compris",
    'on': "on a compris",
    'nous': "nous avons compris",
    'vous': "vous avez compris",
    'ils': "ils ont compris",
    'elles': "elles ont compris"
  },
  'surprendre': {
    'je': "j'ai surpris",
    'tu': "tu as surpris",
    'il': "il a surpris",
    'elle': "elle a surpris",
    'on': "on a surpris",
    'nous': "nous avons surpris",
    'vous': "vous avez surpris",
    'ils': "ils ont surpris",
    'elles': "elles ont surpris"
  },
  'découvrir': {
    'je': "j'ai découvert",
    'tu': "tu as découvert",
    'il': "il a découvert",
    'elle': "elle a découvert",
    'on': "on a découvert",
    'nous': "nous avons découvert",
    'vous': "vous avez découvert",
    'ils': "ils ont découvert",
    'elles': "elles ont découvert"
  },
  'souffrir': {
    'je': "j'ai souffert",
    'tu': "tu as souffert",
    'il': "il a souffert",
    'elle': "elle a souffert",
    'on': "on a souffert",
    'nous': "nous avons souffert",
    'vous': "vous avez souffert",
    'ils': "ils ont souffert",
    'elles': "elles ont souffert"
  },
  'conduire': {
    'je': "j'ai conduit",
    'tu': "tu as conduit",
    'il': "il a conduit",
    'elle': "elle a conduit",
    'on': "on a conduit",
    'nous': "nous avons conduit",
    'vous': "vous avez conduit",
    'ils': "ils ont conduit",
    'elles': "elles ont conduit"
  },
  'produire': {
    'je': "j'ai produit",
    'tu': "tu as produit",
    'il': "il a produit",
    'elle': "elle a produit",
    'on': "on a produit",
    'nous': "nous avons produit",
    'vous': "vous avez produit",
    'ils': "ils ont produit",
    'elles': "elles ont produit"
  },
  'traduire': {
    'je': "j'ai traduit",
    'tu': "tu as traduit",
    'il': "il a traduit",
    'elle': "elle a traduit",
    'on': "on a traduit",
    'nous': "nous avons traduit",
    'vous': "vous avez traduit",
    'ils': "ils ont traduit",
    'elles': "elles ont traduit"
  },
  'atteindre': {
    'je': "j'ai atteint",
    'tu': "tu as atteint",
    'il': "il a atteint",
    'elle': "elle a atteint",
    'on': "on a atteint",
    'nous': "nous avons atteint",
    'vous': "vous avez atteint",
    'ils': "ils ont atteint",
    'elles': "elles ont atteint"
  },
  'craindre': {
    'je': "j'ai craint",
    'tu': "tu as craint",
    'il': "il a craint",
    'elle': "elle a craint",
    'on': "on a craint",
    'nous': "nous avons craint",
    'vous': "vous avez craint",
    'ils': "ils ont craint",
    'elles': "elles ont craint"
  },
  'éteindre': {
    'je': "j'ai éteint",
    'tu': "tu as éteint",
    'il': "il a éteint",
    'elle': "elle a éteint",
    'on': "on a éteint",
    'nous': "nous avons éteint",
    'vous': "vous avez éteint",
    'ils': "ils ont éteint",
    'elles': "elles ont éteint"
  },
  'joindre': {
    'je': "j'ai joint",
    'tu': "tu as joint",
    'il': "il a joint",
    'elle': "elle a joint",
    'on': "on a joint",
    'nous': "nous avons joint",
    'vous': "vous avez joint",
    'ils': "ils ont joint",
    'elles': "elles ont joint"
  },
  'peindre': {
    'je': "j'ai peint",
    'tu': "tu as peint",
    'il': "il a peint",
    'elle': "elle a peint",
    'on': "on a peint",
    'nous': "nous avons peint",
    'vous': "vous avez peint",
    'ils': "ils ont peint",
    'elles': "elles ont peint"
  },
  'clore': {
    'je': "j'ai clos",
    'tu': "tu as clos",
    'il': "il a clos",
    'elle': "elle a clos",
    'on': "on a clos",
    'nous': "nous avons clos",
    'vous': "vous avez clos",
    'ils': "ils ont clos",
    'elles': "elles ont clos"
  },
  'inclure': {
    'je': "j'ai inclus",
    'tu': "tu as inclus",
    'il': "il a inclus",
    'elle': "elle a inclus",
    'on': "on a inclus",
    'nous': "nous avons inclus",
    'vous': "vous avez inclus",
    'ils': "ils ont inclus",
    'elles': "elles ont inclus"
  },
  'cuire': {
    'je': "j'ai cuit",
    'tu': "tu as cuit",
    'il': "il a cuit",
    'elle': "elle a cuit",
    'on': "on a cuit",
    'nous': "nous avons cuit",
    'vous': "vous avez cuit",
    'ils': "ils ont cuit",
    'elles': "elles ont cuit"
  },
  'resoudre': {
    'je': "j'ai résolu",
    'tu': "tu as résolu",
    'il': "il a résolu",
    'elle': "elle a résolu",
    'on': "on a résolu",
    'nous': "nous avons résolu",
    'vous': "vous avez résolu",
    'ils': "ils ont résolu",
    'elles': "elles ont résolu"
  },
  'absoudre': {
    'je': "j'ai absous",
    'tu': "tu as absous",
    'il': "il a absous",
    'elle': "elle a absous",
    'on': "on a absous",
    'nous': "nous avons absous",
    'vous': "vous avez absous",
    'ils': "ils ont absous",
    'elles': "elles ont absous"
  },
  'se lever': {
    'je': 'je me suis levé',
    'tu': 'tu t’es levé',
    'il': 'il s’est levé',
    'elle': 'elle s’est levée',
    'on': 'on s’est levé',
    'nous': 'nous nous sommes levés',
    'vous': 'vous vous êtes levés',
    'ils': 'ils se sont levés',
    'elles': 'elles se sont levées'
  },
  'se coucher': {
    'je': 'je me suis couché',
    'tu': 'tu t’es couché',
    'il': 'il s’est couché',
    'elle': 'elle s’est couchée',
    'on': 'on s’est couché',
    'nous': 'nous nous sommes couchés',
    'vous': 'vous vous êtes couchés',
    'ils': 'ils se sont couchés',
    'elles': 'elles se sont couchées'
  },
  's’habiller': {
    'je': 'je me suis habillé',
    'tu': 'tu t’es habillé',
    'il': 'il s’est habillé',
    'elle': 'elle s’est habillée',
    'on': 'on s’est habillé',
    'nous': 'nous nous sommes habillés',
    'vous': 'vous vous êtes habillés',
    'ils': 'ils se sont habillés',
    'elles': 'elles se sont habillées'
  },
  'se laver': {
    'je': 'je me suis lavé',
    'tu': 'tu t’es lavé',
    'il': 'il s’est lavé',
    'elle': 'elle s’est lavée',
    'on': 'on s’est lavé',
    'nous': 'nous nous sommes lavés',
    'vous': 'vous vous êtes lavés',
    'ils': 'ils se sont lavés',
    'elles': 'elles se sont lavées'
  },
  'se brosser': {
    'je': 'je me suis brossé',
    'tu': 'tu t’es brossé',
    'il': 'il s’est brossé',
    'elle': 'elle s’est brossée',
    'on': 'on s’est brossé',
    'nous': 'nous nous sommes brossés',
    'vous': 'vous vous êtes brossés',
    'ils': 'ils se sont brossés',
    'elles': 'elles se sont brossées'
  },
  'se réveiller': {
    'je': 'je me suis réveillé',
    'tu': 'tu t’es réveillé',
    'il': 'il s’est réveillé',
    'elle': 'elle s’est réveillée',
    'on': 'on s’est réveillé',
    'nous': 'nous nous sommes réveillés',
    'vous': 'vous vous êtes réveillés',
    'ils': 'ils se sont réveillés',
    'elles': 'elles se sont réveillées'
  },
  'se reposer': {
    'je': 'je me suis reposé',
    'tu': 'tu t’es reposé',
    'il': 'il s’est reposé',
    'elle': 'elle s’est reposée',
    'on': 'on s’est reposé',
    'nous': 'nous nous sommes reposés',
    'vous': 'vous vous êtes reposés',
    'ils': 'ils se sont reposés',
    'elles': 'elles se sont reposées'
  },
  'se dépêcher': {
    'je': 'je me suis dépêché',
    'tu': 'tu t’es dépêché',
    'il': 'il s’est dépêché',
    'elle': 'elle s’est dépêchée',
    'on': 'on s’est dépêché',
    'nous': 'nous nous sommes dépêchés',
    'vous': 'vous vous êtes dépêchés',
    'ils': 'ils se sont dépêchés',
    'elles': 'elles se sont dépêchées'
  },
  'se souvenir': {
    'je': 'je me suis souvenu',
    'tu': 'tu t’es souvenu',
    'il': 'il s’est souvenu',
    'elle': 'elle s’est souvenue',
    'on': 'on s’est souvenu',
    'nous': 'nous nous sommes souvenus',
    'vous': 'vous vous êtes souvenus',
    'ils': 'ils se sont souvenus',
    'elles': 'elles se sont souvenues'
  },
  'se rendre compte': {
    'je': 'je me suis rendu compte',
    'tu': 'tu t’es rendu compte',
    'il': 'il s’est rendu compte',
    'elle': 'elle s’est rendue compte',
    'on': 'on s’est rendu compte',
    'nous': 'nous nous sommes rendus compte',
    'vous': 'vous vous êtes rendus compte',
    'ils': 'ils se sont rendus compte',
    'elles': 'elles se sont rendues compte'
  },
  's’intéresser': {
    'je': 'je me suis intéressé',
    'tu': 'tu t’es intéressé',
    'il': 'il s’est intéressé',
    'elle': 'elle s’est intéressée',
    'on': 'on s’est intéressé',
    'nous': 'nous nous sommes intéressés',
    'vous': 'vous vous êtes intéressés',
    'ils': 'ils se sont intéressés',
    'elles': 'elles se sont intéressées'
  },
  's’ennuyer': {
    'je': 'je me suis ennuyé',
    'tu': 'tu t’es ennuyé',
    'il': 'il s’est ennuyé',
    'elle': 'elle s’est ennuyée',
    'on': 'on s’est ennuyé',
    'nous': 'nous nous sommes ennuyés',
    'vous': 'vous vous êtes ennuyés',
    'ils': 'ils se sont ennuyés',
    'elles': 'elles se sont ennuyées'
  },
  'se fâcher': {
    'je': 'je me suis fâché',
    'tu': 'tu t’es fâché',
    'il': 'il s’est fâché',
    'elle': 'elle s’est fâchée',
    'on': 'on s’est fâché',
    'nous': 'nous nous sommes fâchés',
    'vous': 'vous vous êtes fâchés',
    'ils': 'ils se sont fâchés',
    'elles': 'elles se sont fâchées'
  },
  'se tromper': {
    'je': 'je me suis trompé',
    'tu': 'tu t’es trompé',
    'il': 'il s’est trompé',
    'elle': 'elle s’est trompée',
    'on': 'on s’est trompé',
    'nous': 'nous nous sommes trompés',
    'vous': 'vous vous êtes trompés',
    'ils': 'ils se sont trompés',
    'elles': 'elles se sont trompées'
  },
  'se taire': {
    'je': 'je me suis tu',
    'tu': 'tu t’es tu',
    'il': 'il s’est tu',
    'elle': 'elle s’est tue',
    'on': 'on s’est tu',
    'nous': 'nous nous sommes tus',
    'vous': 'vous vous êtes tus',
    'ils': 'ils se sont tus',
    'elles': 'elles se sont tues'
  },
  's’asseoir': {
    'je': 'je me suis assis',
    'tu': 'tu t’es assis',
    'il': 'il s’est assis',
    'elle': 'elle s’est assise',
    'on': 'on s’est assis',
    'nous': 'nous nous sommes assis',
    'vous': 'vous vous êtes assis',
    'ils': 'ils se sont assis',
    'elles': 'elles se sont assises'
  },
  's’entendre avec': {
    'je': 'je me suis entendu',
    'tu': 'tu t’es entendu',
    'il': 'il s’est entendu',
    'elle': 'elle s’est entendue',
    'on': 'on s’est entendu',
    'nous': 'nous nous sommes entendus',
    'vous': 'vous vous êtes entendus',
    'ils': 'ils se sont entendus',
    'elles': 'elles se sont entendues'
  },
  'se disputer (avec)': {
    'je': 'je me suis disputé',
    'tu': 'tu t’es disputé',
    'il': 'il s’est disputé',
    'elle': 'elle s’est disputée',
    'on': 'on s’est disputé',
    'nous': 'nous nous sommes disputés',
    'vous': 'vous vous êtes disputés',
    'ils': 'ils se sont disputés',
    'elles': 'elles se sont disputées'
  },
  'se marier (avec)': {
    'je': 'je me suis marié',
    'tu': 'tu t’es marié',
    'il': 'il s’est marié',
    'elle': 'elle s’est mariée',
    'on': 'on s’est marié',
    'nous': 'nous nous sommes mariés',
    'vous': 'vous vous êtes mariés',
    'ils': 'ils se sont mariés',
    'elles': 'elles se sont mariées'
  },
  'se divorcer': {
    'je': 'je me suis divorcé',
    'tu': 'tu t’es divorcé',
    'il': 'il s’est divorcé',
    'elle': 'elle s’est divorcée',
    'on': 'on s’est divorcé',
    'nous': 'nous nous sommes divorcés',
    'vous': 'vous vous êtes divorcés',
    'ils': 'ils se sont divorcés',
    'elles': 'elles se sont divorcées'
  },
  'se battre': {
    'je': 'je me suis battu',
    'tu': 'tu t’es battu',
    'il': 'il s’est battu',
    'elle': 'elle s’est battue',
    'on': 'on s’est battu',
    'nous': 'nous nous sommes battus',
    'vous': 'vous vous êtes battus',
    'ils': 'ils se sont battus',
    'elles': 'elles se sont battues'
  },
  's’en aller': {
    'je': 'je me suis en allé',
    'tu': 'tu t’es en allé',
    'il': 'il s’est en allé',
    'elle': 'elle s’est en allée',
    'on': 'on s’est en allé',
    'nous': 'nous nous sommes en allés',
    'vous': 'vous vous êtes en allés',
    'ils': 'ils se sont en allés',
    'elles': 'elles se sont en allées'
  },
  'se rendre': {
    'je': 'je me suis rendu',
    'tu': 'tu t’es rendu',
    'il': 'il s’est rendu',
    'elle': 'elle s’est rendue',
    'on': 'on s’est rendu',
    'nous': 'nous nous sommes rendus',
    'vous': 'vous vous êtes rendus',
    'ils': 'ils se sont rendus',
    'elles': 'elles se sont rendues'
  },
  'se servir': {
    'je': 'je me suis servi',
    'tu': 'tu t’es servi',
    'il': 'il s’est servi',
    'elle': 'elle s’est servie',
    'on': 'on s’est servi',
    'nous': 'nous nous sommes servis',
    'vous': 'vous vous êtes servis',
    'ils': 'ils se sont servis',
    'elles': 'elles se sont servies'
  },
  's’apercevoir': {
    'je': 'je me suis aperçu',
    'tu': 'tu t’es aperçu',
    'il': 'il s’est aperçu',
    'elle': 'elle s’est aperçue',
    'on': 'on s’est aperçu',
    'nous': 'nous nous sommes aperçus',
    'vous': 'vous vous êtes aperçus',
    'ils': 'ils se sont aperçus',
    'elles': 'elles se sont aperçues'
  },
  'se douter': {
    'je': 'je me suis douté',
    'tu': 'tu t’es douté',
    'il': 'il s’est douté',
    'elle': 'elle s’est doutée',
    'on': 'on s’est douté',
    'nous': 'nous nous sommes doutés',
    'vous': 'vous vous êtes doutés',
    'ils': 'ils se sont doutés',
    'elles': 'elles se sont doutées'
  },
  'se passer': {
    'je': 'je me suis passé',
    'tu': 'tu t’es passé',
    'il': 'il s’est passé',
    'elle': 'elle s’est passée',
    'on': 'on s’est passé',
    'nous': 'nous nous sommes passés',
    'vous': 'vous vous êtes passés',
    'ils': 'ils se sont passés',
    'elles': 'elles se sont passées'
  },
  'se trouver': {
    'je': 'je me suis trouvé',
    'tu': 'tu t’es trouvé',
    'il': 'il s’est trouvé',
    'elle': 'elle s’est trouvée',
    'on': 'on s’est trouvé',
    'nous': 'nous nous sommes trouvés',
    'vous': 'vous vous êtes trouvés',
    'ils': 'ils se sont trouvés',
    'elles': 'elles se sont trouvées'
  },
  'se mettre': {
    'je': 'je me suis mis',
    'tu': 'tu t’es mis',
    'il': 'il s’est mis',
    'elle': 'elle s’est mise',
    'on': 'on s’est mis',
    'nous': 'nous nous sommes mis',
    'vous': 'vous vous êtes mis',
    'ils': 'ils se sont mis',
    'elles': 'elles se sont mises'
  },
  'se faire': {
    'je': 'je me suis fait',
    'tu': 'tu t’es fait',
    'il': 'il s’est fait',
    'elle': 'elle s’est faite',
    'on': 'on s’est fait',
    'nous': 'nous nous sommes faits',
    'vous': 'vous vous êtes faits',
    'ils': 'ils se sont faits',
    'elles': 'elles se sont faites'
  },
  'se demander': {
    'je': 'je me suis demandé',
    'tu': 'tu t’es demandé',
    'il': 'il s’est demandé',
    'elle': 'elle s’est demandée',
    'on': 'on s’est demandé',
    'nous': 'nous nous sommes demandés',
    'vous': 'vous vous êtes demandés',
    'ils': 'ils se sont demandés',
    'elles': 'elles se sont demandées'
  },
  'se plaindre': {
    'je': 'je me suis plaint',
    'tu': 'tu t’es plaint',
    'il': 'il s’est plaint',
    'elle': 'elle s’est plainte',
    'on': 'on s’est plaint',
    'nous': 'nous nous sommes plaints',
    'vous': 'vous vous êtes plaints',
    'ils': 'ils se sont plaints',
    'elles': 'elles se sont plaintes'
  },
  'se voir': {
    'je': 'je me suis vu',
    'tu': 'tu t’es vu',
    'il': 'il s’est vu',
    'elle': 'elle s’est vue',
    'on': 'on s’est vu',
    'nous': 'nous nous sommes vus',
    'vous': 'vous vous êtes vus',
    'ils': 'ils se sont vus',
    'elles': 'elles se sont vues'
  },
  's’imaginer': {
    'je': 'je me suis imaginé',
    'tu': 'tu t’es imaginé',
    'il': 'il s’est imaginé',
    'elle': 'elle s’est imaginée',
    'on': 'on s’est imaginé',
    'nous': 'nous nous sommes imaginés',
    'vous': 'vous vous êtes imaginés',
    'ils': 'ils se sont imaginés',
    'elles': 'elles se sont imaginées'
  },
  's’efforcer': {
    'je': 'je me suis efforcé',
    'tu': 'tu t’es efforcé',
    'il': 'il s’est efforcé',
    'elle': 'elle s’est efforcée',
    'on': 'on s’est efforcé',
    'nous': 'nous nous sommes efforcés',
    'vous': 'vous vous êtes efforcés',
    'ils': 'ils se sont efforcés',
    'elles': 'elles se sont efforcées'
  },
  's’évanouir': {
    'je': 'je me suis évanoui',
    'tu': 'tu t’es évanoui',
    'il': 'il s’est évanoui',
    'elle': 'elle s’est évanouie',
    'on': 'on s’est évanoui',
    'nous': 'nous nous sommes évanouis',
    'vous': 'vous vous êtes évanouis',
    'ils': 'ils se sont évanouis',
    'elles': 'elles se sont évanouies'
  },
  's’indigner': {
    'je': 'je me suis indigné',
    'tu': 'tu t’es indigné',
    'il': 'il s’est indigné',
    'elle': 'elle s’est indignée',
    'on': 'on s’est indigné',
    'nous': 'nous nous sommes indignés',
    'vous': 'vous vous êtes indignés',
    'ils': 'ils se sont indignés',
    'elles': 'elles se sont indignées'
  },
  's’épanouir': {
    'je': 'je me suis épanoui',
    'tu': 'tu t’es épanoui',
    'il': 'il s’est épanoui',
    'elle': 'elle s’est épanouie',
    'on': 'on s’est épanoui',
    'nous': 'nous nous sommes épanouis',
    'vous': 'vous vous êtes épanouis',
    'ils': 'ils se sont épanouis',
    'elles': 'elles se sont épanouies'
  },
  's’en sortir': {
    'je': 'je m’en suis sorti',
    'tu': 'tu t’en es sorti',
    'il': 'il s’en est sorti',
    'elle': 'elle s’en est sortie',
    'on': 'on s’en est sorti',
    'nous': 'nous nous en sommes sortis',
    'vous': 'vous vous en êtes sortis',
    'ils': 'ils s’en sont sortis',
    'elles': 'elles s’en sont sorties'
  },
  's’attendre': {
    'je': 'je me suis attendu',
    'tu': 'tu t’es attendu',
    'il': 'il s’est attendu',
    'elle': 'elle s’est attendue',
    'on': 'on s’est attendu',
    'nous': 'nous nous sommes attendus',
    'vous': 'vous vous êtes attendus',
    'ils': 'ils se sont attendus',
    'elles': 'elles se sont attendues'
  },
  's’interroger': {
    'je': 'je me suis interrogé',
    'tu': 'tu t’es interrogé',
    'il': 'il s’est interrogé',
    'elle': 'elle s’est interrogée',
    'on': 'on s’est interrogé',
    'nous': 'nous nous sommes interrogés',
    'vous': 'vous vous êtes interrogés',
    'ils': 'ils se sont interrogés',
    'elles': 'elles se sont interrogées'
  },
  'se heurter': {
    'je': 'je me suis heurté',
    'tu': 'tu t’es heurté',
    'il': 'il s’est heurté',
    'elle': 'elle s’est heurtée',
    'on': 'on s’est heurté',
    'nous': 'nous nous sommes heurtés',
    'vous': 'vous vous êtes heurtés',
    'ils': 'ils se sont heurtés',
    'elles': 'elles se sont heurtées'
  },
  'se méfier': {
    'je': 'je me suis méfié',
    'tu': 'tu t’es méfié',
    'il': 'il s’est méfié',
    'elle': 'elle s’est méfiée',
    'on': 'on s’est méfié',
    'nous': 'nous nous sommes méfiés',
    'vous': 'vous vous êtes méfiés',
    'ils': 'ils se sont méfiés',
    'elles': 'elles se sont méfiées'
  },
  'se replier sur soi-même': {
    'je': 'je me suis replié sur moi-même',
    'tu': 'tu t’es replié sur toi-même',
    'il': 'il s’est replié sur lui-même',
    'elle': 'elle s’est repliée sur elle-même',
    'on': 'on s’est replié sur soi-même',
    'nous': 'nous nous sommes repliés sur nous-mêmes',
    'vous': 'vous vous êtes repliés sur vous-mêmes',
    'ils': 'ils se sont repliés sur eux-mêmes',
    'elles': 'elles se sont repliées sur elles-mêmes'
  },
  'se raviser': {
    'je': 'je me suis ravisé',
    'tu': 'tu t’es ravisé',
    'il': 'il s’est ravisé',
    'elle': 'elle s’est ravisée',
    'on': 'on s’est ravisé',
    'nous': 'nous nous sommes ravisés',
    'vous': 'vous vous êtes ravisés',
    'ils': 'ils se sont ravisés',
    'elles': 'elles se sont ravisées'
  },
  'se débrouiller': {
    'je': 'je me suis débrouillé',
    'tu': 'tu t’es débrouillé',
    'il': 'il s’est débrouillé',
    'elle': 'elle s’est débrouillée',
    'on': 'on s’est débrouillé',
    'nous': 'nous nous sommes débrouillés',
    'vous': 'vous vous êtes débrouillés',
    'ils': 'ils se sont débrouillés',
    'elles': 'elles se sont débrouillées'
  },
  'se réconcilier': {
    'je': 'je me suis réconcilié',
    'tu': 'tu t’es réconcilié',
    'il': 'il s’est réconcilié',
    'elle': 'elle s’est réconciliée',
    'on': 'on s’est réconcilié',
    'nous': 'nous nous sommes réconciliés',
    'vous': 'vous vous êtes réconciliés',
    'ils': 'ils se sont réconciliés',
    'elles': 'elles se sont réconciliées'
  },
  'se précipiter': {
    'je': 'je me suis précipité',
    'tu': 'tu t’es précipité',
    'il': 'il s’est précipité',
    'elle': 'elle s’est précipitée',
    'on': 'on s’est précipité',
    'nous': 'nous nous sommes précipités',
    'vous': 'vous vous êtes précipités',
    'ils': 'ils se sont précipités',
    'elles': 'elles se sont précipitées'
  },
  'se figurer': {
    'je': 'je me suis figuré',
    'tu': 'tu t’es figuré',
    'il': 'il s’est figuré',
    'elle': 'elle s’est figurée',
    'on': 'on s’est figuré',
    'nous': 'nous nous sommes figurés',
    'vous': 'vous vous êtes figurés',
    'ils': 'ils se sont figurés',
    'elles': 'elles se sont figurées'
  }
};