// lehetne egy extra layer még benne, hogy pl az éveknek ne legyen több esélye bekerülni, mint  hier-nek, csak mert többen vannak.
// szóval ami egy ilyen azonos egység annak lehetne egy csoportosítása még.
export const timeMarkerPasseCompose = [
    { placement: 'beginningOfSentence', text: 'hier'},
    { placement: 'beginningOfSentence', text: 'avant-hier'},
    { placement: 'beginningOfSentence', text: "hier matin"},
    { placement: 'beginningOfSentence', text: "hier soir"},
    { placement: 'beginningOfSentence', text: "hier après-midi"},
    { placement: 'beginningOfSentence', text: 'ce matin'},
    { placement: 'beginningOfSentence', text: 'dans la matinée'},
    { placement: 'beginningOfSentence', text: 'en fin de matinée'},
    { placement: 'beginningOfSentence', text: 'ce midi'},
    { placement: 'beginningOfSentence', text: 'en début d’après-midi'},
    { placement: 'beginningOfSentence', text: 'cet après-midi'},
    { placement: 'beginningOfSentence', text: 'en fin d’après-midi'},
    { placement: 'beginningOfSentence', text: 'en début de soirée'},
    { placement: 'beginningOfSentence', text: 'ce soir'},
    { placement: 'beginningOfSentence', text: 'dans la soirée'},
    { placement: 'beginningOfSentence', text: 'cette nuit'},
    { placement: 'beginningOfSentence', text: 'en pleine nuit'},
    { placement: 'beginningOfSentence', text: 'la semaine dernière'},
    { placement: 'beginningOfSentence', text: 'le week-end dernier'},
    { placement: 'beginningOfSentence', text: 'le mois dernier'},
    { placement: 'beginningOfSentence', text: 'l’année dernière'},
    { placement: 'beginningOfSentence', text: 'l’hiver dernier'},
    { placement: 'beginningOfSentence', text: 'le printemps dernier'},
    { placement: 'beginningOfSentence', text: 'l’été dernier'},
    { placement: 'beginningOfSentence', text: 'l’automne dernier'},
    { placement: 'beginningOfSentence', text: 'lundi dernier'},
    { placement: 'beginningOfSentence', text: 'mardi dernier'},
    { placement: 'beginningOfSentence', text: 'mercredi dernier'},
    { placement: 'beginningOfSentence', text: 'jeudi dernier'},
    { placement: 'beginningOfSentence', text: 'vendredi dernier'},
    { placement: 'beginningOfSentence', text: 'samedi dernier'},
    { placement: 'beginningOfSentence', text: 'dimanche dernier'},
    { placement: 'beginningOfSentence', text: 'à Noël'},
    { placement: 'beginningOfSentence', text: 'à Pâques'},
    { placement: 'beginningOfSentence', text: 'à la Saint-Valentin'},
    { placement: 'beginningOfSentence', text: 'à Halloween'},
    { placement: 'beginningOfSentence', text: 'à la Fête nationale'},
    { placement: 'beginningOfSentence', text: 'Noël dernier'},
    { placement: 'beginningOfSentence', text: 'Pâques dernier'},
    { placement: 'beginningOfSentence', text: 'la dernière fête de Pâques'},
    { placement: 'beginningOfSentence', text: 'à la fête de la musique'},
    { placement: 'beginningOfSentence', text: 'à la Toussaint'},
    { placement: 'beginningOfSentence', text: 'à la fête des pères'},
    { placement: 'beginningOfSentence', text: 'à la fête des mères'},
    { placement: 'beginningOfSentence', text: 'au mois de janvier'},
    { placement: 'beginningOfSentence', text: 'au mois de février'},
    { placement: 'beginningOfSentence', text: 'au mois de mars'},
    { placement: 'beginningOfSentence', text: "au mois d'avril"},
    { placement: 'beginningOfSentence', text: 'au mois de mai'},
    { placement: 'beginningOfSentence', text: 'au mois de juin'},
    { placement: 'beginningOfSentence', text: 'au mois de juillet'},
    { placement: 'beginningOfSentence', text: "au mois d'août"},
    { placement: 'beginningOfSentence', text: 'au mois de septembre'},
    { placement: 'beginningOfSentence', text: "au mois d'octobre"},
    { placement: 'beginningOfSentence', text: 'au mois de novembre'},
    { placement: 'beginningOfSentence', text: 'au mois de décembre'},
    { placement: 'beginningOfSentence', text: 'il y a une minute'},
    { placement: 'beginningOfSentence', text: 'il y a cinq minutes'},
    { placement: 'beginningOfSentence', text: 'il y a dix minutes'},
    { placement: 'beginningOfSentence', text: 'il y a quinze minutes'},
    { placement: 'beginningOfSentence', text: 'il y a trente minutes'},
    { placement: 'beginningOfSentence', text: 'une demi-heure'},
    { placement: 'beginningOfSentence', text: 'il y a une heure'},
    { placement: 'beginningOfSentence', text: 'il y a deux heures'},
    { placement: 'beginningOfSentence', text: 'il y a trois heures'},
    { placement: 'beginningOfSentence', text: 'il y a un jour'},
    { placement: 'beginningOfSentence', text: 'il y a deux jours'},
    { placement: 'beginningOfSentence', text: 'il y a trois jours'},
    { placement: 'beginningOfSentence', text: 'il y a quatre jours'},
    { placement: 'beginningOfSentence', text: 'il y a dix jours'},
    { placement: 'beginningOfSentence', text: 'il y a une semaine'},
    { placement: 'beginningOfSentence', text: 'il y a deux semaines'},
    { placement: 'beginningOfSentence', text: 'il y a trois semaines'},
    { placement: 'beginningOfSentence', text: 'il y a un mois'},
    { placement: 'beginningOfSentence', text: 'il y a deux mois'},
    { placement: 'beginningOfSentence', text: 'il y a trois mois'},
    { placement: 'beginningOfSentence', text: 'il y a six mois'},
    { placement: 'beginningOfSentence', text: 'il y a un an'},
    { placement: 'beginningOfSentence', text: 'il y a deux ans'},
    { placement: 'beginningOfSentence', text: 'il y a trois ans'},
    { placement: 'beginningOfSentence', text: 'il y a quatre ans'},
    { placement: 'beginningOfSentence', text: 'il y a cinq ans'},
    { placement: 'beginningOfSentence', text: 'il y a plusieurs années'},
    { placement: 'beginningOfSentence', text: 'en 1996'},
    { placement: 'beginningOfSentence', text: 'en 1997'},
    { placement: 'beginningOfSentence', text: 'en 1998'},
    { placement: 'beginningOfSentence', text: 'en 1999'},
    { placement: 'beginningOfSentence', text: 'en 2000'},
    { placement: 'beginningOfSentence', text: 'en 2001'},
    { placement: 'beginningOfSentence', text: 'en 2002'},
    { placement: 'beginningOfSentence', text: 'en 2003'},
    { placement: 'beginningOfSentence', text: 'en 2004'},
    { placement: 'beginningOfSentence', text: 'en 2005'},
    { placement: 'beginningOfSentence', text: 'en 2006'},
    { placement: 'beginningOfSentence', text: 'en 2007'},
    { placement: 'beginningOfSentence', text: 'en 2008'},
    { placement: 'beginningOfSentence', text: 'en 2009'},
    { placement: 'beginningOfSentence', text: 'en 2010'},
    { placement: 'beginningOfSentence', text: 'en 2011'},
    { placement: 'beginningOfSentence', text: 'en 2012'},
    { placement: 'beginningOfSentence', text: 'en 2013'},
    { placement: 'beginningOfSentence', text: 'en 2014'},
    { placement: 'beginningOfSentence', text: 'en 2015'},
    { placement: 'beginningOfSentence', text: 'en 2016'},
    { placement: 'beginningOfSentence', text: 'en 2017'},
    { placement: 'beginningOfSentence', text: 'en 2018'},
    { placement: 'beginningOfSentence', text: 'en 2019'},
    { placement: 'beginningOfSentence', text: 'en 2020'},
    { placement: 'beginningOfSentence', text: 'en 2021'},
    { placement: 'beginningOfSentence', text: 'en 2022'},
    { placement: 'beginningOfSentence', text: 'en 2023'},
    { placement: 'beginningOfSentence', text: 'en 2024'},
    { placement: 'endOfSentence', text: 'hier'},
    { placement: 'endOfSentence', text: 'avant-hier'},
    { placement: 'endOfSentence', text: "hier matin"},
    { placement: 'endOfSentence', text: "hier soir"},
    { placement: 'endOfSentence', text: "hier après-midi"},
    { placement: 'endOfSentence', text: 'ce matin'},
    { placement: 'endOfSentence', text: 'dans la matinée'},
    { placement: 'endOfSentence', text: 'en fin de matinée'},
    { placement: 'endOfSentence', text: 'ce midi'},
    { placement: 'endOfSentence', text: 'en début d’après-midi'},
    { placement: 'endOfSentence', text: 'cet après-midi'},
    { placement: 'endOfSentence', text: 'en fin d’après-midi'},
    { placement: 'endOfSentence', text: 'en début de soirée'},
    { placement: 'endOfSentence', text: 'ce soir'},
    { placement: 'endOfSentence', text: 'dans la soirée'},
    { placement: 'endOfSentence', text: 'cette nuit'},
    { placement: 'endOfSentence', text: 'en pleine nuit'},
    { placement: 'endOfSentence', text: 'la semaine dernière'},
    { placement: 'endOfSentence', text: 'le week-end dernier'},
    { placement: 'endOfSentence', text: 'le mois dernier'},
    { placement: 'endOfSentence', text: 'l’année dernière'},
    { placement: 'endOfSentence', text: 'l’hiver dernier'},
    { placement: 'endOfSentence', text: 'le printemps dernier'},
    { placement: 'endOfSentence', text: 'l’été dernier'},
    { placement: 'endOfSentence', text: 'l’automne dernier'},
    { placement: 'endOfSentence', text: 'lundi dernier'},
    { placement: 'endOfSentence', text: 'mardi dernier'},
    { placement: 'endOfSentence', text: 'mercredi dernier'},
    { placement: 'endOfSentence', text: 'jeudi dernier'},
    { placement: 'endOfSentence', text: 'vendredi dernier'},
    { placement: 'endOfSentence', text: 'samedi dernier'},
    { placement: 'endOfSentence', text: 'dimanche dernier'},
    { placement: 'endOfSentence', text: 'à Noël'},
    { placement: 'endOfSentence', text: 'à Pâques'},
    { placement: 'endOfSentence', text: 'à la Saint-Valentin'},
    { placement: 'endOfSentence', text: 'à Halloween'},
    { placement: 'endOfSentence', text: 'à la Fête nationale'},
    { placement: 'endOfSentence', text: 'Noël dernier'},
    { placement: 'endOfSentence', text: 'Pâques dernier'},
    { placement: 'endOfSentence', text: 'la dernière fête de Pâques'},
    { placement: 'endOfSentence', text: 'à la fête de la musique'},
    { placement: 'endOfSentence', text: 'à la Toussaint'},
    { placement: 'endOfSentence', text: 'à la fête des pères'},
    { placement: 'endOfSentence', text: 'à la fête des mères'},
    { placement: 'endOfSentence', text: 'au mois de janvier'},
    { placement: 'endOfSentence', text: 'au mois de février'},
    { placement: 'endOfSentence', text: 'au mois de mars'},
    { placement: 'endOfSentence', text: "au mois d'avril"},
    { placement: 'endOfSentence', text: 'au mois de mai'},
    { placement: 'endOfSentence', text: 'au mois de juin'},
    { placement: 'endOfSentence', text: 'au mois de juillet'},
    { placement: 'endOfSentence', text: "au mois d'août"},
    { placement: 'endOfSentence', text: 'au mois de septembre'},
    { placement: 'endOfSentence', text: "au mois d'octobre"},
    { placement: 'endOfSentence', text: 'au mois de novembre'},
    { placement: 'endOfSentence', text: 'au mois de décembre'},
    { placement: 'endOfSentence', text: 'il y a une minute'},
    { placement: 'endOfSentence', text: 'il y a cinq minutes'},
    { placement: 'endOfSentence', text: 'il y a dix minutes'},
    { placement: 'endOfSentence', text: 'il y a quinze minutes'},
    { placement: 'endOfSentence', text: 'il y a trente minutes'},
    { placement: 'endOfSentence', text: 'une demi-heure'},
    { placement: 'endOfSentence', text: 'il y a une heure'},
    { placement: 'endOfSentence', text: 'il y a deux heures'},
    { placement: 'endOfSentence', text: 'il y a trois heures'},
    { placement: 'endOfSentence', text: 'il y a un jour'},
    { placement: 'endOfSentence', text: 'il y a deux jours'},
    { placement: 'endOfSentence', text: 'il y a trois jours'},
    { placement: 'endOfSentence', text: 'il y a quatre jours'},
    { placement: 'endOfSentence', text: 'il y a dix jours'},
    { placement: 'endOfSentence', text: 'il y a une semaine'},
    { placement: 'endOfSentence', text: 'il y a deux semaines'},
    { placement: 'endOfSentence', text: 'il y a trois semaines'},
    { placement: 'endOfSentence', text: 'il y a un mois'},
    { placement: 'endOfSentence', text: 'il y a deux mois'},
    { placement: 'endOfSentence', text: 'il y a trois mois'},
    { placement: 'endOfSentence', text: 'il y a six mois'},
    { placement: 'endOfSentence', text: 'il y a un an'},
    { placement: 'endOfSentence', text: 'il y a deux ans'},
    { placement: 'endOfSentence', text: 'il y a trois ans'},
    { placement: 'endOfSentence', text: 'il y a quatre ans'},
    { placement: 'endOfSentence', text: 'il y a cinq ans'},
    { placement: 'endOfSentence', text: 'il y a plusieurs années'},
    { placement: 'endOfSentence', text: 'en 1996'},
    { placement: 'endOfSentence', text: 'en 1997'},
    { placement: 'endOfSentence', text: 'en 1998'},
    { placement: 'endOfSentence', text: 'en 1999'},
    { placement: 'endOfSentence', text: 'en 2000'},
    { placement: 'endOfSentence', text: 'en 2001'},
    { placement: 'endOfSentence', text: 'en 2002'},
    { placement: 'endOfSentence', text: 'en 2003'},
    { placement: 'endOfSentence', text: 'en 2004'},
    { placement: 'endOfSentence', text: 'en 2005'},
    { placement: 'endOfSentence', text: 'en 2006'},
    { placement: 'endOfSentence', text: 'en 2007'},
    { placement: 'endOfSentence', text: 'en 2008'},
    { placement: 'endOfSentence', text: 'en 2009'},
    { placement: 'endOfSentence', text: 'en 2010'},
    { placement: 'endOfSentence', text: 'en 2011'},
    { placement: 'endOfSentence', text: 'en 2012'},
    { placement: 'endOfSentence', text: 'en 2013'},
    { placement: 'endOfSentence', text: 'en 2014'},
    { placement: 'endOfSentence', text: 'en 2015'},
    { placement: 'endOfSentence', text: 'en 2016'},
    { placement: 'endOfSentence', text: 'en 2017'},
    { placement: 'endOfSentence', text: 'en 2018'},
    { placement: 'endOfSentence', text: 'en 2019'},
    { placement: 'endOfSentence', text: 'en 2020'},
    { placement: 'endOfSentence', text: 'en 2021'},
    { placement: 'endOfSentence', text: 'en 2022'},
    { placement: 'endOfSentence', text: 'en 2023'},
    { placement: 'endOfSentence', text: 'en 2024'},
    { placement: 'beginningOfSentence', text: 'd’abord'},
    { placement: 'beginningOfSentence', text: 'ensuite'},
    { placement: 'beginningOfSentence', text: 'puis'},
    { placement: 'beginningOfSentence', text: 'enfin'},
    { placement: 'beginningOfSentence', text: 'après cela'},
    { placement: 'beginningOfSentence', text: 'soudain'},
    { placement: 'beginningOfSentence', text: 'tout à coup'},
]